command /start:
	permission: *
	permission message: &cThis command does not exist
	description: start event
	trigger:
		create a gui with virtual chest inventory with 3 rows named "Are you sure to start the event ?":
			make gui slot 12 with lime wool named "&aYes" with lore "&rI am sure to start the event !":
				close player's inventory
				set {timer-s} to 30
				set {timer-m} to 1
				set {timer} to 1
				broadcast "[&c&lTheEvent580&r] Event starting in 1 minute and 30 seconds."
				loop all players:
					play sound "custom:intro" in voice category with volume 1 to the loop-player
					if loop-player doesn't have permission "group.spectators":
						add 1 to {checking_finished_players}
					if loop-player has permission "theevent580.staff":
						send "[&c&lTheEvent580 - Admin&r] Event countdown / Event started by %executor%" to loop-player
						send "[&c&lTheEvent580 - Admin&r] Event state : &eWaiting&r --> &aStart Countdown" to loop-player
						set {event_state} to "Start Countdown"
					send title "Event starting" with subtitle "in 1 minute and 30 seconds" to loop-player for 3 seconds
			make gui slot 14 with red wool named "&cNo" with lore "&rI am not sure to start the event.":
				close player's inventory
		open the last gui for the player

command /spawn [<player>]:
	description: tp to spawn
	trigger:
		if arg-1 is not set:
			if {jeu_condi} is 0 or -1:
				if {timer} or {timer_save} is 7 or 0 or 1 or 9 or 10 or 8 or "Fin":
					if {finished.%player's uuid%} is true:
						make console execute command "fly %player%"
					if player's game mode is spectator:
						make server execute command "execute in minecraft:overworld run tp %player% 322.081 75.5 341.571 147.5 21.5"
						wait 5 ticks
						set player's game mode to spectator
						force player to fly
						allow fly for player
					if player's game mode is creative:
						make server execute command "execute in minecraft:overworld run tp %player% 322.081 75.5 341.571 147.5 21.5"
						wait 5 ticks
						set player's game mode to creative
						force player to fly
						allow fly for player
					else:
						make server execute command "execute in minecraft:overworld run tp %player% 310.5 67 323.5 0.1 0.1"
						wait 5 ticks
						set player's game mode to adventure
					reveal hidden players of player
					reveal player for all players
					apply saturation without particles to player for 100 days
					set the maximum health of player to 10
					heal player
					if {timer} is 7:
						send "[&c&lTheEvent580 - Admin&r] You are now visible to other players and you can see other players"
					set {hide.%player%} to false
				else:
					send "[&c&lTheEvent580&r] You cannot tp to spawn while playing a minigame"
			else:
				send "[&c&lTheEvent580&r] You cannot tp to spawn while playing a minigame"
		else:
			if player has permission "group.spectators":
				if {jeu_condi} is 0 or -1:
					if {timer} or {timer_save} is 7 or 0 or 1 or 9 or 8 or 10 or "Fin":
						if {finished.%arg-1%} is true:
							make console execute command "fly %arg-1%"
						if arg-1's game mode is spectator:
							make server execute command "execute in minecraft:overworld run tp %arg-1% 322.081 75.5 341.571 147.5 21.5"
							wait 5 ticks
							set arg-1's game mode to spectator
							force arg-1 to fly
							allow fly for arg-1
						if arg-1's game mode is creative:
							make server execute command "execute in minecraft:overworld run tp %arg-1% 322.081 75.5 341.571 147.5 21.5"
							wait 5 ticks
							set arg-1's game mode to creative
							force arg-1 to fly
							allow fly for arg-1
						else:
							make server execute command "execute in minecraft:overworld run tp %arg-1% 310.5 67 323.5 0.1 0.1"
							wait 5 ticks
							set arg-1's game mode to adventure
						apply saturation without particles to arg-1 for 100 days
						set the maximum health of arg-1 to 10
						heal arg-1
						reveal hidden players of arg-1
						reveal arg-1 for all players
						if {timer} is 7:
							send "[&c&lTheEvent580 - Admin&r] You are now visible to other players and you can see other players" to arg-1
						set {hide.%arg-1%} to false
					else:
						send "[&c&lTheEvent580&r] You cannot tp to spawn while playing a minigame"
			else:
				send "[&c&lTheEvent580&r] You cannot tp to spawn while playing a minigame"


command /timer <text> [<text>] [<int>]:
	permission: *
	permission message: &cThis command does not exist
	description: stop / start / set timer
	trigger:
		if arg-1 is "type":
			send "%{timer}%" to player
		if arg-1 is "pause":
			if {timer} is "pause":
				send "[&c&lTheEvent580 - Timer&r] Event is already paused"
			else:
				set {timer_save} to {timer}
				set {timer} to "pause"
				if {jeu_condi} is 5:
					set {courses_boat_timer_status} to false
					set {courses_pied_timer_status} to false
					set {courses_trident_timer_status} to false
				broadcast "[&c&lTheEvent580&r] The Event is currently paused, please wait"
		else if arg-1 is "play":
			set {timer} to {timer_save}
			clear {timer_save}
			if {jeu_condi} is 5:
				set {courses_boat_timer_status} to true
				set {courses_pied_timer_status} to true
				set {courses_trident_timer_status} to true
			broadcast "[&c&lTheEvent580&r] The Event has resumed !"
		else if arg-1 is "mode":
			set {timer_save} to {timer}
			if arg-2 is set:
				if arg-2 is not "pause":
					set {timer} to arg-2 parsed as an integer
				else:
					set {timer} to arg-2
		else if arg-1 is "set":
			if arg-2 and arg-3 is set:
				set {timer-m} to arg-2 parsed as a integer
				set {timer-s} to arg-3
			else:
				send "--> /timer set 1 30 ( example )"
		else if arg-1 is "status":
			if arg-2 is set:
				if arg-2 is "set":
					if arg-3 is set:
						set {timer} to arg-3
				else if arg-2 is "Fin":
					set {timer} to arg-2

command /reset:
	permission: *
	permission message: &cThis command does not exist
	description: reset les variables
	trigger:
		create a gui with virtual chest inventory with 3 rows named "Are you sure to reset the event ?":
			make gui slot 12 with lime wool named "&aYes" with lore "&rI am sure to reset the event !":
				close player's inventory
				loop {staff::*}:
					send "[&c&lTheEvent580 - Admin&r] Reset started by %executor%" to loop-value
				make server execute command "clear @a"
				make server execute command "effect clear @a"
				wait 1 seconds
				set {timer} to 0
				set {l6} to "None"
				set {red} to 0
				make server execute command "execute in overworld run fill -2 300 4 2 86 9 minecraft:red_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill -2 300 4 2 86 9 minecraft:red_stained_glass replace minecraft:light_gray_stained_glass"
				set {orange} to 0
				make server execute command "execute in overworld run fill -4 300 4 -9 86 9 minecraft:orange_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill -3 300 4 -9 86 9 minecraft:orange_stained_glass replace minecraft:light_gray_stained_glass"
				set {yellow} to 0
				make server execute command "execute in overworld run fill -2 300 3 -9 86 -2 minecraft:yellow_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill -2 300 3 -9 86 -2 minecraft:yellow_stained_glass replace minecraft:light_gray_stained_glass"
				set {lime} to 0
				make server execute command "execute in overworld run fill -3 300 -3 -9 86 -9 minecraft:lime_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill -3 300 -3 -9 86 -9 minecraft:lime_stained_glass replace minecraft:light_gray_stained_glass"
				set {light_blue} to 0
				make server execute command "execute in overworld run fill -2 300 -2 3 86 -9 minecraft:light_blue_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill -2 300 -2 3 86 -9 minecraft:light_blue_stained_glass replace minecraft:light_gray_stained_glass"
				set {blue} to 0
				make server execute command "execute in overworld run fill 4 300 -3 9 86 -9 minecraft:blue_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill 4 300 -3 9 86 -9 minecraft:blue_stained_glass replace minecraft:light_gray_stained_glass"
				set {purple} to 0
				make server execute command "execute in overworld run fill 3 300 -2 9 86 3 minecraft:purple_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill 3 300 -2 9 86 3 minecraft:purple_stained_glass replace minecraft:light_gray_stained_glass"
				set {pink} to 0
				make server execute command "execute in overworld run fill 3 300 3 9 86 9 minecraft:pink_concrete replace minecraft:light_gray_concrete"
				make server execute command "execute in overworld run fill 3 300 3 9 86 9 minecraft:pink_stained_glass replace minecraft:light_gray_stained_glass"
				set {white} to 0
				set {light_gray} to 0
				wait 5 ticks
				make server execute command "//world world"
				make server execute command "//pos1 8,98,-8"
				make server execute command "//pos2 -8,99,8"
				make server execute command "//replace sticky_piston air"
				make server execute command "execute in overworld run fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab"
				make server execute command "execute in overworld run fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab"
				make server execute command "execute in overworld run fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab"
				make server execute command "execute in overworld run fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab"
				make server execute command "execute in overworld run fill 8 249 3 -8 249 3 minecraft:glass"
				make server execute command "execute in overworld run fill 8 249 -3 -8 249 -3 minecraft:glass"
				make server execute command "execute in overworld run fill -3 249 -8 -3 249 8 minecraft:glass"
				make server execute command "execute in overworld run fill 3 249 -8 3 249 8 minecraft:glass"
				make server execute command "execute in overworld run fill 8 251 3 -8 251 3 minecraft:air"
				make server execute command "execute in overworld run fill 8 251 -3 -8 251 -3 minecraft:air"
				make server execute command "execute in overworld run fill -3 251 -8 -3 251 8 minecraft:air"
				make server execute command "execute in overworld run fill 3 251 -8 3 251 8 minecraft:air"
				make server execute command "//pos1 8,248,-8"
				make server execute command "//pos2 -8,248,8"
				make server execute command "//replace air sticky_piston[facing=up,extended=false]"
				make server execute command "kill @e[type=minecraft:item]"
				make server execute command "fill 8 247 3 -8 247 3 minecraft:redstone_block"
				make server execute command "fill 8 247 -3 -8 247 -3 minecraft:redstone_block"
				make server execute command "fill -3 247 -8 -3 247 8 minecraft:redstone_block"
				make server execute command "fill 3 247 -8 3 247 8 minecraft:redstone_block"
				make server execute command "fill 8 247 3 -8 247 3 minecraft:redstone_block"
				make server execute command "fill 8 247 -3 -8 247 -3 minecraft:redstone_block"
				make server execute command "fill -3 247 -8 -3 247 8 minecraft:redstone_block"
				make server execute command "fill 3 247 -8 3 247 8 minecraft:redstone_block"
				make server execute command "fill 8 253 9 -8 250 -9 air replace minecraft:polished_deepslate"
				make server execute command "xp set @a 0 levels"
				make server execute command "xp set @a 0 points"
				make server execute command "stopsound @a"
				set {mute.server} to false
				set {finished_players} to 0
				set {online_players} to 0
				set {checking_finished_players} to 0
				set {damage} to 1
				set {x} to 0.5
				set {y} to 102
				set {z} to 5.5
				set {world} to world
				set {pitch} to 0
				set {yaw} to 0
				set {multiplier} to 1
				set {jeu} to 0
				set {jeu_nom} to "&rStart"
				set {jeu_condi} to 0
				set {scoreboard.pos} to 0
				set {map_sg} to 0
				set {ready_player} to 0
				clear {maps::*}
				clear {finished::*}
				clear {games::*}
				set {vote_swap} to false
				resetNPCs()
				set {race_timer} to false
				set {race_lap_1_finished} to false
				set {race_lap_2_finished} to false
				set {race_lap_3_finished} to false
				loop all players:
					clear {ride.%loop-player%}
					add 1 to {online_players}
					make loop-player execute command "spawn"
					apply saturation without particles to loop-player for 100 days
					set {gamemode.%loop-player%} to 2
					set {points_game.%loop-player's uuid%} to 0
					set {points.%loop-player's uuid%} to 0
					if {total_points.%loop-player's uuid%} is not set:
						set {total_points.%loop-player's uuid%} to 0
						set {total_points_event.%loop-player's uuid%} to 0
					else:
						remove {total_points_event.%loop-player's uuid%} from {total_points.%loop-player's uuid%}
						set {total_points_event.%loop-player's uuid%} to 0
					#Parkour
					set {parkour_checkpoint.%loop-player%} to "Start"
					#Dropper
					set {dropper_level.%loop-player%} to 0
					#Find The Button
					set {ftb_fin.%loop-player%} to 0
					#Multilap
					set {race_checkpoint.%loop-player%} to 0
					set {race_lap.%loop-player%} to 1
					set {race_total_time.%loop-player%} to 0
					set {race_lap_time.%loop-player%} to 0
					set {race_boat.%loop-player%} to false
					#Laby
					#set {laby_level.%loop-player%} to "Start"
					#SG
					set {alive.%loop-player's uuid%} to true
					#Bow PVP
					set {health.%loop-player%} to 10
					#For Event : 
					if loop-player has permission "group.spectators":
						remove 1 from {online_players}
					set {ready_check.%loop-player%} to false
					set {ready.%loop-player%} to true
					#Spawn
					make server execute command "gamemode adventure %loop-player%"
					set the maximum health of loop-player to 10
					heal loop-player
					reveal hidden players of loop-player
					if {flag.%loop-player%} is not false:
						set helmet of loop-player to carrot on a stick named "%{flag.%loop-player%}%"
					if loop-player has permission "theevent580.staff":
						send "[&c&lTheEvent580 - Admin&r] Reset ended" to loop-player
						send "[&c&lTheEvent580 - Admin&r] Event state : &e%{event_state}%&r --> &aWaiting" to loop-player
						set {event_state} to "Waiting"
				broadcast "[&c&lTheEvent580&r] Event has been reset."
			make gui slot 14 with red wool named "&cNo" with lore "&rI am not sure to reset the event.":
				close player's inventory
		open the last gui for the player

command /consolestart:
	permission: *
	permission message: &cThis command does not exist
	description: start event
	trigger:
		set {timer-s} to 30
		set {timer-m} to 1
		set {timer} to 1
		broadcast "[&c&lTheEvent580&r] Event starting in 1 minute and 30 seconds."
		loop all players:
			play sound "custom:intro" in voice category with volume 1 to the loop-player
			if loop-player doesn't have permission "group.spectators":
				add 1 to {checking_finished_players}
			if loop-player has permission "theevent580.staff":
				send "[&c&lTheEvent580 - Admin&r] Event countdown / Event started by Console" to loop-player
				send "[&c&lTheEvent580 - Admin&r] Event state : &eWaiting&r --> &aStart Countdown" to loop-player
				set {event_state} to "Start Countdown"
			send title "Event starting" with subtitle "in 1 minute and 30 seconds" to loop-player for 3 seconds

command /consolereset:
	permission: *
	permission message: &cThis command does not exist
	description: reset event
	trigger:
		loop {staff::*}:
			send "[&c&lTheEvent580 - Admin&r] Reset started by %executor%" to loop-value
		make server execute command "clear @a"
		make server execute command "effect clear @a"
		wait 1 seconds
		set {timer} to 0
		set {l6} to "None"
		set {red} to 0
		make server execute command "execute in overworld run fill -2 300 4 2 86 9 minecraft:red_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill -2 300 4 2 86 9 minecraft:red_stained_glass replace minecraft:light_gray_stained_glass"
		set {orange} to 0
		make server execute command "execute in overworld run fill -4 300 4 -9 86 9 minecraft:orange_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill -3 300 4 -9 86 9 minecraft:orange_stained_glass replace minecraft:light_gray_stained_glass"
		set {yellow} to 0
		make server execute command "execute in overworld run fill -2 300 3 -9 86 -2 minecraft:yellow_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill -2 300 3 -9 86 -2 minecraft:yellow_stained_glass replace minecraft:light_gray_stained_glass"
		set {lime} to 0
		make server execute command "execute in overworld run fill -3 300 -3 -9 86 -9 minecraft:lime_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill -3 300 -3 -9 86 -9 minecraft:lime_stained_glass replace minecraft:light_gray_stained_glass"
		set {light_blue} to 0
		make server execute command "execute in overworld run fill -2 300 -2 3 86 -9 minecraft:light_blue_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill -2 300 -2 3 86 -9 minecraft:light_blue_stained_glass replace minecraft:light_gray_stained_glass"
		set {blue} to 0
		make server execute command "execute in overworld run fill 4 300 -3 9 86 -9 minecraft:blue_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill 4 300 -3 9 86 -9 minecraft:blue_stained_glass replace minecraft:light_gray_stained_glass"
		set {purple} to 0
		make server execute command "execute in overworld run fill 3 300 -2 9 86 3 minecraft:purple_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill 3 300 -2 9 86 3 minecraft:purple_stained_glass replace minecraft:light_gray_stained_glass"
		set {pink} to 0
		make server execute command "execute in overworld run fill 3 300 3 9 86 9 minecraft:pink_concrete replace minecraft:light_gray_concrete"
		make server execute command "execute in overworld run fill 3 300 3 9 86 9 minecraft:pink_stained_glass replace minecraft:light_gray_stained_glass"
		set {white} to 0
		set {light_gray} to 0
		wait 5 ticks
		make server execute command "//world world"
		make server execute command "//pos1 8,98,-8"
		make server execute command "//pos2 -8,99,8"
		make server execute command "//replace sticky_piston air"
		make server execute command "execute in overworld run fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab"
		make server execute command "execute in overworld run fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab"
		make server execute command "execute in overworld run fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab"
		make server execute command "execute in overworld run fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab"
		make server execute command "execute in overworld run fill 8 249 3 -8 249 3 minecraft:glass"
		make server execute command "execute in overworld run fill 8 249 -3 -8 249 -3 minecraft:glass"
		make server execute command "execute in overworld run fill -3 249 -8 -3 249 8 minecraft:glass"
		make server execute command "execute in overworld run fill 3 249 -8 3 249 8 minecraft:glass"
		make server execute command "execute in overworld run fill 8 251 3 -8 251 3 minecraft:air"
		make server execute command "execute in overworld run fill 8 251 -3 -8 251 -3 minecraft:air"
		make server execute command "execute in overworld run fill -3 251 -8 -3 251 8 minecraft:air"
		make server execute command "execute in overworld run fill 3 251 -8 3 251 8 minecraft:air"
		make server execute command "//pos1 8,248,-8"
		make server execute command "//pos2 -8,248,8"
		make server execute command "//replace air sticky_piston[facing=up,extended=false]"
		make server execute command "kill @e[type=minecraft:item]"
		make server execute command "fill 8 247 3 -8 247 3 minecraft:redstone_block"
		make server execute command "fill 8 247 -3 -8 247 -3 minecraft:redstone_block"
		make server execute command "fill -3 247 -8 -3 247 8 minecraft:redstone_block"
		make server execute command "fill 3 247 -8 3 247 8 minecraft:redstone_block"
		make server execute command "fill 8 247 3 -8 247 3 minecraft:redstone_block"
		make server execute command "fill 8 247 -3 -8 247 -3 minecraft:redstone_block"
		make server execute command "fill -3 247 -8 -3 247 8 minecraft:redstone_block"
		make server execute command "fill 3 247 -8 3 247 8 minecraft:redstone_block"
		make server execute command "fill 8 253 9 -8 250 -9 air replace minecraft:polished_deepslate"
		make server execute command "xp set @a 0 levels"
		make server execute command "xp set @a 0 points"
		make server execute command "stopsound @a"
		set {mute.server} to false
		set {finished_players} to 0
		set {online_players} to 0
		set {checking_finished_players} to 0
		set {damage} to 1
		set {x} to 0.5
		set {y} to 102
		set {z} to 5.5
		set {world} to world
		set {pitch} to 0
		set {yaw} to 0
		set {multiplier} to 1
		set {jeu} to 0
		set {jeu_nom} to "&rStart"
		set {jeu_condi} to 0
		set {scoreboard.pos} to 0
		set {map_sg} to 0
		set {ready_player} to 0
		clear {maps::*}
		clear {finished::*}
		clear {games::*}
		set {vote_swap} to false
		resetNPCs()
		set {race_timer} to false
		set {race_lap_1_finished} to false
		set {race_lap_2_finished} to false
		set {race_lap_3_finished} to false
		loop all players:
			clear {ride.%loop-player%}
			add 1 to {online_players}
			make loop-player execute command "spawn"
			apply saturation without particles to loop-player for 100 days
			set {gamemode.%loop-player%} to 2
			set {points_game.%loop-player's uuid%} to 0
			set {points.%loop-player's uuid%} to 0
			if {total_points.%loop-player's uuid%} is not set:
				set {total_points.%loop-player's uuid%} to 0
				set {total_points_event.%loop-player's uuid%} to 0
			else:
				remove {total_points_event.%loop-player's uuid%} from {total_points.%loop-player's uuid%}
				set {total_points_event.%loop-player's uuid%} to 0
			#Parkour
			set {parkour_checkpoint.%loop-player%} to "Start"
			#Dropper
			set {dropper_level.%loop-player%} to 0
			#Find The Button
			set {ftb_fin.%loop-player%} to 0
			#Multilap
			set {race_checkpoint.%loop-player%} to 0
			set {race_lap.%loop-player%} to 1
			set {race_total_time.%loop-player%} to 0
			set {race_lap_time.%loop-player%} to 0
			set {race_boat.%loop-player%} to false
			#Laby
			#set {laby_level.%loop-player%} to "Start"
			#SG
			set {alive.%loop-player's uuid%} to true
			#Bow PVP
			set {health.%loop-player%} to 10
			#For Event : 
			if loop-player has permission "group.spectators":
				remove 1 from {online_players}
			set {ready_check.%loop-player%} to false
			set {ready.%loop-player%} to true
			#Spawn
			make server execute command "gamemode adventure %loop-player%"
			set the maximum health of loop-player to 10
			heal loop-player
			reveal hidden players of loop-player
			if {flag.%loop-player%} is not false:
				set helmet of loop-player to carrot on a stick named "%{flag.%loop-player%}%"
			if loop-player has permission "theevent580.staff":
				send "[&c&lTheEvent580 - Admin&r] Reset ended" to loop-player
				send "[&c&lTheEvent580 - Admin&r] Event state : &e%{event_state}%&r --> &aWaiting" to loop-player
				set {event_state} to "Waiting"
		broadcast "[&c&lTheEvent580&r] Event has been reset."

command /parkour:
	permission: *
	permission message: &cThis command does not exist
	description: set le jeu "Parkour"
	trigger:
		make server execute command "execute in minecraft:parkour run tp @a 131.5 129.00 201.5 -90 0"
		set {jeu_condi} to 2
		set {finished_players} to 0
		wait 2 seconds
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				set {points_game.%loop-player's uuid%} to 240 #everyone starts with 240 coins
				set {game_multiplier.%loop-player's uuid%} to 1.0 # everyone starts with a x1.0 multiplier
				set {parkour.next_level_coord.%loop-player's uuid%} to 155
				set {parkour.main_level.%loop-player's uuid%} to 1
				set {parkour.sub_level.%loop-player's uuid%} to 1
				set slot 7 of loop-player to carrot on a stick named "&6Skip level"
				set {parkour.skip.%loop-player's uuid%} to false
				set {parkour.skip_used.%loop-player's uuid%} to false
				set {finished.%loop-player's uuid%} to false
			if {hide.%loop-player's uuid%} = false:
				make console execute command "hide %loop-player%"
			if loop-player has permission "group.spectators":
				set {finished.%loop-player's uuid%} to true
				clear loop-player's inventory
			set {gamemode.%loop-player%} to 2
		wait 2 seconds
		loop all players:
			set loop-player's gamemode to adventure
			if loop-player has permission "group.spectators":
				force loop-player to fly
				allow fly for loop-player


command /bingo:
	permission: *
	permission message: &cThis command does not exist
	description: set le jeu "Bingo"
	trigger:
		make server execute command "execute in minecraft:bingo run tp @a 999889.0 153 999932.5 0 0"
		set {jeu_condi} to 3
		set {finished_players} to 0
		set {damage} to 2
		make server execute command "clear @a"
		loop all players:
			if loop-player has permission "group.spectators":
				reveal hidden players of loop-player
				force loop-player to fly
				allow fly for loop-player
				hide loop-player from all entities
		loop all players:
			loop 5 times:
				set slot 0 of loop-player to iron sword of unbreaking 250 and sharpness 1 named "&eIron sword"
				set slot 1 of loop-player to iron axe of unbreaking 250 and efficiency 2 named "&eIron axe"
				set slot 2 of loop-player to iron pickaxe of unbreaking 250 and efficiency 2 and fortune 2 named "&eFortune iron pickaxe"
				set slot 3 of loop-player to iron pickaxe of unbreaking 250 and efficiency 2 and silk touch named "&eSilk touch iron pickaxe"
				set slot 4 of loop-player to iron shovel of unbreaking 250 and efficiency 2 named "&eIron shovel"
				set slot 6 of loop-player to 64 steaks named "&eSteak"
				set helmet of loop-player to chainmail helmet of unbreaking 250 named "&eChainmail helmet"
				set chestplate of loop-player to chainmail chestplate of unbreaking 250 named "&eChainmail chestplate"
				set leggings of loop-player to chainmail leggings of unbreaking 250  named "&eChainmail leggings"
				set boots of loop-player to chainmail boots of unbreaking 250 named "&eChainmail boots"
				set {bingo_cases.%loop-player%} to 0
				set {bingo_case_1.%loop-player%} to false
				set {bingo_case_2.%loop-player%} to false
				set {bingo_case_3.%loop-player%} to false
				set {bingo_case_4.%loop-player%} to false
				set {bingo_case_5.%loop-player%} to false
				set {bingo_case_6.%loop-player%} to false
				set {bingo_case_7.%loop-player%} to false
				set {bingo_case_8.%loop-player%} to false
				set {bingo_case_9.%loop-player%} to false
				set {bingo_fin.%loop-player%} to false
				set {bingo_kill.%loop-player%} to false
				set {finished.%loop-player's uuid%} to false
				wait 5 ticks
				set loop-player's gamemode to adventure
				set slot 7 of loop-player to carrot on a stick named "&r&eTeleport to home"
				set slot 8 of loop-player to paper named "&eYour Bingo card"
		set {bingo_all_cases} to 0
		set {bingo_case_1_completed} to 0
		set {bingo_case_2_completed} to 0
		set {bingo_case_3_completed} to 0
		set {bingo_case_4_completed} to 0
		set {bingo_case_5_completed} to 0
		set {bingo_case_6_completed} to 0
		set {bingo_case_7_completed} to 0
		set {bingo_case_8_completed} to 0
		set {bingo_case_9_completed} to 0
		set {bingo_case_1_1} to false
		set {bingo_case_2_1} to false
		set {bingo_case_3_1} to false
		set {bingo_case_4_1} to false
		set {bingo_case_5_1} to false
		set {bingo_case_6_1} to false
		set {bingo_case_7_1} to false
		set {bingo_case_8_1} to false
		set {bingo_case_9_1} to false
		set {bingo_fin} to false
		set {pts_lvl_1} to 5*{checking_finished_players}
		set {pts_lvl_1} to {pts_lvl_1}*{multiplier}
		set {pts_lvl_2} to 15*{checking_finished_players}
		set {pts_lvl_2} to {pts_lvl_2}*{multiplier}
		set {pts_lvl_3} to 25*{checking_finished_players}
		set {pts_lvl_3} to {pts_lvl_3}*{multiplier}
		set {pts_lvl_4} to 35*{checking_finished_players}
		set {pts_lvl_4} to {pts_lvl_4}*{multiplier}
		set {pts_lvl_5} to 45*{checking_finished_players}
		set {pts_lvl_5} to {pts_lvl_5}*{multiplier}
		set {pts_lvl_6} to 55*{checking_finished_players}
		set {pts_lvl_6} to {pts_lvl_6}*{multiplier}
		set {pts_lvl_7} to 70*{checking_finished_players}
		set {pts_lvl_7} to {pts_lvl_7}*{multiplier}
		set {pts_lvl_8} to 85*{checking_finished_players}
		set {pts_lvl_8} to {pts_lvl_8}*{multiplier}
		set {pts_lvl_9} to 100*{checking_finished_players}
		set {pts_lvl_9} to {pts_lvl_9}*{multiplier}
		make server execute command "//world bingo"
		make server execute command "//pos1 289,64,164"
		make server execute command "//pos2 322,71,132"
		make server execute command "//walls barrier"
		loop all players:
			if loop-player has permission "group.spectators":
				hide loop-player from all players
				clear loop-player's inventory
				set slot 0 of loop-player to compass named "&rTeleport to player"
				set slot 1 of loop-player to feather named "&rChange player's fly speed"
				set slot 7 of loop-player to carrot on a stick named "&r&eTeleport to home"
				set slot 8 of loop-player to paper named "&eYour Bingo card"
				set {finished.%loop-player's uuid%} to true

command /card:
	description: ouvre la carte
	trigger:
		if player doesn't have permission "group.spectators":
			if {jeu_condi} is 3:
				create a gui with virtual chest inventory with 3 rows named "&eYour card":
					if {bingo_case_1.%player%} is false:
						make gui slot 3 with dark oak leaves named "&rDark Oak Leaves / &cNot validated" with lore "&e+%{pts_lvl_1}% ╣"
					if {bingo_case_1.%player%} is true:
						make gui slot 3 with dark oak leaves named "&rDark Oak Leaves / &aValidated" with lore "&e+%{pts_lvl_1}% ╣"
					if {bingo_case_2.%player%} is false:
						make gui slot 4 with mushroom stem named "&rMushroom Stem / &cNot validated" with lore "&e+%{pts_lvl_2}% ╣"
					if {bingo_case_2.%player%} is true:
						make gui slot 4 with mushroom stem named "&rMushroom Stem / &aValidated" with lore "&e+%{pts_lvl_2}% ╣"
					if {bingo_case_3.%player%} is false:
						make gui slot 5 with lime bed named "&rLime Bed / &cNot validated" with lore "&e+%{pts_lvl_3}% ╣"
					if {bingo_case_3.%player%} is true:
						make gui slot 5 with lime bed named "&rLime Bed / &aValidated" with lore "&e+%{pts_lvl_3}% ╣"
					if {bingo_case_4.%player%} is false:
						make gui slot 12 with raw copper block named "&rBlock of Raw Copper / &cNot validated" with lore "&e+%{pts_lvl_4}% ╣"
					if {bingo_case_4.%player%} is true:
						make gui slot 12 with raw copper block named "&rBlock of Raw Copper / &aValidated" with lore "&e+%{pts_lvl_4}% ╣"
					if {bingo_case_5.%player%} is false:
						make gui slot 13 with calibrated sculk sensor named "&rCalibrated Sculk Sensor / &cNot validated" with lore "&e+%{pts_lvl_5}% ╣"
					if {bingo_case_5.%player%} is true:
						make gui slot 13 with calibrated sculk sensor named "&rCalibrated Sculk Sensor / &aValidated" with lore "&e+%{pts_lvl_5}% ╣"
					if {bingo_case_6.%player%} is false:
						make gui slot 14 with waxed cut copper stairs named "&rWaxed Cut Copper Stairs / &cNot validated" with lore "&e+%{pts_lvl_6}% ╣"
					if {bingo_case_6.%player%} is true:
						make gui slot 14 with waxed cut copper stairs named "&rWaxed Cut Copper Stairs / &aValidated" with lore "&e+%{pts_lvl_6}% ╣"
					if {bingo_case_7.%player%} is false:
						make gui slot 21 with blue candle named "&rBlue Candle / &cNot validated" with lore "&e+%{pts_lvl_7}% ╣"
					if {bingo_case_7.%player%} is true:
						make gui slot 21 with blue candle named "&rBlue Candle / &aValidated" with lore "&e+%{pts_lvl_7}% ╣"
					if {bingo_case_8.%player%} is false:
						make gui slot 22 with deepslate emerald ore named "&rDeepslate Emerald Ore / &cNot validated" with lore "&e+%{pts_lvl_8}% ╣"
					if {bingo_case_8.%player%} is true:
						make gui slot 22 with deepslate emerald ore named "&rDeepslate Emerald Ore / &aValidated" with lore "&e+%{pts_lvl_8}% ╣"
					if {bingo_case_9.%player%} is false:
						make gui slot 23 with zombie head named "&fZombie Head / &cNot validated" with lore "&e+%{pts_lvl_9}% ╣"
					if {bingo_case_9.%player%} is true:
						make gui slot 23 with zombie head named "&fZombie Head / &aValidated" with lore "&e+%{pts_lvl_9}% ╣"
				open the last gui for the player
			else:
				send "[&c&lTheEvent580 - Bingo&r] Sorry, but you are not in &eBingo&r yet, so you are not allowed to see the &eBingo&r card"
		else:
			create a gui with virtual chest inventory with 3 rows named "&eSpec card":
				make gui slot 3 with dark oak leaves named "&rDark Oak Leaves / &a%{bingo_case_1_completed}% completed" with lore "&e+%{pts_lvl_1}% ╣"
				make gui slot 4 with mushroom stem named "&rMushroom Stem / &a%{bingo_case_2_completed}% completed" with lore "&e+%{pts_lvl_2}% ╣"
				make gui slot 5 with lime bed named "&rLime Bed / &a%{bingo_case_3_completed}% completed" with lore "&e+%{pts_lvl_3}% ╣"
				make gui slot 12 with raw copper block named "&rBlock of Raw Copper / &a%{bingo_case_4_completed}% completed" with lore "&e+%{pts_lvl_4}% ╣"
				make gui slot 13 with calibrated sculk sensor named "&rCalibrated Sculk Sensor / &a%{bingo_case_5_completed}% completed" with lore "&e+%{pts_lvl_5}% ╣"
				make gui slot 14 with waxed cut copper stairs named "&rWaxed Cut Copper Stairs / &a%{bingo_case_6_completed}% completed" with lore "&e+%{pts_lvl_6}% ╣"
				make gui slot 21 with blue candle named "&rBlue Candle / &a%{bingo_case_7_completed}% completed" with lore "&e+%{pts_lvl_7}% ╣"
				make gui slot 22 with deepslate emerald ore named "&rDeepslate Emerald Ore / &a%{bingo_case_8_completed}% completed" with lore "&e+%{pts_lvl_8}% ╣"
				make gui slot 23 with zombie head named "&fZombie Head / &a%{bingo_case_9_completed}% completed" with lore "&e+%{pts_lvl_9}% ╣"
			open the last gui for the player

command /ftb:
	permission: *
	permission message: &cThis command does not exist
	description: lance find the button
	trigger:
		make server execute command "execute in minecraft:find_the_button run tp @a 0 148 0 0 0"
		set {jeu_condi} to 4
		set {finished_players} to 0
		loop all players:
			make console execute command "hide %loop-player%"
			set {gamemode.%loop-player%} to 2
			set {ftb_fin.%loop-player%} to 0
			set {finished.%loop-player's uuid%} to false
			set {ftb_1.%loop-player%} to false
			set {ftb_2.%loop-player%} to false
			set {ftb_3.%loop-player%} to false
			set {ftb_4.%loop-player%} to false
			set {ftb_5.%loop-player%} to false
			set {ftb_6.%loop-player%} to false
			set {ftb_7.%loop-player%} to false
			set {ftb_8.%loop-player%} to false
			set {ftb_9.%loop-player%} to false
			set {ftb_10.%loop-player%} to false
			set {ftb_11.%loop-player%} to false
		loop all players:
			if loop-player has permission "group.spectators":
				set {finished.%loop-player's uuid%} to true
				force loop-player to fly
				allow fly for loop-player
				set slot 0 of loop-player to compass named "&rTeleport to player"
				set slot 1 of loop-player to feather named "&rChange player's fly speed"
				set slot 8 of loop-player to paper named "&aTotal of button pressed card"
		set {total_buttons_pressed} to 0
		set {ftb_oak_completed} to 0
		set {ftb_spruce_completed} to 0
		set {ftb_acacia_completed} to 0
		set {ftb_mangrove_completed} to 0
		set {ftb_crimson_completed} to 0
		set {ftb_polished_blackstone_completed} to 0
		set {ftb_dark_oak_completed} to 0
		set {ftb_stone_completed} to 0
		set {ftb_warped_completed} to 0
		set {ftb_jungle_completed} to 0
		set {ftb_birch_completed} to 0
		set {ftb_1} to false
		set {ftb_2} to false
		set {ftb_3} to false
		set {ftb_4} to false
		set {ftb_5} to false
		set {ftb_6} to false
		set {ftb_7} to false
		set {ftb_8} to false
		set {ftb_9} to false
		set {ftb_10} to false
		set {ftb_11} to false
		set {ftb_fin} to false
		set {pts_lvl_1} to 10*{checking_finished_players}
		set {pts_lvl_1} to {pts_lvl_1}*{multiplier}
		set {pts_lvl_2} to 15*{checking_finished_players}
		set {pts_lvl_2} to {pts_lvl_2}*{multiplier}
		set {pts_lvl_3} to 20*{checking_finished_players}
		set {pts_lvl_3} to {pts_lvl_3}*{multiplier}
		set {pts_lvl_4} to 25*{checking_finished_players}
		set {pts_lvl_4} to {pts_lvl_4}*{multiplier}
		set {pts_lvl_5} to 30*{checking_finished_players}
		set {pts_lvl_5} to {pts_lvl_5}*{multiplier}
		set {pts_lvl_6} to 35*{checking_finished_players}
		set {pts_lvl_6} to {pts_lvl_6}*{multiplier}
		set {pts_lvl_7} to 40*{checking_finished_players}
		set {pts_lvl_7} to {pts_lvl_7}*{multiplier}
		set {pts_lvl_8} to 45*{checking_finished_players}
		set {pts_lvl_8} to {pts_lvl_8}*{multiplier}
		set {pts_lvl_9} to 50*{checking_finished_players}
		set {pts_lvl_9} to {pts_lvl_9}*{multiplier}
		set {pts_lvl_10} to 55*{checking_finished_players}
		set {pts_lvl_10} to {pts_lvl_10}*{multiplier}
		set {pts_lvl_11} to 60*{checking_finished_players}
		set {pts_lvl_11} to {pts_lvl_11}*{multiplier}
		make server execute command "//world find_the_button"
		make server execute command "//pos1 -4,152,4"
		make server execute command "//pos2 4,147,-4"
		make server execute command "//set glass"
		make server execute command "//pos1 -3,151,3"
		make server execute command "//pos2 3,148,-3"
		make server execute command "//set air"
		wait 1 second
		make server execute command "gamemode adventure @a"
		make server execute command "execute in minecraft:find_the_button run tp @a 0 148 0 0 0"

command /totalbuttons:
	permission: "group.spectators"
	trigger:
		create a gui with virtual chest inventory with 4 rows named "&aAll buttons":
			make gui slot 3 with oak button named "&rOak Button / &a%{ftb_oak_completed}% Pressed" with lore "&e+%{pts_lvl_1}% ╣"
			make gui slot 4 with spruce button named "&rSpruce Button / &a%{ftb_spruce_completed}% Pressed" with lore "&e+%{pts_lvl_2}% ╣"
			make gui slot 5 with acacia button named "&rAccacia Button / &a%{ftb_acacia_completed}% Pressed" with lore "&e+%{pts_lvl_3}% ╣"
			make gui slot 12 with mangrove button named "&rMangrove Button / &a%{ftb_mangrove_completed}% Pressed" with lore "&e+%{pts_lvl_4}% ╣"
			make gui slot 13 with crimson button named "&rCrimson Button / &a%{ftb_crimson_completed}% Pressed" with lore "&e+%{pts_lvl_5}% ╣"
			make gui slot 14 with polished blackstone button named "&rPolished Blackstone Button / &a%{ftb_polished_blackstone_completed}% Pressed" with lore "&e+%{pts_lvl_6}% ╣"
			make gui slot 21 with dark oak button named "&rDark Oak Button / &a%{ftb_dark_oak_completed}% Pressed" with lore "&e+%{pts_lvl_7}% ╣"
			make gui slot 22 with stone button named "&rStone Button / &a%{ftb_stone_completed}% Pressed" with lore "&e+%{pts_lvl_8}% ╣"
			make gui slot 23 with warped button named "&rWarped Button / &a%{ftb_warped_completed}% Pressed" with lore "&e+%{pts_lvl_9}% ╣"
			make gui slot 30 with jungle button named "&rJungle Button / &a%{ftb_jungle_completed}% Pressed" with lore "&e+%{pts_lvl_10}% ╣"
			make gui slot 31 with birch button named "&rBirch Button / &a%{ftb_birch_completed}% Pressed" with lore "&e+%{pts_lvl_11}% ╣"
		open the last gui for the player

command /courses:
	description: lance race
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to 5
		set {finished_players} to 0
		loop all players:
			set {race_checkpoint.%loop-player%} to 0
			set {race_lap.%loop-player%} to 1
			if loop-player has permission "group.spectators":
				set {finished.%loop-player's uuid%} to true
			else:
				set {finished.%loop-player's uuid%} to false
				set slot 40 of loop-player to carrot on a stick named "&rYou're on Lap 1"
				set {race_total_time.%loop-player%} to 0
				set {race_lap_time.%loop-player%} to 0
			set {race_boat.%loop-player%} to false
		set {race_timer_status} to false
		set {race_lap_1_finished} to false
		set {race_lap_2_finished} to false
		set {race_lap_3_finished} to false
		set {race_lap} to 1
		set {pts_lvl_1} to 40*{checking_finished_players}
		set {pts_lvl_1} to {pts_lvl_1}*{multiplier}
		set {remove_pts_lvl_1} to 40*{multiplier}
		set {pts_lvl_2} to 60*{checking_finished_players}
		set {pts_lvl_2} to {pts_lvl_2}*{multiplier}
		set {remove_pts_lvl_2} to 60*{multiplier}
		set {pts_lvl_3} to 80*{checking_finished_players}
		set {pts_lvl_3} to {pts_lvl_3}*{multiplier}
		set {remove_pts_lvl_3} to 80*{multiplier}
		make server execute command "execute in minecraft:races_lap_3 run tp @a 0.5 131 3.5 180 0"
		wait 2 seconds
		make server execute command "gamemode adventure @a"

command /sg [<text>]:
	description: lance le sg
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to 6
		loop all players:
			if player doesn't have permission "group.spectators":
				add 1 to {finished_players}
				set {alive.%loop-player's uuid%} to true
			else:
				set {alive.%loop-player's uuid%} to false

		set {1st_blood} to true
		set {pts_lvl_1} to 50*{multiplier}
		set {pts_lvl_2} to 20*{multiplier}
		set {pts_lvl_3} to 10*{multiplier}
		set {pts_lvl_4} to 15*{multiplier}
		set {pts_lvl_5} to 75*{multiplier}
		loop all players:
			make server execute command "effect give %loop-player% invisibility 210 1 true"
		set {game} to "SG3"
		sgMapCheck()

command /laby:
	description: launch laby
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to 7
		set {finished_players} to 0
		make server execute command "execute in minecraft:labyrinthe run tp @a 0.0 129 1.0 -90 0"
		wait 2 seconds
		loop all players:
			set loop-player's gamemode to adventure
			if loop-player has permission "group.spectators":
				set loop-player's gamemode to spectator
				set {finished.%loop-player's uuid%} to true
				set {laby_level.%loop-player%} to "None"
			else:
				set {finished.%loop-player's uuid%} to false
				set {gamemode.%loop-player%} to 2
				set {laby_level.%loop-player%} to "Start"
				make server execute command "effect give %loop-player% invisibility 660 1 true"
				make server execute command "effect give %loop-player% night_vision 660 255 true"
		set {pts_lvl_1} to 30*{checking_finished_players}
		set {pts_lvl_1} to {pts_lvl_1}*{multiplier}
		set {remove_pts_lvl_1} to 30*{multiplier}
		set {pts_lvl_2} to 50*{checking_finished_players}
		set {pts_lvl_2} to {pts_lvl_2}*{multiplier}
		set {remove_pts_lvl_2} to 50*{multiplier}
		set {pts_lvl_3} to 80*{checking_finished_players}
		set {pts_lvl_3} to {pts_lvl_3}*{multiplier}
		set {remove_pts_lvl_3} to 80*{multiplier}

command /bowpvp:
	description: lauch bow pvp
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to 8
		set {finished_players} to {checking_finished_players}
		loop all players:
			set {invicibility.%loop-player's uuid%} to false
			teleport loop-player to location(0.5, 169, 0.5, "Bow_PVP", -180, 90)
			set the maximum health of loop-player to 5
			set {gamemode.%loop-player%} to 2
			if loop-player has permission "group.spectators":
				set {alive.%loop-player's uuid%} to false
				if {hide.%loop-player's uuid%} = false:
					make console execute command "hide %loop-player%"
			else:
				set {alive.%loop-player's uuid%} to true
		wait 2 seconds
		make server execute command "gamemode adventure @a"
		set {pts_lvl_1} to 40*{multiplier}#kill bow & more than 1 heart
		set {pts_lvl_2} to 30*{multiplier}#kill sword & more than 1 heart
		set {pts_lvl_3} to 60*{multiplier}#kill bow & elemination
		set {pts_lvl_4} to 45*{multiplier}#kill sword & elemination
		set {pts_lvl_5} to 5*{multiplier}#pitty points more than 1 heart
		set {pts_lvl_6} to 10*{multiplier}#pitty points elemination

command /bm:
	description: starts Build Masters
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to 9
		set {finished_players} to 0
		set {damage} to 2
		make server execute command "execute in build_masters run tp @a 0.5 128 0.5 -90 0"
		wait 5 ticks
		set {_pos.player} to 0
		reveal hidden players of all players
		loop all players:
			set loop-player's gamemode to adventure
			if loop-player has permission "group.spectators":
				make console execute command "hide %loop-player%"
				allow fly for loop-player
				force loop-player to fly
				set {build.location.%loop-player%} to -1
				set {build.%loop-player%} to -1
				set {builds.%loop-player%} to "Spec"
				set {finished.%loop-player's uuid%} to true
			else:
				set {build.%loop-player%} to 1
				set {builds.%loop-player%} to 0
				set {finished.%loop-player's uuid%} to false
				set {build.location.%loop-player%} to {_pos.player}
				send "[&c&lTheEvent580 - Build Masters&r] Player %loop-player% has been set to plot %{_pos.player}%" to console
				add 1 to {_pos.player}
		set {builds_total} to 0
		set {pts_lvl_1} to 5*{checking_finished_players}#build 1
		set {pts_lvl_1} to {pts_lvl_1}*{multiplier}#build 1
		set {pts_lvl_2} to 15*{checking_finished_players}#build 2
		set {pts_lvl_2} to {pts_lvl_2}*{multiplier}#build 2
		set {pts_lvl_3} to 25*{checking_finished_players}#build 3
		set {pts_lvl_3} to {pts_lvl_3}*{multiplier}#build 3
		set {pts_lvl_4} to 40*{checking_finished_players}#build 4
		set {pts_lvl_4} to {pts_lvl_4}*{multiplier}#build 4
		set {pts_lvl_5} to 60*{checking_finished_players}#build 5
		set {pts_lvl_5} to {pts_lvl_5}*{multiplier}#build 5
		set {pts_lvl_6} to 70*{checking_finished_players}#build 6
		set {pts_lvl_6} to {pts_lvl_6}*{multiplier}#build 6
		set {pts_lvl_7} to 80*{checking_finished_players}#build 7
		set {pts_lvl_7} to {pts_lvl_7}*{multiplier}#build 7
		set {pts_lvl_8} to 95*{checking_finished_players}#build 8
		set {pts_lvl_8} to {pts_lvl_8}*{multiplier}#build 8
		set {pts_lvl_9} to 120*{checking_finished_players}#build 9
		set {pts_lvl_9} to {pts_lvl_9}*{multiplier}#build 9
		set {pts_lvl_10} to 150*{checking_finished_players}#build 10
		set {pts_lvl_10} to {pts_lvl_10}*{multiplier}#build 10
		make server execute command "execute in minecraft:build_masters run setblock 1 129 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 131 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 133 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 135 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 137 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 139 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 141 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 143 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 145 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 147 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 149 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 151 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 153 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 155 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 157 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 159 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 161 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 163 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 165 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 167 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 169 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 171 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 173 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 175 10030 white_concrete"
		make server execute command "execute in minecraft:build_masters run setblock 1 177 10030 white_concrete"


command /points <offline player> [<int>]:
	description: sets points to whatever i want
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-2 is set:
			add arg-2 to {points.%arg-1's uuid%}

command /tele:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to 8
		respawnBowPVP(player)

command /damage <int>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {damage} to arg-1

command /health <int> <offline player>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set the maximum health of player to arg-1
		set {health.%player%} to arg-2
		heal player

command /jeu <int>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {jeu_condi} to arg-1

command /gm <int>:
	permission: group.spectators
	permission message: &cThis command does not exist
	trigger:
		set {gamemode.%player%} to arg-1
		if arg-1 is 1:
			set player's gamemode to creative
		if arg-1 is 2:
			set player's gamemode to adventure
		if arg-1 is 3:
			set player's gamemode to spectator
		if arg-1 is 0:
			set player's gamemode to survival

command /updateclassement:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		updateClassement()

command /updateparkour:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		updateParkour()

command /reloadscoreboard:
	permission:  *
	permission message: &cThis command does not exist
	trigger:
		reloadScoreboard()

command /readycheck:
	description: do a ready check
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {check_players} to 0
		set {replied} to 0
		make player execute command "mute"
		wait 3 seconds
		loop all players:
			set {ready_check.%loop-player%} to false
			set {ready.%loop-player%} to false
			if loop-player has permission "group.spectators":
				send "[&c&lTheEvent580 - Admin&r] Ready check started by %executor%, ends in 30 seconds" to loop-player
				set {ready.%loop-player%} to true
			else:
				add 1 to {check_players}
				send "%nl%--------------------------------%nl%%nl%%nl%" to loop-player
				send "Are you ready to start playing ?%nl%" to loop-player
				send "<run command:/ready>&a&lI am ready to play<reset>&r or <run command:/notready>&c&lI am not ready to play<reset>&r" to loop-player
				send "%nl%%nl%%nl%--------------------------------%nl%" to loop-player
		set {timer-s} to 31
		while {replied} != {online_players}:
			wait 1 tick
			remove 1 from {timer-s}
			if {timer-s} > 21:
				send action bar "&e&lTime left : &a&l%{timer-s}%&e&ls" to all players
			else if {timer-s} > 11:
				send action bar "&e&lTime left : &6&l%{timer-s}%&e&ls" to all players
			else if {timer-s} > 0:
				send action bar "&e&lTime left : &c&l%{timer-s}%&e&ls" to all players
			if {timer-s} < 1:
				exit loop
			wait 19 ticks
		
		loop all players:
			loop 500 times:
				send "" to loop-player
			if {ready.%loop-player%} is true:
				if loop-player doesn't have permission "group.spectators":
					remove 1 from {check_players}
		if {check_players} is 0:
			send "[&c&lTheEvent580 - Admin&r] Everyone is ready, start whenever you want !" to executor
		else:
			loop all players:
				if {ready_check.%loop-player%} is false:
					set {ready_check.%loop-player%} to true
				if loop-player has permission "group.spectators":
					create a gui with virtual chest inventory with 3 rows named "Not ready players":
						wait 1 tick
						set {pos} to 0
						loop all players:
							set {head} to "%loop-player-2%" parsed as an offline player
							if {ready.%loop-player-2%} is false:
								make gui slot {pos} with skull of {head} named "&r&c&l%loop-player-2%&f isn't ready"
								add 1 to {pos}
					open the last gui for the loop-player
			send "[&c&lTheEvent580 - Admin&r] %{check_players}% players are not ready, ask them why they aren't"
		make player execute command "mute"

command /ready:
	description: ready you automatically
	trigger:
		if {ready_check.%player%} is false:
			set {ready_check.%player%} to true
			set {ready.%player%} to true
			add 1 to {ready_player}
			add 1 to {replied}
			broadcast "[&c&lTheEvent580&r] &a&l%player%&r is ready to start."

command /notready:
	description: unready you automatically
	trigger:
		if {ready_check.%player%} is false:
			set {ready_check.%player%} to true
			set {ready.%player%} to false
			add 1 to {replied}
			broadcast "[&c&lTheEvent580&r] &c&l%player%&r isn't ready to start."

command /serverversion:
	description: give the server version
	permission: *
	permission message: &cThis command does not exist
	trigger:
		send "MC server version : Paper 1.20.1 (Build 193)"

command /qmskin:
	description: send the Question Mark skin to the executor
	permission: *
	permission message: &cThis command does not exist
	trigger:
		send "<link:https://s.namemc.com/i/fc14461a38710880.png>The skin<reset>"

command /fake <text> [<text>]:
	permission: *
	permission message: &cThis command does not exist
	description: "Simulate" the start of the game
	trigger:
		if arg-1 is "dropper":
			set {dropper_lvl_1} to 0
			set {dropper_lvl_2} to 0
			set {dropper_lvl_3} to 0
			set {dropper_lvl_4} to 0
			set {dropper_fin} to 0
			set {pts_lvl_1} to 5*{online_players}
			set {pts_lvl_1} to {pts_lvl_1}*{multiplier}
			set {remove_pts_lvl_1} to 5*{multiplier}
			set {pts_lvl_2} to 10*{online_players}
			set {pts_lvl_2} to {pts_lvl_2}*{multiplier}
			set {remove_pts_lvl_2} to 10*{multiplier}
			set {pts_lvl_3} to 15*{online_players}
			set {pts_lvl_3} to {pts_lvl_3}*{multiplier}
			set {remove_pts_lvl_3} to 15*{multiplier}
			set {pts_lvl_4} to 20*{online_players}
			set {pts_lvl_4} to {pts_lvl_4}*{multiplier}
			set {remove_pts_lvl_4} to 20*{multiplier}
			set {pts_fin} to 40*{online_players}
			set {pts_fin} to {pts_fin}*{multiplier}
			set {remove_pts_fin} to 40*{multiplier}
			loop all players:
				set {gamemode.%loop-player%} to 2
				set {dropper_level.%loop-player%} to 1
		if arg-1 is "courses":
			if arg-2 is "boat":
				set {courses} to "boat"

command /world:
	permission: *
	permission message: &cThis command does not exist
	description: send player's world
	trigger:
		send player's world to player

command /ping [<player>]:
	description: send arg-1's ping (if precised) to executor
	trigger:
		if arg-1 is set:
			if arg-1's ping < 50:
				send "[&c&lTheEvent580&r] %arg-1%'s ping is &a&l%arg-1's ping% &rms" to executor
			else if arg-1's ping < 100:
				send "[&c&lTheEvent580&r] %arg-1%'s ping is &e&l%arg-1's ping% &rms" to executor
			else if arg-1's ping < 150:
				send "[&c&lTheEvent580&r] %arg-1%'s ping is &6&l%arg-1's ping% &rms" to executor
			else if arg-1's ping < 200:
				send "[&c&lTheEvent580&r] %arg-1%'s ping is &c&l%arg-1's ping% &rms" to executor
			else if arg-1's ping > 199:
				send "[&c&lTheEvent580&r] %arg-1%'s ping is &4&l%arg-1's ping% &rms" to executor
		else:
			if executor's ping < 50:
				send "[&c&lTheEvent580&r] Your ping is &a&l%executor's ping% &rms" to executor
			else if executor's ping < 100:
				send "[&c&lTheEvent580&r] Your ping is &e&l%executor's ping% &rms" to executor
			else if executor's ping < 150:
				send "[&c&lTheEvent580&r] Your ping is &6&l%executor's ping% &rms" to executor
			else if executor's ping < 200:
				send "[&c&lTheEvent580&r] Your ping is &c&l%executor's ping% &rms" to executor
			else if executor's ping > 199:
				send "[&c&lTheEvent580&r] Your ping is &4&l%executor's ping% &rms" to executor

command /msg <player> <text>:
	aliases: tell
	trigger:
		if arg-1 is player:
			send "[&c&lTheEvent580 - Private Messages&r] Talking to himself is disabled on this server."
		else:
			send "[&c&lTheEvent580 - Private Messages&r] From %player% : %arg-2%" to arg-1
			send "[&c&lTheEvent580 - Private Messages&r] To %arg-1% : %arg-2%" to player
			#loop all players:
			#	if loop-player has permission "theevent580.messages.spy":
			#		if loop-player is not arg-1 or executor:
			#			send "[&c&lTheEvent580 - Private Messages - Spy Mode&r] %player% said ""%arg-2%"" to %arg-1%"

command /staff <text> [<player>]:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-1 is "remove":
			remove arg-2 from {staff::*}
		if arg-1 is "add":
			add arg-2 to {staff::*}
		if arg-1 is "see":
			send "[&c&lTheEvent580 - Admin&r] Online staff :"
			loop {staff::*}:
				send "[&c&lTheEvent580 - Admin&r] %loop-value%"

command /tpspec:
	trigger:
		set {_user} to player
		if {timer} = 5 or 6:
			if {finished.%player's uuid%} is true:
				create a gui with virtual chest inventory with 6 rows named "&r露 &8Spectator menu":
					wait 1 tick
					make gui slot 0 with red stained glass pane named "&rラ &cRed"
					make gui slot 9 with orange stained glass pane named "&rャ &6Orange"
					make gui slot 18 with yellow stained glass pane named "&rギ &eYellow"
					make gui slot 27 with lime stained glass pane named "&r画 &aLime"
					make gui slot 36 with light blue stained glass pane named "&r動 &bLight Blue"
					make gui slot 45 with blue stained glass pane named "&r像 &1Blue"
					set {_slot.red} to 1
					set {_slot.orange} to 10
					set {_slot.yellow} to 19
					set {_slot.lime} to 28
					set {_slot.light_blue} to 37
					set {_slot.blue} to 46
					loop all players:
						if {finished.%loop-player's uuid%} is false:
							set {_head} to "%loop-value%" parsed as an offline player
							if loop-player has permission "group.rouge":
								set {_slot} to {_slot.red}
								add 1 to {_slot.red}
							if loop-player has permission "group.orange":
								set {_slot} to {_slot.orange}
								add 1 to {_slot.orange}
							if loop-player has permission "group.jaune":
								set {_slot} to {_slot.yellow}
								add 1 to {_slot.yellow}
							if loop-player has permission "group.vert":
								set {_slot} to {_slot.lime}
								add 1 to {_slot.lime}
							if loop-player has permission "group.bleu_clair":
								set {_slot} to {_slot.light_blue}
								add 1 to {_slot.light_blue}
							if loop-player has permission "group.bleu":
								set {_slot} to {_slot.blue}
								add 1 to {_slot.blue}
							make gui slot {_slot} with skull of {_head} named "&fTeleport to %{color.%loop-player's uuid%}%%{_head}%":
								teleport {_user} to {_head}
								close {_user}'s inventory
					set {_slot} to 8
					loop 6 times:
						make gui slot {_slot} with skull of "MHF_ArrowRight" parsed as an offline player named "&r&fNext page":
							teleport {_user} to {_head}
							close {_user}'s inventory
						add 9 to {_slot}
				open the last gui for the player
		else:
			if player has permission "group.spectators":
				create a gui with virtual chest inventory with 6 rows named "&r露 &8Spectator menu":
					wait 1 tick
					make gui slot 0 with red stained glass pane named "&rラ &cRed"
					make gui slot 9 with orange stained glass pane named "&rャ &6Orange"
					make gui slot 18 with yellow stained glass pane named "&rギ &eYellow"
					make gui slot 27 with lime stained glass pane named "&r画 &aLime"
					make gui slot 36 with light blue stained glass pane named "&r動 &bLight Blue"
					make gui slot 45 with blue stained glass pane named "&r像 &1Blue"
					set {_slot.red} to 1
					set {_slot.orange} to 10
					set {_slot.yellow} to 19
					set {_slot.lime} to 28
					set {_slot.light_blue} to 37
					set {_slot.blue} to 46
					loop all players:
						if {finished.%loop-player's uuid%} is false:
							set {_head} to "%loop-value%" parsed as an offline player
							if loop-player has permission "group.rouge":
								set {_slot} to {_slot.red}
								add 1 to {_slot.red}
							if loop-player has permission "group.orange":
								set {_slot} to {_slot.orange}
								add 1 to {_slot.orange}
							if loop-player has permission "group.jaune":
								set {_slot} to {_slot.yellow}
								add 1 to {_slot.yellow}
							if loop-player has permission "group.vert":
								set {_slot} to {_slot.lime}
								add 1 to {_slot.lime}
							if loop-player has permission "group.bleu_clair":
								set {_slot} to {_slot.light_blue}
								add 1 to {_slot.light_blue}
							if loop-player has permission "group.bleu":
								set {_slot} to {_slot.blue}
								add 1 to {_slot.blue}
							make gui slot {_slot} with skull of {_head} named "&fTeleport to %{color.%loop-player's uuid%}%%{_head}%":
								teleport {_user} to {_head}
								close {_user}'s inventory
					set {_slot} to 8
					loop 6 times:
						make gui slot {_slot} with skull of "MHF_ArrowRight" parsed as an offline player named "&r&fNext page":
							teleport {_user} to {_head}
							close {_user}'s inventory
							make player execute command "tpspec2"
						add 9 to {_slot}
				open the last gui for the player
		#set {_user} to player
		#if {finished.%player's uuid%} is true:
		#	create a gui with virtual chest inventory with 6 rows named "Spectator menu":
		#		wait 1 tick
		#		set {_slot} to 0
		#		loop all players:
		#			if {finished.%loop-player's uuid%} is false:
		#				set {_head} to "%loop-value%" parsed as an offline player
		#				make gui slot {_slot} with skull of {_head} named "&fTeleport to %{_head}%":
		#					teleport {_user} to {_head}
		#					close {_user}'s inventory
		#				add 1 to {_slot}
		#	open the last gui for the player
		#else:
		#	if {finished.%player's uuid%} = true:
		#		loop all players:
		#			if loop-player doesn't have permission "group.spectators":
		#				add loop-player to {_players::*}
		#		create a gui with virtual chest inventory with 6 rows named "Spectator menu":
		#			wait 1 tick
		#			set {_slot} to 0
		#			loop {_players::*}:
		#				set {_head} to "%loop-value-2%" parsed as an offline player
		#				make gui slot {_slot} with skull of {_head} named "&fTeleport to %{_head}%":
		#					teleport {_user} to {_head}
		#					close {_user}'s inventory
		#				add 1 to {_slot}
		#		open the last gui for the player
command /tpspec2:
	trigger:
		set {_user} to player
		if {timer} = 5 or 6:
			if {finished.%player's uuid%} is true:
				create a gui with virtual chest inventory with 2 rows named "&r露 &8Spectator menu":
					wait 1 tick
					make gui slot 0 with purple stained glass pane named "&rの &5Purple"
					make gui slot 9 with pink stained glass pane named "&r目 &dPink"
					set {_slot.purple} to 1
					set {_slot.pink} to 10
					loop all players:
						if {finished.%loop-player's uuid%} is false:
							set {_head} to "%loop-value%" parsed as an offline player
							if loop-player has permission "group.violet":
								set {_slot} to {_slot.purple}
								add 1 to {_slot.purple}
							if loop-player has permission "group.pink":
								set {_slot} to {_slot.pink}
								add 1 to {_slot.pink}
							make gui slot {_slot} with skull of {_head} named "&fTeleport to %{color.%loop-player's uuid%}%%{_head}%":
								teleport {_user} to {_head}
								close {_user}'s inventory
					set {_slot} to 8
					loop 2 times:
						make gui slot {_slot} with skull of "MHF_ArrowLeft" parsed as an offline player named "&r&fLast page":
							teleport {_user} to {_head}
							close {_user}'s inventory
							make player execute command "tpspec"
						add 9 to {_slot}
			open the last gui for the player
		else:
			if player has permission "group.spectators":
				create a gui with virtual chest inventory with 2 rows named "&r露 &8Spectator menu":
					wait 1 tick
					make gui slot 0 with purple stained glass pane named "&rの &5Purple"
					make gui slot 9 with pink stained glass pane named "&r目 &dPink"
					set {_slot.purple} to 1
					set {_slot.pink} to 10
					loop all players:
						if {finished.%loop-player's uuid%} is false:
							set {_head} to "%loop-value%" parsed as an offline player
							if loop-player has permission "group.violet":
								set {_slot} to {_slot.purple}
								add 1 to {_slot.purple}
							if loop-player has permission "group.pink":
								set {_slot} to {_slot.pink}
								add 1 to {_slot.pink}
							make gui slot {_slot} with skull of {_head} named "&fTeleport to %{color.%loop-player's uuid%}%%{_head}%":
								teleport {_user} to {_head}
								close {_user}'s inventory
					set {_slot} to 8
					loop 2 times:
						make gui slot {_slot} with skull of "MHF_ArrowLeft" parsed as an offline player named "&r&fLast page":
							teleport {_user} to {_head}
							close {_user}'s inventory
							make player execute command "tpspec"
						add 9 to {_slot}
			open the last gui for the player

command /tests <int>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		add arg-1 to {online_players}

command /emotes [<text>]:
	description: opens a gui with all the emotes that, when clicked, will send that emote in chat
	trigger:
		if arg-1 is not set:
			set {_skull} to a player head
			set {_skullnbt} to nbt compound of {_skull}
			add nbt compound of "{display:{Name:""{\""text\"":\""&r&fSkull\""}""},SkullOwner:{Id:""d39e3587-abea-4770-bf02-2f16aa1d04e3"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWRjZjJjMTk4ZjYxZGY1YTZkMGJhOTdkYmY5MGMzMzc5OTU0MDVjMTczOTZjMDE2Yzg1ZjZmM2ZlYTUyYzkwNiJ9fX0=""}]}}}" to {_skullnbt}
			set {_heartmenu} to a player head
			set {_heartmenunbt} to nbt compound of {_heartmenu}
			add nbt compound of "{display:{Name:""{\""text\"":\""&r&cRed Heart\""}""},SkullOwner:{Id:""9e486964-a0ef-46c2-a8d9-61fa37680a53"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWI3NmI0ZWU5ODg1NzIyOTdjYmQ4NzQ2ODNiZWU5NmFlM2M1NWNlOTRjMDA0ZTUxYWRjODJjZWUxNmNkMGIwYyJ9fX0=""}]}}}" to {_heartmenunbt}
			open chest inventory with 3 rows named "Emotes menu" to player
			set slot 0 of current inventory of player to {_skull}
			set slot 1 of current inventory of player to {_heartmenu}
			set slot 26 of current inventory of player to barrier named "&r&cClose emote menu"
			set {menu.%player%} to "main"
		else:
			if arg-1 is "heart":
				set {_heart1} to a player head
				set {_heart1nbt} to nbt compound of {_heart1}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&4Dark Red Heart\""}""},SkullOwner:{Id:""9e486964-a0ef-46c2-a8d9-61fa37680a53"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWI3NmI0ZWU5ODg1NzIyOTdjYmQ4NzQ2ODNiZWU5NmFlM2M1NWNlOTRjMDA0ZTUxYWRjODJjZWUxNmNkMGIwYyJ9fX0=""}]}}}" to {_heart1nbt}
				set {_heart2} to a player head
				set {_heart2nbt} to nbt compound of {_heart2}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&cRed Heart\""}""},SkullOwner:{Id:""9e486964-a0ef-46c2-a8d9-61fa37680a53"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWI3NmI0ZWU5ODg1NzIyOTdjYmQ4NzQ2ODNiZWU5NmFlM2M1NWNlOTRjMDA0ZTUxYWRjODJjZWUxNmNkMGIwYyJ9fX0=""}]}}}" to {_heart2nbt}
				set {_heart3} to a player head
				set {_heart3nbt} to nbt compound of {_heart3}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&6Orange Heart\""}""},SkullOwner:{Id:""ef508f92-3bcd-42fc-a28d-9c0e70b73d9e"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZhMjdlZGRmNjBhMDQ4Mzc3OGM4ZTNjNjY1MGY1Mjg4MzQxZjM4YmI5ZTQzMTc5YzY2YmIxZTdiMWQ5ZGQ2YiJ9fX0=""}]}}}" to {_heart3nbt}
				set {_heart4} to a player head
				set {_heart4nbt} to nbt compound of {_heart4}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&eYellow Heart\""}""},SkullOwner:{Id:""f246cc0b-1017-47c0-a703-99e024d74968"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWVlOWJhYzBhZDRhYmY1OTU1NmE5ODY0ODAwNGU4Mzc0MWQ3NmU0MDk3YjJkZjAzNzIwN2YxYTY5ZDRhZmNmZCJ9fX0=""}]}}}" to {_heart4nbt}
				set {_heart5} to a player head
				set {_heart5nbt} to nbt compound of {_heart5}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&aLime Heart\""}""},SkullOwner:{Id:""4a408bbe-c99c-47ac-bf04-06923e11122a"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjQ0MWJhMzA5MTA2MWM2OTliOGVhNDA4NTAxMTAzNzhlOTU0NTQwNDhkMWY1MTA1NmM2YWVjMzk1MDUxM2VhYiJ9fX0=""}]}}}" to {_heart5nbt}
				set {_heart6} to a player head
				set {_heart6nbt} to nbt compound of {_heart6}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&2Green Heart\""}""},SkullOwner:{Id:""a51f7781-d659-4391-9c2c-d9de29489f3e"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTZiZmI5M2MxM2U1MmQ1M2RhM2RiYjk3YzhkZWUyYjZlMzY4ZDlkN2RjN2RmNjRlMDdiNDNhMmM2NTJjMGU4MSJ9fX0=""}]}}}" to {_heart6nbt}
				set {_heart7} to a player head
				set {_heart7nbt} to nbt compound of {_heart7}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&3Cyan Heart\""}""},SkullOwner:{Id:""21b66c0e-e1c1-4657-a191-08e2379b34bf"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGE0OWQ1NTY5M2JiOWJhODI4OWYxMTU2MDcxYTE0OWYzYjliZTI0ZGJiMzY2NjQyMmUzYzEzNTVhOGM5YWVlMyJ9fX0=""}]}}}" to {_heart7nbt}
				set {_heart8} to a player head
				set {_heart8nbt} to nbt compound of {_heart8}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&bLight Blue Heart\""}""},SkullOwner:{Id:""baaffa39-99ca-411c-b593-016218e60958"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDRmN2ZhMTk2ZDhmOWFhY2ZjMDgxYjgxZTNjYWUxYmU0MWNmZGJlZGQzMDkyOGRjOWJjYzhjNTc5MGYyMmFkOSJ9fX0=""}]}}}" to {_heart8nbt}
				set {_heart9} to a player head
				set {_heart9nbt} to nbt compound of {_heart9}
				add nbt compound of "{display:{Name:""{\""text\"":\""&9Blue Heart\""}""},SkullOwner:{Id:""b72852e8-2474-4596-8cd3-1cf516fcad37"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWZmZmRiNGY3NWUxNjc4ZWNmYWE1ZjQyYTMyZjExZTFjYzA4Nzk0NmY0ODU3NDYzYWU2NjQ3Y2MzZTAwNzllMiJ9fX0=""}]}}}" to {_heart9nbt}
				set {_heart10} to a player head
				set {_heart10nbt} to nbt compound of {_heart10}
				add nbt compound of "{display:{Name:""{\""text\"":\""&1Dark Blue Heart\""}""},SkullOwner:{Id:""b72852e8-2474-4596-8cd3-1cf516fcad37"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWZmZmRiNGY3NWUxNjc4ZWNmYWE1ZjQyYTMyZjExZTFjYzA4Nzk0NmY0ODU3NDYzYWU2NjQ3Y2MzZTAwNzllMiJ9fX0=""}]}}}" to {_heart10nbt}
				set {_heart11} to a player head
				set {_heart11nbt} to nbt compound of {_heart11}
				add nbt compound of "{display:{Name:""{\""text\"":\""&5Purple Heart\""}""},SkullOwner:{Id:""e9347bea-8ccf-461d-a05f-373d5bbaac7d"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTdiYjRkYTkzZGYyZGU5MmJhNjM5YmEzMzQzN2MxNDkxMWMyOWJlMmVhNTdmYmYzMDViODBlZmZhZWNjNGJmYyJ9fX0=""}]}}}" to {_heart11nbt}
				set {_heart12} to a player head
				set {_heart12nbt} to nbt compound of {_heart12}
				add nbt compound of "{display:{Name:""{\""text\"":\""&dPink Heart\""}""},SkullOwner:{Id:""d77126da-0633-44e6-9859-59c9cc117c69"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2E3MDdlNzQxZmYyMjM0MzgwOTE2YzI2NWY2OThkODIyOThlYzNjMWIzMmI1YjA0ZGFjNDA3NmUxODA0MTlkMiJ9fX0=""}]}}}" to {_heart12nbt}
				set {_goback} to a player head
				set {_gobacknbt} to nbt compound of {_goback}
				#add nbt compound of "{display:{Name:""{\""text\"":\""&r&fGo back to the main menu\""}""},SkullOwner:{Id:""1226610a-b7f8-47e5-a15d-126c4ef18635"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg0ZjU5NzEzMWJiZTI1ZGMwNThhZjg4OGNiMjk4MzFmNzk1OTliYzY3Yzk1YzgwMjkyNWNlNGFmYmEzMzJmYyJ9fX0=""}]}}}" to {_gobacknbt}
				add nbt compound of "{display:{Name:""{\""text\"":\""&r&fGo back to the main menu\""}""},SkullOwner:{Id:""2391d533-ab09-434d-9980-adafde4057a3"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmQ2OWUwNmU1ZGFkZmQ4NGU1ZjNkMWMyMTA2M2YyNTUzYjJmYTk0NWVlMWQ0ZDcxNTJmZGM1NDI1YmMxMmE5In19fQ==""}]}}}" to {_gobacknbt}
				open chest inventory with 3 rows named "Emotes menu" to player
				set slot 0 of current inventory of player to {_heart1}
				set slot 1 of current inventory of player to {_heart2}
				set slot 2 of current inventory of player to {_heart3}
				set slot 3 of current inventory of player to {_heart4}
				set slot 4 of current inventory of player to {_heart5}
				set slot 5 of current inventory of player to {_heart6}
				set slot 6 of current inventory of player to {_heart7}
				set slot 7 of current inventory of player to {_heart8}
				set slot 8 of current inventory of player to {_heart9}
				set slot 9 of current inventory of player to {_heart10}
				set slot 10 of current inventory of player to {_heart11}
				set slot 11 of current inventory of player to {_heart12}
				set slot 25 of current inventory of player to {_goback}
				set slot 26 of current inventory of player to barrier named "&r&cClose emote menu"
				set {menu.%player%} to "heart"

command /fly [<player>]:
	permission: group.spectators
	permission message: &cThis command does not exist
	trigger:
		if arg-1 is set:
			if arg-1 can fly:
				disable fly for arg-1
				send "[&c&lTheEvent580 - Admin&r] Fly mode disabled for %arg-1%" to player
				if arg-1 is not player:
					send "[&c&lTheEvent580 - Admin&r] Fly mode disabled by %executor%" to arg-1
			else:
				allow fly for arg-1
				send "[&c&lTheEvent580 - Admin&r] Fly mode enabled for %arg-1%" to player
				if arg-1 is not player:
					send "[&c&lTheEvent580 - Admin&r] Fly mode enabled by %executor%" to arg-1
		else:
			if executor is player:
				if player can fly:
					disable fly for player
					send "[&c&lTheEvent580 - Admin&r] Fly mode disabled" to player
				else:
					allow fly for player
					send "[&c&lTheEvent580 - Admin&r] Fly mode enabled" to player

command /mute [<player>]:
	permission: *
	permission message: &cThis command does not exist
	description: Mutes chat (or player if enter as an arg)
	trigger:
		if arg-1 is not set:
			if {mute.server} is false:
				set {mute.server} to true
				send action bar "[&c&lTheEvent580 - Chat&r] &6⚠&rThe chat has been muted !" to all players
			else if {mute.server} is true:
				send action bar "[&c&lTheEvent580 - Chat&r] &6⚠&rThe chat has been unmuted !" to all players
				set {mute.server} to false
		else:
			if arg-1 doesn't have permission "group.spectators":
				if {mute.%arg-1%} is false:
					set {mute.%arg-1%} to true
					send "[&c&lTheEvent580 - Chat&r] &6⚠&rYou have been muted by %player% !%nl%" to arg-1
					send "[&c&lTheEvent580 - Chat&r] &6⚠&rYou have muted %arg-1% sucessfully !%nl%" to player
				else if {mute.%arg-1%} is true:
					set {mute.%arg-1%} to false
					send "[&c&lTheEvent580 - Chat&r] &6⚠&rYou have been unmuted by %player% !%nl%" to arg-1
					send "[&c&lTheEvent580 - Chat&r] &6⚠&rYou have unmuted %arg-1% sucessfully !%nl%" to player

command /filter <text> <text>:
	description: add a word / sentence to the anti-swear filter
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-1 is "add":
			add arg-2 to {filter::*}
		else if arg-1 is "remove":
			remove arg-2 from {filter::*}

command /filtersee:
	description: send the anti-swear filter to the player
	permission: *
	trigger:
		send "[&c&lTheEvent580 - Admin&r] Here are all of the banned words:"
		loop {filter::*}:
			send "[&c&lTheEvent580 - Admin&r] %loop-value%"

command /testmode <text>:
	description: turns on and off the test mode
	permission: *
	trigger:
		if arg-1 is "on":	
			set {jeu_condi_save} to {jeu_condi}
			set {jeu_condi} to -1
		else if arg-1 is "off":
			set {jeu_condi} to {jeu_condi_save}

command /seeplacement:
	permission: *
	permission message: &cThis command does not exist
	description: allows the executor of the command to see the placement
	trigger:
		clear {show}
		clear {finished::*}
		clear {list_points::*}
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				add {points.%loop-player's uuid%} to {list_points::*}
				set {points_string.%loop-player%} to "%{points.%loop-player's uuid%}%"
		set {list_points::*} to sorted {list_points::*}
		set {list_points::*} to reversed {list_points::*}

		send "[&c&lTheEvent580 - Admin&r] Here are placements of all the players :"
		set {seepts} to 1
		loop {list_points::*}:
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {list_points::%{seepts}%} = {points.%loop-player's uuid%}:
						send "[&c&lTheEvent580 - Admin&r] %{seepts}% : %{color.%loop-player's uuid%}%%loop-player%&r has %{points.%loop-player's uuid%}% ╣"
			add 1 to {seepts}

command /announcements <text>:
	aliases: announcement, announce, bc, broadcast, alert, alerts
	permission: *
	permission message: &cThis command does not exist
	trigger:
		broadcast "[&c&lTheEvent580 - Announcement&r] %arg-1%"

command /on:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload on.sk"

command /commands:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload commands.sk"

command /every:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload every.sk"

command /functions:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload functions.sk"

command /ph:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload placeholders.sk"

command /rldropper:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload dropper.sk"

command /scripts:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload scripts"

command /all:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		make executor execute command "sk reload all"

command /see <player>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if {finished.%loop-player's uuid%} is false:
					reveal loop-player for arg-1
		send "[&c&lTheEvent580 - Admin&r] You can now see the players who haven't finished yet" to arg-1

command /skip:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		create a gui with virtual chest inventory with 3 rows named "Are you sure to skip the game ?":
			make gui slot 12 with lime wool named "&aYes" with lore "&rI am sure to skip the game !":
				close player's inventory
				loop {staff::*}:
					send "[&c&lTheEvent580 - Admin&r] Game is getting skipped by %executor%" to loop-value
				if {jeu} is 6:
					set {timer-m} to 1
					set {timer-s} to 30
					set {timer} to 10
				else:
					set {timer} to 8
					if {jeu} is 3:
						set {timer-m} to 5
						set {timer-s} to 60
					else:			
						set {timer-m} to 1
						set {timer-s} to 60
				set {l6} to {jeu_nom}
				set {jeu_nom} to "&rHub"
				set {finished_players} to 0
				set {courses_boat_timer_status} to false
				set {courses_pied_timer_status} to false
				set {courses_trident_timer_status} to false
				set {damage} to 1
				clear {pos1}
				clear {pos2}
				clear {pos3}
				clear {show}
				clear {finished::*}
				clear {list_points::*}
				set {jeu_condi} to 0
				set {scoreboard.pos} to 0
				loop all players:
					clear loop-player's inventory
					make loop-player execute command "spawn"
					set {gamemode.%loop-player%} to 2
					remove {points_game.%loop-player's uuid%} from {total_points.%loop-player's uuid%}
					set {points_game.%loop-player's uuid%} to 0
					#Parkour
					set {parkour_checkpoint.%loop-player%} to "Start"
					#Dropper
					set {dropper_level.%loop-player%} to 0
					#Find The Button
					set {ftb_fin.%loop-player%} to 0
					set {ftb_1.%loop-player%} to false
					set {ftb_2.%loop-player%} to false
					set {ftb_3.%loop-player%} to false
					set {ftb_4.%loop-player%} to false
					set {ftb_5.%loop-player%} to false
					set {ftb_6.%loop-player%} to false
					set {ftb_7.%loop-player%} to false
					set {ftb_8.%loop-player%} to false
					set {ftb_9.%loop-player%} to false
					set {ftb_10.%loop-player%} to false
					set {ftb_11.%loop-player%} to false
					#Courses
					set {courses_boat_timer_status.%loop-player%} to false
					set {courses_boat_timer.%loop-player%} to 0
					set {courses_boat.%loop-player%} to "Start"
					set {courses_boat_timer.%loop-player%} to 0
					set {courses_boat_timer_status} to false
					set {courses_pied.%loop-player%} to "Start"
					set {courses_pied_timer.%loop-player%} to 0
					set {courses_pied_timer_section.%loop-player%} to 0
					set {courses_pied_timer_status.%loop-player%} to false
					set {courses_pied_timer_status} to false
					set {courses_trident.%loop-player%} to "Start"
					set {courses_trident_timer.%loop-player%} to 0
					set {courses_trident_timer_section.%loop-player%} to 0
					set {courses_trident_timer_status.%loop-player%} to false
					set {has_trident.%loop-player%} to false
					set {courses_trident_timer_status} to false
					#Laby
					set {laby_level.%loop-player%} to "Start"
					#Bow PVP
					set {health.%loop-player%} to 10
					#Spawn
					set the maximum health of loop-player to 10
					heal loop-player
					reveal hidden players of loop-player
					if loop-player has permission "theevent580.staff":
						send "[&c&lTheEvent580 - Admin&r] Game Skipped" to loop-player
						send "[&c&lTheEvent580 - Admin&r] Event state : &e%{event_state}%&r --> &aIntermission" to loop-player
						set {event_state} to "Intermission"
				broadcast "[&c&lTheEvent580&r] Game has been skipped."
			make gui slot 14 with red wool named "&cNo" with lore "&rI am not sure to skip the game.":
				close player's inventory
		open the last gui for the player

command /speed:
	trigger:
		if player has permission "group.spectators":
			if flying speed of player > 0.8:
				set flying speed of player to 0.1
			else:
				set player's flying speed to player's flying speed * 2
			set {_flyspeed} to the flying speed of player
			set  {_flyspeed} to {_flyspeed} * 10
			send "[&c&lTheEvent580 - Fly&r] Fly speed is now set to %{_flyspeed}%║"
		else:
			set {_isplayer} to false
			loop {finished::*}:
				if loop-value is player:
					if player is not flying:
						make server execute command "fly %player%"
					set {_isplayer} to true
					if flying speed of player > 0.8:
						set flying speed of player to 0.1
					else:
						set player's flying speed to player's flying speed * 2
					set {_flyspeed} to the flying speed of player
					set  {_flyspeed} to {_flyspeed} * 10
					send "[&c&lTheEvent580 - Fly&r] Fly speed is now set to %{_flyspeed}%║"
			if {_isplayer} is false:
				send "[&c&lTheEvent580 - Fly&r] You are not in a spectator state, you cannot change you fly speed"

command /hide [<player>]:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-1 is not set:
			if {hide.%player's uuid%} is true:
				reveal player for all players
				set {hide.%player's uuid%} to false
				send "[&c&lTheEvent580 - Admin&r] You are now visible to other players"
			else if {hide.%player's uuid%} is not set:
				hide player from all players
				set {hide.%player's uuid%} to true
				send "[&c&lTheEvent580 - Admin&r] You are now invisible to other players"
			else:
				hide player from all players
				set {hide.%player's uuid%} to true
				send "[&c&lTheEvent580 - Admin&r] You are now invisible to other players"
		else:
			if {hide.%arg-1's uuid%} is true:
				reveal arg-1 for all players
				set {hide.%arg-1's uuid%} to false
				send "[&c&lTheEvent580 - Admin&r] You are now visible to other players" to arg-1
			else if {hide.%arg-1's uuid%} is not set:
				hide arg-1 from all players
				loop all players:
					if loop-player has permission "group.spectators":
						reveal arg-1 for loop-player
				set {hide.%arg-1's uuid%} to true
				send "[&c&lTheEvent580 - Admin&r] You are now invisible to other players" to arg-1
			else:
				hide arg-1 from all players
				loop all players:
					if loop-player has permission "group.spectators":
						reveal arg-1 for loop-player
				set {hide.%arg-1's uuid%} to true
				send "[&c&lTheEvent580 - Admin&r] You are now invisible to other players" to arg-1

command /multiplier [<int>]:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-1 is not set :
			send "[&c&lTheEvent580 - Admin&r] Current multiplier : %{multiplier}%║"
		else:
			set {multiplier} to arg-1
			send "[&c&lTheEvent580 - Admin&r] New multiplier : %{multiplier}%║"

command /achivement <player> <text> <text>:
	description: Give / Remove an achivement to any player
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-2 is "give":
			if arg-3 is "Secret_Base_1":
				set {Secret_Base_1.%arg-1's uuid%} to true
				set {_time} to now formatted as "HH:mm:ss"
				set {_date} to now formatted as "dd/MM/yyyy"
				send "[&c&lTheEvent580 - Achivement&r] Achivement aquired : You found the secret base in the hub ! (%{_date}% - %{_time}% GMT)" to arg-1
				set {Secret_Base_1.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : You found the secret base in the hub ! (%{_date}% - %{_time}% GMT)"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : You found the secret base in the hub ! (%{_date}% - %{_time}% GMT)" to loop-player
			if arg-3 is "Herobrine":
				set {Herobrine.%arg-1's uuid%} to true
				set {_time} to now formatted as "HH:mm:ss"
				set {_date} to now formatted as "dd/MM/yyyy"
				send "[&c&lTheEvent580 - Achivement&r] Achivement aquired : You discovered Herobrine ! (%{_date}% - %{_time}% GMT)" to arg-1
				set {Herobrine.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : You discovered Herobrine ! (%{_date}% - %{_time}% GMT)"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : You discovered Herobrine ! (%{_date}% - %{_time}% GMT)" to loop-player
			if arg-3 is "HubParkour":
				set {HubParkour.%arg-1's uuid%} to true
				set {_time} to now formatted as "HH:mm:ss"
				set {_date} to now formatted as "dd/MM/yyyy"
				send "[&c&lTheEvent580 - Achivement&r] Achivement aquired : You finished the Hub parkour ! (%{_date}% - %{_time}% GMT)" to arg-1
				set {HubParkour.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : You finished the Hub parkour ! (%{_date}% - %{_time}% GMT)"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : You finished the Hub parkour ! (%{_date}% - %{_time}% GMT)" to loop-player
			if arg-3 is "1SecBM":
				set {1SecBM.%arg-1's uuid%} to true
				set {_time} to now formatted as "HH:mm:ss"
				set {_date} to now formatted as "dd/MM/yyyy"
				send "[&c&lTheEvent580 - Achivement&r] Achivement aquired : Finishing the Build Master 1 second before the end ! (%{_date}% - %{_time}% GMT)" to arg-1
				set {1SecBM.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : Finishing the Build Master 1 second before the end ! (%{_date}% - %{_time}% GMT)"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : Finishing the Build Master 1 second before the end ! (%{_date}% - %{_time}% GMT)" to loop-player
			if arg-3 is "FBSG":
				set {FBSG.%arg-1's uuid%} to true
				set {_time} to now formatted as "HH:mm:ss"
				set {_date} to now formatted as "dd/MM/yyyy"
				send "[&c&lTheEvent580 - Achivement&r] Achivement aquired : Surviving until the Final Battle in Survival Games at least once ! (%{_date}% - %{_time}% GMT)" to arg-1
				set {FBSG.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : Surviving until the Final Battle in Survival Games at least once ! (%{_date}% - %{_time}% GMT)"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% aquired the Achivement : Surviving until the Final Battle in Survival Games at least once ! (%{_date}% - %{_time}% GMT)" to loop-player
		if arg-2 is "remove":
			if arg-3 is "Secret_Base_1":
				set {Secret_Base_1.%arg-1's uuid%} to false
				send "[&c&lTheEvent580 - Achivement&r] Achivement removed : You found the secret base in the hub !" to arg-1
				set {Secret_Base_1.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% does not have the Achivement : You found the secret base in the hub !"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% got their Achivement : You found the secret base in the hub ! removed" to loop-player
			if arg-3 is "Herobrine":
				set {Herobrine.%arg-1's uuid%} to false
				send "[&c&lTheEvent580 - Achivement&r] Achivement removed : You discovered Herobrine !" to arg-1
				set {Herobrine.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% does not have the Achivement : You discovered Herobrine !"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% got their Achivement : You discovered Herobrine ! removed" to loop-player
			if arg-3 is "HubParkour":
				set {HubParkour.%arg-1's uuid%} to false
				send "[&c&lTheEvent580 - Achivement&r] Achivement removed : You finished the Hub parkour !" to arg-1
				set {HubParkour.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% does not have the Achivement : You finished the Hub parkour !"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% got their Achivement : You finished the Hub parkour ! removed" to loop-player
			if arg-3 is "1SecBM":
				set {1SecBM.%arg-1's uuid%} to false
				send "[&c&lTheEvent580 - Achivement&r] Achivement removed : Finishing the Build Master 1 second before the end !" to arg-1
				set {1SecBM.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% does not have the Achivement : Finishing the Build Master 1 second before the end !"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% got their Achivement : Finishing the Build Master 1 second before the end ! removed" to loop-player
			if arg-3 is "FBSG":
				set {FBSG.%arg-1's uuid%} to false
				send "[&c&lTheEvent580 - Achivement&r] Achivement removed : Surviving until the Final Battle in Survival Games at least once !" to arg-1
				set {FBSG.%arg-1's uuid%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %arg-1% does not have the Achivement : Surviving until the Final Battle in Survival Games at least once !"
				loop all players:
					if loop-player has permission "group.spectators":
						send "[&c&lTheEvent580 - Achivement&r] Player %arg-1% got their Achivement : Surviving until the Final Battle in Survival Games at least once ! removed" to loop-player
		if arg-2 is "check":
			if arg-3 is "Secret_Base_1":
				send {Secret_Base_1.%arg-1's uuid%.infos} to player
			if arg-3 is "Herobrine":
				send {Herobrine.%arg-1's uuid%.infos} to player
			if arg-3 is "HubParkour":
				send {HubParkour.%arg-1's uuid%.infos} to player
			if arg-3 is "1SecBM":
				send {1SecBM.%arg-1's uuid%.infos} to player
			if arg-3 is "FBSG":
				send {FBSG.%arg-1's uuid%.infos} to player	

command /resetNPCs:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		resetNPCs()

command /settotalpoints <int> <player>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {total_points.%arg-2's uuid%} to arg-1
		send "[&c&lTheEvent580 - Admin&r] The new total points of %arg-2% is now %arg-1% ╣"

command /seeblock:
	aliases: colorblind
	description: toggles the action bar to see the block and all
	trigger:
		if {check_block.%player%} is false:
			set {check_block.%player%} to true
			send "%nl%[&c&lTheEvent580 - Colorblind&r] You are now able to see the name of the block you're looking at !%nl%"
		else:
			set {check_block.%player%} to false
			send "%nl%[&c&lTheEvent580 - Colorblind&r] You can no longer see the name of the block you're looking at !%nl%"

command /wl <text> [<offline player>]:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-1 is "add":
			if arg-2 is not set:
				send "[&c&lTheEvent580 - Admin&r] Please enter a username"
			else:
				if arg-2 is not whitelisted:
					make console execute command "whitelist add %arg-2%"
					send "[&c&lTheEvent580 - Admin&r] Player %arg-2% has been added to the whitelist"
				else:
					send "[&c&lTheEvent580 - Admin&r] Player %arg-2% is already whitelisted"
		if arg-1 is "remove":
			if arg-2 is not set:
				send "[&c&lTheEvent580 - Admin&r] Please enter a username"
			else:
				if arg-2 is whitelisted:
					make console execute command "whitelist remove %arg-2%"
					send "[&c&lTheEvent580 - Admin&r] Player %arg-2% has been removed from the whitelist"
				else:
					send "[&c&lTheEvent580 - Admin&r] Player %arg-2% is already unwhitelisted"
		if arg-1 is "list":
			make console execute command "whitelist list"
			send "[&c&lTheEvent580 - Admin&r] Please check the console"

command /addplayers <int>:
	permission: *
	trigger:
		add arg-1 to {checking_finished_players}

command /try:
	permission: *
	trigger:
		give 1 of carrot on a stick named "X Cross Wrong Way" to player

command /color <offline player>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		set {arg1} to "%arg-1%"
		set {arg1.uuid} to arg-1's uuid
		set {head} to "%arg-1%" parsed as an offline player
		create a gui with virtual chest inventory with 3 rows named "New color for &f%{color.%arg-1's uuid%}%%arg-1%":
			make gui slot 4 with skull of {head} named "&f%{color.%arg-1's uuid%}%%arg-1%'s head"
			#if player has permission "group.rouge":
			#	make gui slot 5 with red concrete named "&rCurrent color : &cRed"
			#else if player has permission "group.orange":
			#	make gui slot 5 with orange concrete named "&rCurrent color : &6Orange"
			#else if player has permission "group.jaune":
			#	make gui slot 5 with yellow concrete named "&rCurrent color : &eYellow"
			#else if player has permission "group.vert":
			#	make gui slot 5 with lime concrete named "&rCurrent color : &aLime"
			#else if player has permission "group.bleu_clair":
			#	make gui slot 5 with light blue concrete named "&rCurrent color : &bLight Blue"
			#else if player has permission "group.bleu":
			#	make gui slot 5 with blue concrete named "&rCurrent color : &1Blue"
			#else if player has permission "group.violet":
			#	make gui slot 5 with purple concrete named "&rCurrent color : &5Purple"
			#else if player has permission "group.rose":
			#	make gui slot 5 with pink concrete named "&rCurrent color : &dPink"
			#else if player has permission "group.spectators":
			#	make gui slot 5 with gray concrete named "&rCurrent color : &8Spectator"
			make gui slot 10 with red concrete named "&cRed":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set rouge"
				set {color.%{arg1.uuid}%} to "ラ&c "
			make gui slot 11 with orange concrete named "&6Orange":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set orange"
				set {color.%{arg1.uuid}%} to "ャ&6 "
			make gui slot 19 with yellow concrete named "&eYellow":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set jaune"
				set {color.%{arg1.uuid}%} to "ギ&e "
			make gui slot 20 with lime concrete named "&aGreen":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set vert"
				set {color.%{arg1.uuid}%} to "画&a "
			make gui slot 15 with light blue concrete named "&bLight Blue":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set bleu_clair"
				set {color.%{arg1.uuid}%} to "動&b "
			make gui slot 16 with blue concrete named "&1Blue":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set bleu"
				set {color.%{arg1.uuid}%} to "像&1 "
			make gui slot 24 with purple concrete named "&5Purple":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set violet"
				set {color.%{arg1.uuid}%} to "の&5 "
			make gui slot 25 with pink concrete named "&dPink":
				close player's inventory
				if {arg-1} has permission "group.spectators":
					add 1 to {online_players}
				make console execute command "lp user %{arg1}% parent set rose"
				set {color.%{arg1.uuid}%} to "目&d "
			make gui slot 22 with gray concrete named "&8Spectator":
				close player's inventory
				remove 1 from {online_players}
				make console execute command "lp user %{arg1}% parent set spectators"
				set {color.%{arg1.uuid}%} to "露&8 "
		open the last gui for the player

command /end:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				kick loop-player due to "[&c&lTheEvent580&r] TheEvent580 is over, thanks for playing and see you soon !"
				make console execute command "wl remove %loop-player%"

command /grab <player> <player>:
	permission: *
	permission message: &cThis command does not exist
	trigger:
		if arg-1 != arg-2:
			if {ride.%arg-1%} is set:
				clear {ride.%arg-1%}
			else:
				set {ride.%arg-1%} to arg-2
				make arg-1 ride arg-2
				send "[&c&lTheEvent580&r] You grabbed %{color.%arg-1's uuid%}% %arg-1%&r !" to arg-2
				send "[&c&lTheEvent580&r] You've been grabbed by %{color.%arg-2's uuid%}% %arg-2%&r !" to arg-1
		else:
			send "[&c&lTheEvent580&r] You cannot grab yourself" to arg-1

command /playsgmusic:
	permission: *
	trigger:
		set {_random} to a random number between 1 and 8
		if {_random} = 1:
			loop all players:
				play sound "custom:sg1" in record category with volume 1 to the loop-player
				wait 155 seconds
		if {_random} = 2:
			loop all players:
				play sound "custom:sg2" in record category with volume 1 to the loop-player
				wait 218 seconds
		if {_random} = 3:
			loop all players:
				play sound "custom:sg3" in record category with volume 1 to the loop-player
				wait 196 seconds
		if {_random} = 4:
			loop all players:
				play sound "custom:sg4" in record category with volume 1 to the loop-player
				wait 194 seconds
		if {_random} = 5:
			loop all players:
				play sound "custom:sg5" in record category with volume 1 to the loop-player
				wait 218 seconds
		if {_random} = 6:
			loop all players:
				play sound "custom:sg6" in record category with volume 1 to the loop-player
				wait 224 seconds
		if {_random} = 7:
			loop all players:
				play sound "custom:sg7" in record category with volume 1 to the loop-player
				wait 170 seconds
		if {_random} = 8:
			loop all players:
				play sound "custom:sg8" in record category with volume 1 to the loop-player
				wait 165 seconds
		if {timer} = 6:
			make console execute command "playsgmusic"
	
command /item <player>:
	permission: *
	trigger:
		give 1 of carrot on a stick named "&rSwap players and spectators" with lore "&rRight click to swap the players and the spectators" to arg-1

command /seepoints <player>:
	permission: *
	trigger:
		send {points.%arg-1's uuid%} to player

command /storepurchase <text>:
	permission: *
	trigger:
		broadcast "[&c&lTheEvent580 - Store&r] %arg-1%"

command /uuid <offline player>:
	permission: *
	trigger:
		send "Here is %arg-1%'s uuid : %arg-1's uuid%<reset>"