every tick:
	reloadScoreboard()
	reloadTab()
	if {race_timer} is true:
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if {finished.%loop-player's uuid%} is false:
					add 0.05 to {race_lap_time.%loop-player's uuid%}
					add 0.05 to {race_total_time.%loop-player's uuid%}
			reloadTimer()

	if {jeu_condi} is 0:
		if {timer} or {timer_save} is not 7:
			loop all players:
				if block 1 meter below loop-player is hay bale:
					make loop-player execute command "spawn"
					add 1 to {compl_parcour.%loop-player's uuid%}
					updateParkour()
				if block 0 meter below loop-player is water:
					if loop-player's gamemode is adventure:
						make loop-player execute command "spawn"
				if block 0 or 1 meter below loop-player is dirt path:
					remove speed from loop-player
					apply speed 2 without particles to loop-player for 1 second
				if block 1 meter below loop-player is ochre froglight:
					make loop-player execute command "spawn"
				if block 1 meter below loop-player is verdant froglight:
					teleport loop-player to location(193.5,69,-381.5,world "overworld", 0.01,0.01)
				if block 1 meter below loop-player is jigsaw block:
					if helmet of loop-player is not air:
						set {flag.%loop-player's uuid%} to false
						send "[<##155966>&lTheEvent580&r] Your flag has been removed" to loop-player
						clear helmet of loop-player
					if {HubParkour.%loop-player's uuid%} is false:
						make server execute command "achivement %loop-player% give HubParkour"
				if block 2 meter under loop-player is powder_snow:
					if {Secret_Base_1.%loop-player's uuid%} is false:
						make server execute command "achivement %loop-player% give Secret_Base_1"
		loop all players:
			while {ride.%loop-player's uuid%} is set:
				make loop-player ride {ride.%loop-player's uuid%}
				wait 1 tick

	else if {jeu_condi} is 2: #Parkour
		loop all players:
			if y-coordinate of loop-player is less than 100:
				if {parkour.main_level.%loop-player's uuid%} and {parkour.sub_level.%loop-player's uuid%} = 1:
					teleport loop-player to location(131.5, 129.00, 201.5,"parkour", -90, 0)
				else if game mode of loop-player is spectator:
					teleport loop-player to location(131.5, 129.00, 201.5,"parkour", -90, 0)
				else:
					teleport loop-player to {parkour_checkpoint_location.%loop-player's uuid%}
			if the game mode of loop-player is adventure:
				if loop-player doesn't have permission "group.spectators":
					if {finished.%loop-player's uuid%} = false:
						if the x-coordinate of loop-player > {parkour.next_level_coord.%loop-player's uuid%}:
							if the y coordinate of loop-player > 128:
								if the z-coordinate of loop-player is between 198 and 204 :
									set {parkour_checkpoint_location.%loop-player's uuid%} to location of loop-player
									add 1 to {parkour.sub_level.%loop-player's uuid%}
									if {parkour.main_level.%loop-player's uuid%} != 4:
										add 16 to {parkour.next_level_coord.%loop-player's uuid%}
									else:
										if {parkour.sub_level.%loop-player's uuid%} != 7:
											add 16 to {parkour.next_level_coord.%loop-player's uuid%}
										else:
											add 32 to {parkour.next_level_coord.%loop-player's uuid%}
									if {parkour.main_level.%loop-player's uuid%} = 1:
										if {parkour.skip_used.%loop-player's uuid%} = false:
											add 0.1 to {game_multiplier.%loop-player's uuid%}
										if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
											send "[<##155966>&lTheEvent580 - Parkour&r] &aEasy&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
											if {parkour.sub_level.%loop-player's uuid%} = 7:
												set {parkour.sub_level.%loop-player's uuid%} to 1
												add 1 to {parkour.main_level.%loop-player's uuid%}
												loop all players:
													if loop-player-1 = loop-player-2:
														send "[<##155966>&lTheEvent580 - Parkour&r] &aEasy&r levels completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player-1
													else:
														send "[<##155966>&lTheEvent580 - Parkour&r] %loop-player-1% finished &aEasy&r levels 1-1 to 1-6." to loop-player-2
									if {parkour.main_level.%loop-player's uuid%} = 2:
										if {parkour.skip_used.%loop-player's uuid%} = false:
											add 0.2 to {game_multiplier.%loop-player's uuid%}
										if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
											send "[<##155966>&lTheEvent580 - Parkour&r] &6Medium&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
											if {parkour.sub_level.%loop-player's uuid%} = 7:
												set {parkour.sub_level.%loop-player's uuid%} to 1
												add 1 to {parkour.main_level.%loop-player's uuid%}
												loop all players:
													if loop-player-1 = loop-player-2:
														send "[<##155966>&lTheEvent580 - Parkour&r] &6Medium&r levels completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player-1
													else:
														send "[<##155966>&lTheEvent580 - Parkour&r] %loop-player-1% finished &6Medium&r levels 2-1 to 2-6." to loop-player-2
									if {parkour.main_level.%loop-player's uuid%} = 3:
										if {parkour.skip_used.%loop-player's uuid%} = false:
											add 0.4 to {game_multiplier.%loop-player's uuid%}
										if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
											send "[<##155966>&lTheEvent580 - Parkour&r] &cHard&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
											if {parkour.sub_level.%loop-player's uuid%} = 7:
												set {parkour.sub_level.%loop-player's uuid%} to 1
												add 1 to {parkour.main_level.%loop-player's uuid%}
												loop all players:
													if loop-player-1 = loop-player-2:
														send "[<##155966>&lTheEvent580 - Parkour&r] &cHard&r levels completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player-1
													else:
														send "[<##155966>&lTheEvent580 - Parkour&r] %loop-player-1% finished &cHard&r levels 3-1 to 3-6." to loop-player-2
									if {parkour.main_level.%loop-player's uuid%} = 4:
										if {parkour.sub_level.%loop-player's uuid%} = 8:
											clear loop-player's inventory
										if {parkour.sub_level.%loop-player's uuid%} = 8:
											add 1.3 to {game_multiplier.%loop-player's uuid%}
											make console execute command "fly %loop-player%"
											loop all players:
												if loop-player-1 = loop-player-2:
													send "[<##155966>&lTheEvent580 - Parkour&r] You fully finished &6Parkour&r ! You get rewarded with %checkPoints({points_game.%loop-player-1's uuid%} * {game_multiplier.%loop-player-1's uuid%})% 工 !" to loop-player-1
												else:
													if {finished.%loop-player-2's uuid%} = true:
														if loop-player-2 doesn't have permission "group.spectators":
															command("gamepoints %loop-player-2% %10*{multiplier}% %loop-player-1% completed &r&6&lParkour&r<##155966> after you (unmultiplied)")
															send "[<##155966>&lTheEvent580 - Parkour&r] %loop-player-1% finished &6Parkour&r after you ! You get rewarded with %checkPoints(10*{multiplier})% 工 (unmultiplied)!" to loop-player-2
													send "[<##155966>&lTheEvent580 - Parkour&r] %loop-player-1% finished all 25 levels of &6Parkour&r !" to loop-player-2
											wait 2 ticks
											set {finished.%loop-player's uuid%} to true
										else:
											if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
												if {parkour.skip_used.%loop-player's uuid%} = false:
													add 0.75 to {game_multiplier.%loop-player's uuid%}
												send "[<##155966>&lTheEvent580 - Parkour&r] &4Extreme&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
					#if block 2 meters below loop-player is iron_block:
					#	if {parkour_checkpoint.%loop-player's uuid%} is 0:
					#		add round({pts_lvl_1}) to {points_game.%loop-player's uuid%}
					#		add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
					#		add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
					#		if {parkour_checkpoint_1} is false:
					#			set {parkour_checkpoint_1} to true
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to get to checkpoint 1"
					#		else if {parkour_checkpoint_1} is true:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 1"
					#		play sound "custom:coins" in voice category with volume 2 to the loop-player
					#		send "[<##155966>&lTheEvent580&r] You got to the checkpoint 1 [&6+%checkPoints({pts_lvl_1})% &r工]" to loop-player
					#		remove {remove_pts_lvl_1} from {pts_lvl_1}
					#		set {parkour_checkpoint.%loop-player's uuid%} to 1
					#		set {parkour_checkpoint_location.%loop-player's uuid%} to loop-player's location
					#	if {parkour_checkpoint.%loop-player's uuid%} is 2:
					#		if {parkour_skip.%loop-player's uuid%} = false:
					#			add round({pts_lvl_3}) to {points_game.%loop-player's uuid%}
					#			add round({pts_lvl_3}) to {total_points.%loop-player's uuid%}
					#			add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
					#			if {parkour_checkpoint_3} is false:
					#				set {parkour_checkpoint_3} to true
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to get to checkpoint 3"
					#			else if {parkour_checkpoint_3} is true:
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 3"
					#			play sound "custom:coins" in voice category with volume 2 to the loop-player
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 3 [&6+%checkPoints({pts_lvl_3})% &r工]" to loop-player
					#			remove {remove_pts_lvl_3} from {pts_lvl_3}
					#		else:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 3 by skipping section 2"
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 3 by skipping section 2, you did not recieve any points" to loop-player
					#		set {parkour_checkpoint.%loop-player's uuid%} to 3
					#		set {parkour_checkpoint_location.%loop-player's uuid%} to loop-player's location
					#	if {parkour_checkpoint.%loop-player's uuid%} is 4:
					#		if the inventory of loop-player contains a carrot on a stick named "&6Skip Level":
					#			add round({pts_lvl_5}) to {points_game.%loop-player's uuid%}
					#			add round({pts_lvl_5}) to {total_points.%loop-player's uuid%}
					#			add round({pts_lvl_5}) to {total_points_event.%loop-player's uuid%}
					#			if {parkour_checkpoint_5} is false:
					#				set {parkour_checkpoint_5} to true
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to get to checkpoint 5"
					#			else if {parkour_checkpoint_5} is true:
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 5"
					#			play sound "custom:coins" in voice category with volume 2 to the loop-player
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 5 [&6+%checkPoints({pts_lvl_5})% &r工]" to loop-player
					#			remove {remove_pts_lvl_5} from {pts_lvl_5}
					#			set {parkour_skip.%loop-player's uuid%} to true
					#			send "[<##155966>&lTheEvent580&r] You are at the last section of the &6&lParkour&r, you can no longer skip. Good luck !" to loop-player
					#		else:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 5 by skipping section 4"
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 5 by skipping section 4, you did not recieve any points" to loop-player
					#		set {parkour_checkpoint.%loop-player's uuid%} to 5
					#		set {parkour_checkpoint_location.%loop-player's uuid%} to loop-player's location
					#		remove 1 of carrot on a stick from loop-player's inventory
					#if block 2 meters below loop-player is gold_block:
					#	if {parkour_checkpoint.%loop-player's uuid%} is "Start":
					#		add {pts_lvl_0} to {points_game.%loop-player's uuid%}
					#		add {pts_lvl_0} to {total_points.%loop-player's uuid%}
					#		add {pts_lvl_0} to {total_points_event.%loop-player's uuid%}
					#		if {parkour_checkpoint_0} is false:
					#			set {parkour_checkpoint_0} to true
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to get to checkpoint 0 ( The easiest one )"
					#		else if {parkour_checkpoint_0} is true:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 0 ( The easiest one )"
					#		play sound "custom:coins" in voice category with volume 2 to the loop-player
					#		send "[<##155966>&lTheEvent580&r] You got to the checkpoint 0 ( The easiest one ) [&6+%{pts_lvl_0}% &r工]" to loop-player
					#		remove {remove_pts_lvl_0} from {pts_lvl_0}
					#		set {parkour_checkpoint.%loop-player's uuid%} to 0
					#		set {parkour_checkpoint_location.%loop-player's uuid%} to loop-player's location
					#	if {parkour_checkpoint.%loop-player's uuid%} is 1:
					#		if {parkour_skip.%loop-player's uuid%} = false:
					#			add round({pts_lvl_2}) to {points_game.%loop-player's uuid%}
					#			add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
					#			add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
					#			if {parkour_checkpoint_2} is false:
					#				set {parkour_checkpoint_2} to true
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to get to checkpoint 2"
					#			else if {parkour_checkpoint_2} is true:
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 2"
					#			play sound "custom:coins" in voice category with volume 2 to the loop-player
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 2 [&6+%checkPoints({pts_lvl_2})% &r工]" to loop-player
					#			remove {remove_pts_lvl_2} from {pts_lvl_2}
					#		else:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 2 by skipping section 1"
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 2 by skipping section 1, you did not recieve any points" to loop-player
					#		set {parkour_checkpoint.%loop-player's uuid%} to 2
					#		set {parkour_checkpoint_location.%loop-player's uuid%} to loop-player's location
					#	if {parkour_checkpoint.%loop-player's uuid%} is 3:
					#		if {parkour_skip.%loop-player's uuid%} = false:
					#			add round({pts_lvl_4}) to {points_game.%loop-player's uuid%}
					#			add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
					#			add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
					#			if {parkour_checkpoint_4} is false:
					#				set {parkour_checkpoint_4} to true
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to get to checkpoint 4"
					#			else if {parkour_checkpoint_4} is true:
					#				broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 4"
					#			play sound "custom:coins" in voice category with volume 2 to the loop-player
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 4 [&6+%checkPoints({pts_lvl_4})% &r工]" to loop-player
					#			remove {remove_pts_lvl_4} from {pts_lvl_4}
					#		else:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r got to checkpoint 2 by skipping section 1"
					#			send "[<##155966>&lTheEvent580&r] You got to the checkpoint 2 by skipping section 1, you did not recieve any points" to loop-player
					#		set {parkour_checkpoint.%loop-player's uuid%} to 4
					#		set {parkour_checkpoint_location.%loop-player's uuid%} to loop-player's location
					#if block 2 meters below loop-player is diamond_block:
					#	if {parkour_checkpoint.%loop-player's uuid%} is 5:
					#		make console execute command "/see %loop-player%"
					#		set {finished.%loop-player's uuid%} to true
					#		make server execute command "/hide %loop-player%"
					#		make server execute command "/hide %loop-player%"
					#		force loop-player to fly
					#		allow fly for loop-player
					#		add {pts_fin} to {points_game.%loop-player's uuid%}
					#		add {pts_fin} to {total_points.%loop-player's uuid%}
					#		add {pts_fin} to {total_points_event.%loop-player's uuid%}
					#		if {parkour_fin} is false:
					#			set {parkour_fin} to true
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r was the 1st player to finish &6&lParkour&r !"
					#		else if {parkour_fin} is true:
					#			broadcast "[<##155966>&lTheEvent580&r] &6&l%loop-player%&r finished &6&lParkour&r !"
					#		play sound "custom:coins" in voice category with volume 2 to the loop-player
					#		send "[<##155966>&lTheEvent580&r] You just finished &6&lParkour&r [&6+%checkPoints({pts_fin})%	 &r工]" to loop-player
					#		remove {remove_pts_fin} from {pts_fin}
					#		set {parkour_checkpoint.%loop-player's uuid%} to "End"
					#		set {gamemode.%loop-player's uuid%} to 3
					#		add 1 to {finished_players}
					#		set slot 0 of loop-player to compass named "&rTeleport to player"
					#		set slot 1 of loop-player to feather named "&rChange player's fly speed"

	else if {jeu_condi} is 3: #Bingo
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if {bingo_kill.%loop-player's uuid%} is true:
					set {bingo_kill.%loop-player's uuid%} to 2
					remove 1 of iron sword from loop-player's inventory
					give 1 of diamond sword of unbreaking 250 and sharpness 1 named "&eDiamond sword" to loop-player
					create a gui with virtual chest inventory with 3 rows named "&eUpgrade your pickaxe":
						make gui slot 11 with diamond pickaxe of unbreaking 250 and efficiency 4 and silk touch named "&eSilk touch diamond pickaxe":
							close player's inventory
							remove 1 of iron pickaxe of unbreaking 250 and efficiency 2 and silk touch from player's inventory
							give 1 of diamond pickaxe of unbreaking 250 and efficiency 4 and silk touch named "&eSilk touch diamond pickaxe" to player
						make gui slot 15 with diamond pickaxe of unbreaking 250 and efficiency 4 and fortune 1 named "&eFortune diamond pickaxe":
							close player's inventory
							remove 1 of iron pickaxe of unbreaking 250 and efficiency 2 and fortune 2 from player's inventory
							give 1 of diamond pickaxe of unbreaking 250 and efficiency 4 and fortune 1 named "&eFortune diamond pickaxe" to player
					open the last gui for the loop-player
				loop all items in loop-player's inventory:
					if loop-item is red sandstone:
						wait 1 tick
						if {bingo_case_1.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_1_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_1_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eRed Sandstone&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eRed Sandstone&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_1_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eRed Sandstone&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eRed Sandstone&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_1_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_1.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_1}% Collected &r&eRed Sandstone")
							add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
							remove round(5*{multiplier}) from {pts_lvl_1}
							remove 1 red sandstone from loop-player's inventory
					if loop-item is white wool:
						wait 1 tick
						if {bingo_case_2.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_2_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_2_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eWhite Wool&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eWhite Wool&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_2_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eWhite Wool&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eWhite Wool&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_2_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_2.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_2}% Collected &r&eWhite Wool")
							add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
							remove round(15*{multiplier}) from {pts_lvl_2}
							remove 1 white wool from loop-player's inventory
					if loop-item is gold block:
						wait 1 tick
						if {bingo_case_3.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_3_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_3_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eGold Block&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eGold Block&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_3_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eGold Block&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eGold Block&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_3_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_3.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_3}% Collected &r&eGold Block")
							add round({pts_lvl_3}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
							remove round(25*{multiplier}) from {pts_lvl_3}
							remove 1 gold block from loop-player's inventory
					if loop-item is amethyst cluster:
						wait 1 tick
						if {bingo_case_4.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_4_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_4_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eAmethyst Cluster&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eAmethyst Cluster&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_4_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eAmethyst Cluster&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eAmethyst Cluster&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_4_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_4.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_4}% Collected &r&eAmethyst Cluster")
							add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
							remove round(35*{multiplier}) from {pts_lvl_4}
							remove 1 amethyst cluster from loop-player's inventory
					if loop-item is enchanting table:
						wait 1 tick
						if {bingo_case_5.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_5_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_5_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eEnchanting table&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eEnchanting table&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_5_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eEnchanting table&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eEnchanting table&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_5_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_5.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_5}% Collected &r&eEnchanting table")
							add round({pts_lvl_5}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_5}) to {total_points_event.%loop-player's uuid%}
							remove round(45*{multiplier}) from {pts_lvl_5}
							remove 1 enchanting table from loop-player's inventory
					if loop-item is dune armor trim smithing template:
						wait 1 tick
						if {bingo_case_6.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_6_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_6_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eDune armor trim&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eDune armor trim&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_6_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eDune armor trim&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eDune armor trim&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_6_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_6.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_6}% Collected &r&eDune armor trim")
							add round({pts_lvl_6}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_6}) to {total_points_event.%loop-player's uuid%}
							remove round(55*{multiplier}) from {pts_lvl_6}
							remove 1 dune armor trim smithing template from loop-player's inventory
					if loop-item is blue candle:
						wait 1 tick
						if {bingo_case_7.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_7_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_7_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eBlue Candle&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eBlue Candle&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_7_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eBlue Candle&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eBlue Candle&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_7_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_7.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_7}% Collected &r&eBlue Candle")
							add round({pts_lvl_7}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_7}) to {total_points_event.%loop-player's uuid%}
							remove round(70*{multiplier}) from {pts_lvl_7}
							remove 1 blue candle from loop-player's inventory
					if loop-item is deepslate emerald ore:
						wait 1 tick
						if {bingo_case_8.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_8_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_8_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eDeepslate Emerald Ore&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eDeepslate Emerald Ore&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_8_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eDeepslate Emerald Ore&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eDeepslate Emerald Ore&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_8_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_8.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_8}% Collected &r&eDeepslate Emerald Ore")
							add round({pts_lvl_8}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_8}) to {total_points_event.%loop-player's uuid%}
							remove round(85*{multiplier}) from {pts_lvl_8}
							remove 1 deepslate emerald ore from loop-player's inventory
					if loop-item is zombie head:
						wait 1 tick
						if {bingo_case_9.%loop-player's uuid%} is false:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_9_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_9_1} is true:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r completed the &eZombie Head&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eZombie Head&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
							if {bingo_case_9_1} is false:
								broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &eZombie Head&r slot (%{bingo_cases.%loop-player's uuid%}%/9)."
								send "[<##155966>&lTheEvent580&r] You completed the &eZombie Head&r slot (%{bingo_cases.%loop-player's uuid%}%/9)." to loop-player
								set {bingo_case_9_1} to true
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_9.%loop-player's uuid%} to true
							command("gamepoints %loop-player% %{pts_lvl_9}% Collected &r&eZombie Head")
							add round({pts_lvl_9}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_9}) to {total_points_event.%loop-player's uuid%}
							remove round(100*{multiplier}) from {pts_lvl_9}
							remove 1 zombie head from loop-player's inventory
				if {bingo_cases.%loop-player's uuid%} is 9:
					set {bingo_cases.%loop-player's uuid%} to "All"
					if {bingo_fin} is false:
						set {bingo_fin} to true
						broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r is the 1st player to complete the &e&lBingo&r."
					else if {bingo_fin} is true:
						broadcast "[<##155966>&lTheEvent580&r] &e%loop-player%&r just completed the &e&lBingo&r."
					send "[<##155966>&lTheEvent580&r] You just completed the bingo &e&lBingo&r" to loop-player
					set {bingo_fin.%loop-player's uuid%} to true
					make console execute command "/see %loop-player%"
					set {finished.%loop-player's uuid%} to true
					command("gamepoints %loop-player% %10*{multiplier}% Completion bonus")
					add 10*{multiplier} to {total_points.%loop-player's uuid%}
					add 10*{multiplier} to {total_points_event.%loop-player's uuid%}
					set loop-player's gamemode to adventure
					set slot 0 of loop-player to compass named "&rTeleport to player"
					set slot 1 of loop-player to feather named "&rChange player's fly speed"
					make server execute command "/hide %loop-player%"
					force loop-player to fly
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					add 1 to {finished_players}

	else if {jeu_condi} is 4: #Find The Button
		loop all players:
			if the game mode of loop-player is adventure:
				if loop-player doesn't have permission "group.spectators":
					if {ftb_fin.%loop-player's uuid%} is 11:
						broadcast "[<##155966>&lTheEvent580&r] &a&l%loop-player%&r found all the buttons and finished the &a&lFind The Button&r !"
						set {ftb_fin.%loop-player's uuid%} to "All"
						set {gamemode.%loop-player's uuid%} to 3
						add 1 to {finished_players}
						make console execute command "/see %loop-player%"
						set {finished.%loop-player's uuid%} to true
						command("gamepoints %loop-player% %10*{multiplier}% Completion bonus")
						add 10*{multiplier} to {total_points.%loop-player's uuid%}
						add 10*{multiplier} to {total_points_event.%loop-player's uuid%}
						set slot 0 of loop-player to compass named "&rTeleport to player"
						set slot 1 of loop-player to feather named "&rChange player's fly speed"
						make console execute command "/hide %loop-player%"
						make console execute command "/hide %loop-player%"
						force loop-player to fly
						allow fly for loop-player

	else if {jeu_condi} is 5: #Races
		loop all players:
			if the y coordinate of loop-player < 100:
				if {race_checkpoint.%loop-player's uuid%} = 0:
					teleport loop-player to location(1, 131, 3.5, world("Races_lap_3"),180, 0)
				else:
					teleport loop-player to {race_checkpoint_pos.%loop-player's uuid%}
			if block 2 meter under loop-player is pearlescent froglight:
				remove speed from loop-player
				apply speed 2 without particles to loop-player for 50 ticks
			if block 3 meter under loop-player is coal block:
				if loop-player's inventory doesn't contain trident:
					give 1 of trident of unbreaking 250 and riptide 1 to loop-player
					send title "&7[&a+&7] &aTrident equipped" to loop-player for 1 second
			if the x coordinate of loop-player is between 4 and -4:
				if the y coordinate of loop-player is between 128 and 134:
					if the z coordinate of loop-player is between 1 and 0:
						if {finished.%loop-player's uuid%} = false:
							if {race_checkpoint.%loop-player's uuid%} >= 2:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								if {race_lap.%loop-player's uuid%} = 3:
									if {race_lap_3_finished} = false:
										set {race_lap_3_finished} to true
										set {race_lap} to "All"
										make console execute command "execute in minecraft:races_lap_3 run fill -10 130 -43 -12 136 -43 air replace stone"
										make console execute command "execute in minecraft:races_lap_3 run fill -16 130 -43 -18 136 -43 air replace smooth_basalt"
									set {gamemode.%loop-player's uuid%} to 3
									set {finished.%loop-player's uuid%} to true
									clear loop-player's inventory
									make console execute command "/hide %loop-player%"
									force loop-player to fly
									allow fly for loop-player
									broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the race in &b%{race_total_time.%loop-player's uuid%}% &rseconds"
									send "[<##155966>&lTheEvent580&r] You just completed the race in &b%{race_total_time.%loop-player's uuid%}% &rseconds" to loop-player
									command("gamepoints %loop-player% %{pts_lvl_3}% Completed &r&b&lMultilap")
									add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
									add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
									add 1 to {finished_players}
									remove round(80*{multiplier}) from {pts_lvl_3}
									set slot 0 of loop-player to compass named "&rTeleport to player"
									set slot 1 of loop-player to feather named "&rChange player's fly speed"
								else:
									if {race_lap.%loop-player's uuid%} = 1:
										if {race_lap_1_finished} = false:
											set {race_lap_1_finished} to true
											set {race_lap} to 2
											make console execute command "execute in minecraft:races_lap_3 run fill -10 130 -43 -12 136 -43 stone replace air"
											make console execute command "execute in minecraft:races_lap_3 run fill -16 130 -43 -18 136 -43 air replace smooth_basalt"
										broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 1st lap of the race in &b%{race_lap_time.%loop-player's uuid%}% &rseconds"
										send "[<##155966>&lTheEvent580&r] You just completed the 1st lap of the race in &b%{race_lap_time.%loop-player's uuid%}% &rseconds" to loop-player
										command("gamepoints %loop-player% %{pts_lvl_1}% Completed Lap 1")
										add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
										add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
										remove round(40*{multiplier}) from {pts_lvl_1}
										set {_item} to carrot on a stick
										set {_item.nbt} to nbt compound of {_item}
										add nbt compound of "{display:{Name:'{""text"":""You are on Lap 2"",""italic"""":""false"",""color"":""gold""}'},CustomModelData:29}" to {_item.nbt}
										set slot 40 of loop-player to {_item}
									if {race_lap.%loop-player's uuid%} = 2:
										if {race_lap_2_finished} = false:
											set {race_lap_2_finished} to true
											set {race_lap} to 3
											make console execute command "execute in minecraft:races_lap_3 run fill -16 130 -43 -18 136 -43 smooth_basalt replace air"
											make console execute command "execute in minecraft:races_lap_3 run fill -4 130 -43 -6 136 -43 air replace blackstone"
										broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 2nd lap of the race in &b%{race_lap_time.%loop-player's uuid%}% &rseconds"
										send "[<##155966>&lTheEvent580&r] You just completed the 2nd lap of the race in &b%{race_lap_time.%loop-player's uuid%}% &rseconds" to loop-player
										command("gamepoints %loop-player% %{pts_lvl_2}% Completed Lap 2")
										add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
										add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
										remove round(60*{multiplier}) from {pts_lvl_2}
										set {_item} to carrot on a stick
										set {_item.nbt} to nbt compound of {_item}
										add nbt compound of "{display:{Name:'{""text"":""You are on Lap 3"",""italic"":""false"",""color"":""red""}'},CustomModelData:31}" to {_item.nbt}
										set slot 40 of loop-player to {_item}
									add 1 to {race_lap.%loop-player's uuid%}
									send title "&7[&bLap&7] &bEntered Lap %{race_lap.%loop-player's uuid%}%" to loop-player for 1 second
									set {race_lap_time.%loop-player's uuid%} to 0
						set {race_checkpoint.%loop-player's uuid%} to 0
			if the x coordinate of loop-player is between 22 and 24:
				if the y coordinate of loop-player is between 155 and 160:
					if the z coordinate of loop-player is between -51 and -42:
						if {race_checkpoint.%loop-player's uuid%} = 1:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
			if the x coordinate of loop-player is between 31 and 30:
				if the y coordinate of loop-player is between 139 and 145:
					if the z coordinate of loop-player is between -8 and -16:
						if {race_boat.%loop-player's uuid%} = true:
							send title "&7[&c-&7] &cBoat removed" to loop-player for 1 second
							if {in_vehicle.%loop-player's uuid%} = true:
								make console execute command "execute in minecraft:races_lap_3 at %loop-player% run kill @e[type=minecraft:boat,limit=1,sort=nearest]"
							remove 5 of oak boat from loop-player
							set {race_boat.%loop-player's uuid%} to false
			if the x coordinate of loop-player is between 26 and 27:
				if the y coordinate of loop-player is between 155 and 160:
					if the z coordinate of loop-player is between -51 and -42:
						if {race_boat.%loop-player's uuid%} is false:
							send title "&7[&a+&7] &aBoat equipped" to loop-player for 1 second
							give 1 of oak boat to loop-player
							set {race_boat.%loop-player's uuid%} to true
			if the x coordinate of loop-player is between -5 and -4:
				if the y coordinate of loop-player is between 130 and 135:
					if the z coordinate of loop-player is between 13 and 18:
						if loop-player's inventory contain elytra:
							send title "&7[&c-&7] &cElytra removed" to loop-player for 1 second
							remove 1 of elytra from loop-player
			if the x coordinate of loop-player is between -15 and -6:
				if the y coordinate of loop-player is between 129 and 134:
					if the z coordinate of loop-player is between -34 and -36:
						if {race_checkpoint.%loop-player's uuid%} = 0:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							add 1 to {race_checkpoint.%loop-player's uuid%}
							if {finished.%loop-player's uuid%} = false:
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
			if the x coordinate of loop-player is between -55 and -60:
				if the y coordinate of loop-player is between 139 and 144:
					if the z coordinate of loop-player is between -27 and -26:
						if loop-player's inventory doesn't contain elytra:
							set chestplate of loop-player to elytra of unbreaking 250
							send title "&7[&a+&7] &aElytra equipped" to loop-player for 1 second
					if the z coordinate of loop-player is between -34 and -32:
						if {race_checkpoint.%loop-player's uuid%} = 1:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
			if the x coordinate of loop-player is between 0 and 20:
				if the y coordinate of loop-player is between 138 and 200:
					if the z coordinate of loop-player is between -32 and -30:
						if {race_checkpoint.%loop-player's uuid%} = 2:
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
				if the y coordinate of loop-player is between 126 and 130:
					if the z coordinate of loop-player is between -89 and -87:
						if {race_checkpoint.%loop-player's uuid%} = 1:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
					if the z coordinate of loop-player is between -90 and -89:
						if loop-player's inventory contain trident:
							send title "&7[&c-&7] &cTrident removed" to loop-player for 0.1 second
							remove 1 of trident from loop-player
					if the z coordinate of loop-player is between -88 and -87:
						if loop-player's inventory doesn't contain elytra:
							set chestplate of loop-player to elytra of unbreaking 250
							send title "&7[&a+&7] &aElytra equipped" to loop-player for 1 second
				if the y coordinate of loop-player is bigger than 138:
					if the z coordinate of loop-player is between -39 and -38:
						if loop-player's inventory contain elytra:
							send title "&7[&c-&7] &cElytra removed" to loop-player for 1 second
							remove 1 of elytra from loop-player
			if block 1.6 meter under loop-player is structure block:
				push loop-player up at speed 1
				push loop-player forward at speed 0.6
			if block 1 meter under loop-player is command block:
				remove jump boost from loop-player
				apply jump boost 8.7 without particles to loop-player for 2 ticks
		#	if {courses} is "boat":
		#		if y-coordinate of loop-player is less than 0:
		#			clear loop-player's inventory
		#			if {courses_boat.%loop-player's uuid%} is "Start":
		#				teleport loop-player to location(-1, 128.00, -1, "courses_boat", 0, 0)
		#			else if {gamemode.%loop-player's uuid%} is 3:
		#				teleport loop-player to location(11.878, 132.36820, -0.485, "courses_boat", 54.9, 19)
		#			else if {courses_boat.%loop-player's uuid%} isn't "Start":
		#				teleport loop-player to {courses_boat_location.%loop-player's uuid%}
		#				set slot 0 of loop-player's inventory to oak boat
		#		if the game mode of loop-player is adventure:
		#			if loop-player doesn't have permission "group.spectators":
		#				if {courses_boat.%loop-player's uuid%} is 1:
		#					if block 2 meters below loop-player is white_concrete or black_concrete:
		#						set {courses_boat.%loop-player's uuid%} to "End"
		#						set {gamemode.%loop-player's uuid%} to 3
		#						set {finished.%loop-player's uuid%} to true
		#						clear loop-player's inventory
		#						make console execute command "/hide %loop-player%"
		#						force loop-player to fly
		#						allow fly for loop-player
		#						set {courses_boat_timer_status.%loop-player's uuid%} to false
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the boat race in &b%{courses_boat_timer.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_1})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the boat race in &b%{courses_boat_timer.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_1})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						add {pts_lvl_1} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
		#						add 1 to {finished_players}
		#						remove {remove_pts_lvl_1} from {pts_lvl_1}
		#						set slot 0 of loop-player to compass named "&rTeleport to player"
		#						set slot 1 of loop-player to feather named "&rChange player's fly speed"
		#				else if {courses_boat.%loop-player's uuid%} is "Start":
		#					if block 2 meters below loop-player is iron_block:
		#						set {courses_boat_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_boat.%loop-player's uuid%} to 1
		#						make server execute command "give %loop-player% oak_boat"
		#						if {hide.%loop-player's uuid%} is true:
		#							make console execute command "/hide %loop-player%"
		#	else if {courses} is "pied":
		#		if y-coordinate of loop-player is less than 60:
		#			if {courses_pied.%loop-player's uuid%} is "Start":
		#				teleport loop-player to location(-1, 128.00, -1, "courses_pied", 0, 0)
		#			else if {gamemode.%loop-player's uuid%} is 3:
		#				teleport loop-player to location(11.878, 132.36820, -0.485, "courses_pied", 54.9, 19)
		#			else if {courses_pied.%loop-player's uuid%} isn't "Start":
		#				teleport loop-player to {courses_pied_location.%loop-player's uuid%}
		#		if the game mode of loop-player is adventure:
		#			if loop-player doesn't have permission "group.spectators":
		#				if {courses_pied.%loop-player's uuid%} is 3:
		#					if block 2 meters below loop-player is oxidized_copper:
		#						make server execute command "execute in courses_pied run tp %loop-player% 59.5 133 21 90 0"
		#					if block 2 meters below loop-player is white_concrete or black_concrete:
		#						set {courses_pied.%loop-player's uuid%} to "End"
		#						set {gamemode.%loop-player's uuid%} to 3
		#						set {finished.%loop-player's uuid%} to true
		#						make console execute command "/see %loop-player%"
		#						make server execute command "/hide %loop-player%"
		#						force loop-player to fly
		#						allow fly for loop-player
		#						set {courses_pied_timer_status.%loop-player's uuid%} to false
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the foot race in &b%{courses_pied_timer.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_1})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] you just completed the foot race in &b%{courses_pied_timer.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_1})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						add {pts_lvl_1} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
		#						add 1 to {finished_players}
		#						remove {remove_pts_lvl_1} from {pts_lvl_1}
		#						set slot 0 of loop-player to compass named "&rTeleport to player"
		#						set slot 1 of loop-player to feather named "&rChange player's fly speed"
		#				else if {courses_pied.%loop-player's uuid%} is 2:
		#					if block 2 meters below loop-player is copper_block:
		#						make server execute command "effect give %loop-player% levitation 5 2 true"
		#					if block 2 meters below loop-player is iron_block:
		#						set {courses_pied_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_pied.%loop-player's uuid%} to 3
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 2nd part of the easy path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_5})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the 2nd part of the easy path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_5})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						set {courses_pied_timer_section.%loop-player's uuid%} to 0
		#						add {pts_lvl_5} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_5}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_5}) to {total_points_event.%loop-player's uuid%}
		#						remove {remove_pts_lvl_5} from {pts_lvl_5}
		#						if {hide.%loop-player's uuid%} is false:
		#							make server execute command "/hide %loop-player%"
		#					if block 2 meters below loop-player is netherite_block:
		#						set {courses_pied_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_pied.%loop-player's uuid%} to 3
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 2nd part of the hard path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_3})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the 2nd part of the hard path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_3})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						set {courses_pied_timer_section.%loop-player's uuid%} to 0
		#						add {pts_lvl_3} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_3}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
		#						remove {remove_pts_lvl_3} from {pts_lvl_3}
		#						if {hide.%loop-player's uuid%} is false:
		#							make server execute command "/hide %loop-player%"
		#				else if {courses_pied.%loop-player's uuid%} is 1:
		#					if block 2 meters below loop-player is gold_block:
		#						set {courses_pied_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_pied.%loop-player's uuid%} to 2
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 1st part of the easy path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_4})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the 1st part of the path race in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_4})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						set {courses_pied_timer_section.%loop-player's uuid%} to 0
		#						add {pts_lvl_4} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
		#						remove {remove_pts_lvl_4} from {pts_lvl_4}
		#						if {hide.%loop-player's uuid%} is false:
		#							make server execute command "/hide %loop-player%"
		#					if block 2 meters below loop-player is diamond_block:
		#						set {courses_pied_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_pied.%loop-player's uuid%} to 2
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 1st part of the hard path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_2})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the 1st part of the hard path in &b%{courses_pied_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_2})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						set {courses_pied_timer_section.%loop-player's uuid%} to 0
		#						add {pts_lvl_2} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
		#						remove {remove_pts_lvl_2} from {pts_lvl_2}
		#						if {hide.%loop-player's uuid%} is false:
		#							make server execute command "/hide %loop-player%"
		#				else if {courses_pied.%loop-player's uuid%} is "Start":
		#					if block 2 meters below loop-player is iron_block:
		#						set {courses_pied_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_pied.%loop-player's uuid%} to 1
		#						set {courses_pied_timer_section.%loop-player's uuid%} to 0
		#	else if {courses} is "trident":
		#		if y-coordinate of loop-player is less than 60:
		#			if {courses_trident.%loop-player's uuid%} is "Start":
		#				teleport loop-player to location(-1, 128.00, -1, "courses_trident", 0, 0)
		#				if {hide.%loop-player's uuid%} is false:
		#					make server execute command "/hide %loop-player%"
		#			else if {gamemode.%loop-player's uuid%} is 3:
		#				teleport loop-player to location(11.878, 132.36820, -0.485, "courses_trident", 54.9, 19)
		#				if {hide.%loop-player's uuid%} is false:
		#					make server execute command "/hide %loop-player%"
		#			else if {courses_trident.%loop-player's uuid%} isn't "Start":
		#				teleport loop-player to {courses_trident_location.%loop-player's uuid%}
		#		if the game mode of loop-player is adventure:
		#			if loop-player doesn't have permission "group.spectators":
		#				if {courses_trident.%loop-player's uuid%} is 2:
		#					if block 2 meters below loop-player is white_concrete or black_concrete:
		#						set {courses_trident.%loop-player's uuid%} to "End"
		#						if {hide.%loop-player's uuid%} is false:
		#							make server execute command "/hide %loop-player%"
		#						force loop-player to fly
		#						allow fly for loop-player
		#						set {courses_trident_timer_status.%loop-player's uuid%} to false
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the trident race in &b%{courses_trident_timer.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_1})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the trident race in &b%{courses_trident_timer.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_1})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						add {pts_lvl_1} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
		#						add 1 to {finished_players}
		#						remove {remove_pts_lvl_1} from {pts_lvl_1}
		#						set slot 0 of loop-player to compass named "&rTeleport to player"
		#						set slot 1 of loop-player to feather named "&rChange player's fly speed"
		#				else if {courses_trident.%loop-player's uuid%} is 1:
		#					if block 2 meters below loop-player is gold_block:
		#						set {courses_trident_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_trident.%loop-player's uuid%} to 2
		#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 1st part of the trident race in &b%{courses_trident_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_2})% &r工]"
		#						send "[<##155966>&lTheEvent580&r] You just completed the 1st part of the trident race in &b%{courses_trident_timer_section.%loop-player's uuid%}% &rseconds [&b+%checkPoints({pts_lvl_2})% &r工]" to loop-player
		#						play sound "custom:coins" in voice category with volume 2 to the loop-player
		#						set {courses_pied_timer_section.%loop-player's uuid%} to 0
		#						add {pts_lvl_2} to {points.%loop-player's uuid%}
		#						add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
		#						add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
		#						remove {remove_pts_lvl_2} from {pts_lvl_2}		
		#				else if {courses_pied.%loop-player's uuid%} is "Start":
		#					if block 2 meters below loop-player is iron_block:
		#						set {courses_trident_location.%loop-player's uuid%} to loop-player's location
		#						set {courses_trident.%loop-player's uuid%} to 1
		#						set {courses_trident_timer_section.%loop-player's uuid%} to 0
		#						if {has_trident.%loop-player's uuid%} is false:
		#							make server execute command "give %loop-player% trident{Unbreakable:1b,Enchantments:[{id:riptide,lvl:3}]} 1"
		#							set {has_trident.%loop-player's uuid%} to true

	else if {jeu_condi} is 6: #Survival Games
		loop {sg.wb} times:
			loop {sg.wb} times:
				if {timer-m} > 10:
					set {_x.block} to the loop-value-1 * 10 - ceil({sg.wb}) * 5
					set {_z.block} to the loop-value-2 * 10 - ceil({sg.wb}) * 5
				else:
					set {_x.block} to the loop-value-1 * 5 - ceil({sg.wb}) * 3
					set {_z.block} to the loop-value-2 * 5 - ceil({sg.wb}) * 3.5
				make 10 of dust using dustOption(blue,2) at location({_x.block},{sg.height},{_z.block},"sg4") with force for all players
		if {timer} = 6:
			if {sg.height} > 33.4999999:
				remove (1/15)/10 from {sg.height}
				make console execute command "setsgheight %{sg.height}%"
			loop all players:
				set {_x.block.player} to the x-coordinate of loop-player
				set {_z.block.player} to the z-coordinate of loop-player
				if {alive.%loop-player's uuid%} = false:
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}-1,{sg.height},{_z.block.player}-1,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}-1,{sg.height},{_z.block.player},"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}+1,{sg.height},{_z.block.player},"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}-1,{sg.height},{_z.block.player}+1,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}+1,{sg.height},{_z.block.player}-1,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player},{sg.height},{_z.block.player}-1,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player},{sg.height},{_z.block.player}+1,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}+1,{sg.height},{_z.block.player}+1,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}-2,{sg.height},{_z.block.player},"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player},{sg.height},{_z.block.player}+2,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player},{sg.height},{_z.block.player}-2,"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player}+2,{sg.height},{_z.block.player},"sg4") with force for loop-player
					make 10 of dust using dustOption(lime,1) at location({_x.block.player},{sg.height},{_z.block.player},"sg4") with force for loop-player
				else:
					make 10 of dust using dustOption(red,1) at location({_x.block.player}-1,{sg.height},{_z.block.player}-1,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}-1,{sg.height},{_z.block.player},"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}+1,{sg.height},{_z.block.player},"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}-1,{sg.height},{_z.block.player}+1,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}+1,{sg.height},{_z.block.player}-1,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player},{sg.height},{_z.block.player}-1,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player},{sg.height},{_z.block.player}+1,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}+1,{sg.height},{_z.block.player}+1,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}-2,{sg.height},{_z.block.player},"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player},{sg.height},{_z.block.player}+2,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player},{sg.height},{_z.block.player}-2,"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player}+2,{sg.height},{_z.block.player},"sg4") with force for all players
					make 10 of dust using dustOption(red,1) at location({_x.block.player},{sg.height},{_z.block.player},"sg4") with force for all players

	#	loop all players:
	#		if {timer} is 6:
	#			if {timer-m} is "09":
	#				if {timer-s} is 59:
	#					if {game} is "SG1":
	#						make server execute command "execute in minecraft:sg1 run setblock -1573 64 -641 minecraft:redstone_block"
	#					else if {game} is "SG2":
	#						make server execute command "execute in minecraft:sg2 run setblock 29 33 0 minecraft:redstone_block"
	#						wait 10 ticks
	#						make server execute command "execute in minecraft:sg2 run setblock 29 33 0 minecraft:air"
	#					else if {game} is "SG3":
	#						make server execute command "execute in minecraft:sg3 run setblock -46 26 -13 minecraft:redstone_block"
	#					else if {game} is "SG4":
	#						make server execute command "execute in minecraft:sg4 run setblock 27 37 -3 minecraft:redstone_block"
	#					else if {game} is "SG5":
	#						make server execute command "execute in minecraft:sg5 run setblock 10 67 51 minecraft:redstone_block"
	#					else if {game} is "SG6":
	#						make server execute command "execute in minecraft:sg6 run fill -193 62 -7 -137 62 -63 minecraft:redstone_block"

	#else if {jeu_condi} is 7: #Laby
	#	loop all players:
	#		if the game mode of loop-player is adventure:
	#			if loop-player doesn't have permission "group.spectators":
	#				if {laby_level.%loop-player's uuid%} is 2:
	#					if block 2 meters below loop-player is white_concrete or black_concrete:
	#						set {laby_level.%loop-player's uuid%} to "End"
	#						set {gamemode.%loop-player's uuid%} to 3
	#						set {finished.%loop-player's uuid%} to true
	#						set loop-player's gamemode to spectator
	#						force loop-player to fly
	#						allow fly for loop-player
	#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the &5Labyrinth &r[&5+%checkPoints({pts_lvl_3})% &r工]"
	#						send "[<##155966>&lTheEvent580&r] You just completed the &5Labyrinth &r[&5+%checkPoints({pts_lvl_3})% &r工]" to loop-player
	#						play sound "custom:coins" in voice category with volume 2 to the loop-player
	#						add {pts_lvl_3} to {points.%loop-player's uuid%}
	#						add round({pts_lvl_3}) to {total_points.%loop-player's uuid%}
	#						add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
	#						add 1 to {finished_players}
	#						remove {remove_pts_lvl_3} from {pts_lvl_3}
	#				else if {laby_level.%loop-player's uuid%} is 1:
	#					if block 1 meter below loop-player is gold_block:
	#						set {laby_level.%loop-player's uuid%} to 2
	#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 2nd part of the &5Labyrinth &r[&5+%checkPoints({pts_lvl_2})% &r工]"
	#						send "[<##155966>&lTheEvent580&r] You just completed the 2nd part of the &5Labyrinth &r[&5+%checkPoints({pts_lvl_2})% &r工]" to loop-player
	#						play sound "custom:coins" in voice category with volume 2 to the loop-player
	#						add {pts_lvl_2} to {points.%loop-player's uuid%}
	#						add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
	#						add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
	#						remove {remove_pts_lvl_2} from {pts_lvl_2}
	#				else if {laby_level.%loop-player's uuid%} is "Start":
	#					if block 1 meter below loop-player is iron_block:
	#						set {laby_level.%loop-player's uuid%} to 1
	#						broadcast "[<##155966>&lTheEvent580&r] %loop-player% just completed the 1st part of the &5Labyrinth &r[&5+%checkPoints({pts_lvl_1})% &r工]"
	#						send "[<##155966>&lTheEvent580&r] You just completed the 1st part of the &5Labyrinth &r[&5+%checkPoints({pts_lvl_1})% &r工]" to loop-player
	#						play sound "custom:coins" in voice category with volume 2 to the loop-player
	#						add {pts_lvl_1} to {points.%loop-player's uuid%}
	#						add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
	#						add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
	#						remove {remove_pts_lvl_1} from {pts_lvl_1}
	#			if {gamemode.%loop-player's uuid%} is 3:
	#				if the y-coordinate of loop-player is 120:
	#					teleport loop-player to location(1, 128, 1, "labyrinthe", -90, 0)

	else if {jeu_condi} is 8: #Bow PVP
		loop all players:
			if {invincibility.%loop-player's uuid%} = true:
				if {invincibility.time_left.%loop-player's uuid%} > 0.05:
					remove 0.05 from {invincibility.time_left.%loop-player's uuid%}
				else:
					set {invincibility.%loop-player's uuid%} to false
					#make console execute command "hide %loop-player%"
					set helmet of loop-player to air
					set chestplate of loop-player to air
					set leggings of loop-player to air
					set boots of loop-player to air
			if the y-coordinate of loop-player is smaller than 90:
				if {alive.%loop-player's uuid%} = true:
					kill loop-player
				else:
					respawnBowPVP(loop-player)

	else if {jeu_condi} is 9: #Build Masters
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if {finished.%loop-player's uuid%} is false:
					if {timer_minute.%loop-player's uuid%} >= 0:
						if {build.%loop-player's uuid%} = 1:
							checkBuild1({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 2:
							checkBuild2({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 3:
							checkBuild3({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 4:
							checkBuild4({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 5:
							checkBuild5({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 6:
							checkBuild6({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 7:
							checkBuild7({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 8:
							checkBuild8({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 9:
							checkBuild9({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} = 10:
							checkBuild10({build.location.%loop-player's uuid%})
						if {build.%loop-player's uuid%} is "End":
							allow fly for loop-player
							force loop-player to fly
							set loop-player's gamemode to adventure
							set {finished.%loop-player's uuid%} to true
							set {build.%loop-player's uuid%} to "end"
						set {_x_%loop-player's uuid%} to the x-coordinate of loop-player
						set {_z_%loop-player's uuid%} to the z-coordinate of loop-player
						if {timeout_portal.%loop-player's uuid%} > 0:
							remove 0.05 from {timeout_portal.%loop-player's uuid%}
						if block at location({_x_%loop-player's uuid%}, 128, {_z_%loop-player's uuid%}, "build_masters") is pumpkin:
							if {timeout_portal.%loop-player's uuid%} <= 0:
								if the z-coordinate of loop-player > 3000:
									set {timeout_portal.%loop-player's uuid%} to 5
									set {_concrete_items} to 0
									set {_terracotta_items} to 0
									set {_copper_items} to 0
									loop all items in loop-player's inventory:
										if loop-item is red concrete or orange concrete or yellow concrete or lime concrete or green concrete or cyan concrete or light blue concrete or blue concrete or purple concrete or magenta concrete or pink concrete or brown concrete or black concrete or gray concrete or light gray concrete or white concrete :
											add the amount of loop-item in loop-player's inventory to {_concrete_items}
										if loop-item is red terracotta or orange terracotta or yellow terracotta or lime terracotta or green terracotta or cyan terracotta or light blue terracotta or blue terracotta or purple terracotta or magenta terracotta or pink terracotta or brown terracotta or black terracotta or gray terracotta or light gray terracotta or white terracotta or terracotta:
											add the amount of loop-item in loop-player's inventory to {_terracotta_items}
										if loop-item is waxed copper block or waxed exposed copper block or waxed weathered copper block or waxed oxidized copper block or waxed cut copper block or waxed exposed cut copper block or waxed weathered cut copper block or waxed oxidized cut copper block :
											add the amount of loop-item in loop-player's inventory to {_copper_items}
									set {_total_pay} to {_concrete_items} + {_terracotta_items} * 2 + {_copper_items} * 3
									removeTime({_total_pay}, loop-player)
									if {build.location.%loop-player's uuid%} = 0:
										make server execute command "execute in build_masters run tp %loop-player% 2.5 129 998.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 1:
										make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1019.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 2:
										make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1040.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 3:
										make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1061.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 4:
										make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1082.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 5:
										make server execute command "execute in build_masters run tp %loop-player% 23.5 129 998.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 6:
										make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1019.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 7:
										make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1040.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 8:
										make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1061.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 9:
										make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1082.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 10:
										make server execute command "execute in build_masters run tp %loop-player% 44.5 129 998.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 11:
										make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1019.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 12:
										make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1040.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 13:
										make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1061.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 14:
										make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1082.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 15:
										make server execute command "execute in build_masters run tp %loop-player% 65.5 129 998.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 16:
										make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1019.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 17:
										make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1040.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 18:
										make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1061.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 19:
										make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1082.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 20:
										make server execute command "execute in build_masters run tp %loop-player% 86.5 129 998.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 21:
										make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1019.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 22:
										make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1040.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 23:
										make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1061.00000001 -90 0"
									else if {build.location.%loop-player's uuid%} is 24:
										make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1082.00000001 -90 0"
								else:
									make server execute command "execute in build_masters run tp %loop-player% 6.5 131 5000.5 -90 0"
							else:
								send "[<##155966>&lTheEvent580&r] You need to wait %round({timeout_portal.%loop-player's uuid%})% seconds before going into the portal again" to loop-player
						if the z-coordinate of loop-player > 3000:
							remove speed from loop-player
							apply speed 4 without particles to loop-player for 2 ticks
					else:
						clear loop-player's inventory
						set slot 0 of loop-player to compass named "&rTeleport to player"
						set slot 1 of loop-player to feather named "&rChange player's fly speed"
						set {finished.%loop-player's uuid%} to true
						make console execute command "/hide %loop-player%"
						make console execute command "/see %loop-player%"
						wait 5 ticks
						allow fly for loop-player
						force loop-player to fly
						set loop-player's gamemode to adventure
				else:
					if block at location({_x_%loop-player's uuid%}, 128, {_z_%loop-player's uuid%}, "build_masters") is pumpkin:
						if the z-coordinate of loop-player > 3000:
							make server execute command "execute in minecraft:build_masters run tp %loop-player% -7.53 153.24 1040.13 -90.66 36.09"
					else if block 1 meter under loop-player is pumpkin :
						make server execute command "execute in build_masters run tp %loop-player% 6.5 131 5000.5 -90 0"

every second:
	if {timer} is 1:
		if {timer-m} is 0:
			if {timer-s} is 48:
				currentPlayers()
			if {timer-s} is 24:
				currentSpecs()
			if {timer-s} is 11:
				loop all players:
					send title "Event starting in" with subtitle "&4>     10     <" to loop-player for 3 seconds
			if {timer-s} is 10:
				loop all players:
					send title "Event starting in" with subtitle "&4>     9     <" to loop-player for 3 seconds
			if {timer-s} is 9:
				loop all players:
					send title "Event starting in" with subtitle "&c>    8    <" to loop-player for 3 seconds
			if {timer-s} is 8:
				loop all players:
					send title "Event starting in" with subtitle "&c>    7    <" to loop-player for 3 seconds
			if {timer-s} is 7:
				loop all players:
					send title "Event starting in" with subtitle "&6>   6   <" to loop-player for 3 seconds
			if {timer-s} is 6:
				loop all players:
					send title "Event starting in" with subtitle "&6>   5   <" to loop-player for 3 seconds
			if {timer-s} is 5:
				loop all players:
					send title "Event starting in" with subtitle "&e>  4  <" to loop-player for 3 seconds
			if {timer-s} is 4:
				loop all players:
					send title "Event starting in" with subtitle "&e>  3  <" to loop-player for 3 seconds
			if {timer-s} is 3:
				loop all players:
					send title "Event starting in" with subtitle "&a> 2 <" to loop-player for 3 seconds
			if {timer-s} is 2:
				loop all players:
					send title "Event starting in" with subtitle "&a> 1 <" to loop-player for 3 seconds
					make server execute command "fill 8 247 -8 -8 247 8 redstone_block"
			if {timer-s} is 1:
				loop all players:
					send title "Event starting" with subtitle "&2NOW" to loop-player for 1 second
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStart Countdown&r --> &aShowing games" to loop-player
						set {event_state} to "Showing games"
			if {timer-s} is 0:
				set {timer} to 2
				set {timer-m} to 0
				set {timer-s} to 30
				make server execute command "starttp"
				loop all players:
					if loop-player doesn't have permission "group.spectators":
						set loop-player's game mode to adventure
					clear loop-player's inventory
					make server execute command "/hide %loop-player%"
				broadcast "[<##155966>&lTheEvent580&r] The Minigames are :"
		if {timer-m} is 1:
			if {timer-s} is 12:
				newPlayers()
			if {timer-s} is 0:
				set {timer-m} to 0
				set {timer-s} to 60
		remove 1 from {timer-s}
	if {timer} is 2:
		if {timer-s} is 28:
			broadcast "[<##155966>&lTheEvent580&r] &c&lDropper"
		if {timer-s} is 25:
			broadcast "[<##155966>&lTheEvent580&r] &6&lParkour"
		if {timer-s} is 22:
			broadcast "[<##155966>&lTheEvent580&r] &e&lBingo"
		if {timer-s} is 19:
			broadcast "[<##155966>&lTheEvent580&r] &a&lFind The Button"
		if {timer-s} is 16:
			broadcast "[<##155966>&lTheEvent580&r] &b&lMultilap"
		if {timer-s} is 13:
			broadcast "[<##155966>&lTheEvent580&r] &1&lBuild Masters"
		if {timer-s} is 10:
			broadcast "[<##155966>&lTheEvent580&r] &5&lSurvival Games"
		if {timer-s} is 7:
			broadcast "[<##155966>&lTheEvent580&r] And &d&lBow PVP"
		if {timer-s} is 4:
			make server execute command "starttp"
		if {timer-s} is 0:
			add 1 to {jeu}
			set {timer} to 3
			set {timer-m} to 0
			set {timer-s} to 40
			make server execute command "fill 8 247 -8 -8 247 8 air"
			wait 5 ticks
			make server execute command "fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab"
			make server execute command "fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab"
			make server execute command "fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab"
			make server execute command "fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab"
			make server execute command "fill 8 251 3 -8 251 3 minecraft:air"
			make server execute command "fill 8 251 -3 -8 251 -3 minecraft:air"
			make server execute command "fill -3 251 -8 -3 251 8 minecraft:air"
			make server execute command "fill 3 251 -8 3 251 8 minecraft:air"
			loop all players:
				if {hide.%loop-player's uuid%} = true:
					if loop-player doesn't have permission "group.spectators":
						make console execute command "hide %loop-player%"
				if loop-player has permission "group.spectators":
					force loop-player to fly
					allow fly for loop-player
					make server execute command "/hide %loop-player%"
				if loop-player has permission "theevent580.staff":
					send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eShowing games&r --> &aVoting" to loop-player
					set {event_state} to "Voting"
		remove 1 from {timer-s}
	if {timer} is 3:
		if {timer-s} = 35:
			loop all players:
				if loop-player doesn't have permission "group.specators":
					giveRandomItems(loop-player)
		if {timer-s} is 13:
			loop all players:
				if loop-player has permission "theevent580.staff":
					send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eVoting&r --> &aVotes closed" to loop-player
					set {event_state} to "Votes closed"
				remove 1 of carrot on a stick named "&rBlock a game" from loop-player
				remove 1 of carrot on a stick named "&rYou choose the game" from loop-player
				remove 1 of carrot on a stick named "&rSwap players and spectators" from loop-player
				remove 1 of minecart named "&rGrab a player" from loop-player
				remove 1 of netherite sword named "&rKill a player" from loop-player
				remove 1 of crossbow named "&rKill a player" from loop-player
				clear {ride.%loop-player's uuid%}
		if {timer-s} is 0:
			set {timer} to 4
			set {timer-m} to 0
			set {timer-s} to 10
			loop all players:
				if loop-player has permission "theevent580.staff":
					send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eVotes closed&r --> &aTeleporting to game" to loop-player
					set {event_state} to "Teleporting to game"
			wait 3 seconds
			make server execute command "fill 8 247 -8 -8 247 8 air"
			wait 5 ticks
			make server execute command "fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab"
			make server execute command "fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab"
			make server execute command "fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab"
			make server execute command "fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab"
			make server execute command "fill 8 251 3 -8 251 3 minecraft:air"
			make server execute command "fill 8 251 -3 -8 251 -3 minecraft:air"
			make server execute command "fill -3 251 -8 -3 251 8 minecraft:air"
			make server execute command "fill 3 251 -8 3 251 8 minecraft:air"
		if {timer-s} is 13:
			make server execute command "fill 8 247 -8 -8 247 8 redstone_block"
			if {red} isn't -10000:
				set {red} to 0
			if {orange} isn't -10000:
				set {orange} to 0
			if {yellow} isn't -10000:
				set {yellow} to 0
			if {lime} isn't -10000:
				set {lime} to 0
			if {light_blue} isn't -10000:
				set {light_blue} to 0
			if {blue} isn't -10000:
				set {blue} to 0
			if {purple} isn't -10000:
				set {purple} to 0
			if {pink} isn't -10000:
				set {pink} to 0
			set {white} to 0
			set {light_gray} to 0
		if {timer-s} is 11:
			loop all players:
				if {vote_swap} = false:
					if loop-player doesn't have permission "group.spectators":
						if {alive.%loop-player's uuid%} = true:
							#Vote x1
							if the chestplate of loop-player is not golden chestplate or diamond chestplate: 
								if block 2 meters below loop-player is red_concrete:
									add 1 to {red}
								else if block 2 meters below loop-player is orange_concrete:
									add 1 to {orange}
								else if block 2 meters below loop-player is yellow_concrete:
									add 1 to {yellow}
								else if block 2 meters below loop-player is lime_concrete:
									add 1 to {lime}
								else if block 2 meters below loop-player is light_blue_concrete:
									add 1 to {light_blue}
								else if block 2 meters below loop-player is blue_concrete:
									add 1 to {blue}
								else if block 2 meters below loop-player is purple_concrete:
									add 1 to {purple}
								else if block 2 meters below loop-player is pink_concrete:
									add 1 to {pink}
								else if block 2 meters below loop-player is light_gray_concrete:
									add 1 to {light_gray}
								else:
									add 1 to {white}
							#Vote x2
							if the chestplate of loop-player is golden chestplate: 
								if block 2 meters below loop-player is red_concrete:
									add 2 to {red}
								else if block 2 meters below loop-player is orange_concrete:
									add 2 to {orange}
								else if block 2 meters below loop-player is yellow_concrete:
									add 2 to {yellow}
								else if block 2 meters below loop-player is lime_concrete:
									add 2 to {lime}
								else if block 2 meters below loop-player is light_blue_concrete:
									add 2 to {light_blue}
								else if block 2 meters below loop-player is blue_concrete:
									add 2 to {blue}
								else if block 2 meters below loop-player is purple_concrete:
									add 2 to {purple}
								else if block 2 meters below loop-player is pink_concrete:
									add 2 to {pink}
								else if block 2 meters below loop-player is light_gray_concrete:
									add 2 to {light_gray}
								else:
									add 2 to {white}
							#Vote x3
							if the chestplate of loop-player is diamond chestplate: 
								if block 2 meters below loop-player is red_concrete:
									add 3 to {red}
								else if block 2 meters below loop-player is orange_concrete:
									add 3 to {orange}
								else if block 2 meters below loop-player is yellow_concrete:
									add 3 to {yellow}
								else if block 2 meters below loop-player is lime_concrete:
									add 3 to {lime}
								else if block 2 meters below loop-player is light_blue_concrete:
									add 3 to {light_blue}
								else if block 2 meters below loop-player is blue_concrete:
									add 3 to {blue}
								else if block 2 meters below loop-player is purple_concrete:
									add 3 to {purple}
								else if block 2 meters below loop-player is pink_concrete:
									add 3 to {pink}
								else if block 2 meters below loop-player is light_gray_concrete:
									add 3 to {light_gray}
								else:
									add 3 to {white}
				else:
					if loop-player has permission "group.spectators":
						if block 2 meters below loop-player is red_concrete:
							add 1 to {red}
						else if block 2 meters below loop-player is orange_concrete:
							add 1 to {orange}
						else if block 2 meters below loop-player is yellow_concrete:
							add 1 to {yellow}
						else if block 2 meters below loop-player is lime_concrete:
							add 1 to {lime}
						else if block 2 meters below loop-player is light_blue_concrete:
							add 1 to {light_blue}
						else if block 2 meters below loop-player is blue_concrete:
							add 1 to {blue}
						else if block 2 meters below loop-player is purple_concrete:
							add 1 to {purple}
						else if block 2 meters below loop-player is pink_concrete:
							add 1 to {pink}
						else if block 2 meters below loop-player is light_gray_concrete:
							add 1 to {light_gray}
						else:
							add 1 to {white}
		if {timer-s} = 10:
			clear all players's inventory
			checkBiggest()
			after()
		if {timer-s} is 3:
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {alive.%loop-player's uuid%} = false:
						if {hide.%loop-player's uuid%} = true:
							make console execute command "/hide %loop-player%"
		remove 1 from {timer-s}
	if {timer} is 4:
		if {timer-s} is 5:
			loop all players:
				apply levitation of tier 2 without particles to loop-player for 5.3 seconds
				if {hide.%loop-player's uuid%} = true:
					make console execute command "hide %loop-player%"
		if {timer-s} is 0:
			set {timer} to 5
			set {timer-s} to 30
			set {timer-m} to 2
			if {jeu_nom} is "&c&lDropper":
				make server execute command "dropper"
			else if {jeu_nom} is "&6&lParkour":
				make server execute command "parkour"
			else if {jeu_nom} is "&e&lBingo":
				make server execute command "bingo"
			else if {jeu_nom} is "&a&lFind The Button":
				make server execute command "ftb"
			else if {jeu_nom} is "&b&lMultilap":
				make server execute command "courses"
			else if {jeu_nom} is "&1&lBuild Masters":
				make server execute command "bm"
			else if {jeu_nom} is "&5&lSurvival Games":
				make server execute command "sg"
			else if {jeu_nom} is "&d&lBow PVP":
				make server execute command "bowpvp"
			loop all players:
				clear loop-player's inventory
				if loop-player has permission "theevent580.staff":
					send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eTeleporting to game&r --> &aStarting game" to loop-player
					set {event_state} to "Starting game"
				else:
					set {alive.%loop-player's uuid%} to true
		remove 1 from {timer-s}
	if {timer} is 5:
		if {jeu_condi} != 0:
			if {timer-s} is 30:
				loop all players:
					if loop-player has permission "group.spectators":
						force loop-player to fly
						allow fly for loop-player
		set {scoreboard.pos} to 0
		if {timer-m} = 0:
			if {jeu_nom} is "&c&lDropper":
				set {barrier} to "red"
				if {timer-s} is 35:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &c&lDropper&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to finish the 5 levels in less than 5 minutes."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Finishing a level before other people will give you more points, so try to be the fastest."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] You can get every infos on the website."
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] To get to the next levels, just jump in the water."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] To complete the &c&lDropper&r, do the same on the last level."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &c&lDropper&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &c&lDropper&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &c&lDropper&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					make server execute command "execute in minecraft:dropper run gamerule randomTickSpeed 0"
					make server execute command "execute in minecraft:dropper run fill 14 127 10 5 127 1 air replace barrier"
					broadcast "[<##155966>&lTheEvent580&r] &c&lDropper&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race6" in record category with volume 1 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&cDropper" to loop-player
							set {event_state} to "Game &r&cDropper"
					set {timer} to 6
					set {timer-m} to 4
					set {timer-s} to 60
					set {red} to -10000
			if {jeu_nom} is "&6&lParkour":
				if {timer-s} is 35:
					loop all players:
						if loop-player has permission "group.spectators":
							make console execute command "/see %loop-player%"
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &6&lParkour&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to complete all 24 levels in less than 10 minutes."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Finishing a section will up your modifier, so try to get the most you can !."
					broadcast "[<##155966>&lTheEvent580&r] You can get every infos on the website."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] You willl get invisibility AND NO COLLISIONS."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &6&lParkour&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &6&lParkour&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &6&lParkour&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					make server execute command "execute in parkour run fill 134 132 194 128 129 208 air replace minecraft:barrier"
					broadcast "[<##155966>&lTheEvent580&r] &6&lParkour&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race2" in record category with volume 1 to the loop-player
						make console execute command "/team join nocolisions %loop-player%"
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&6Parkour" to loop-player
							set {event_state} to "Game &r&6Parkour"
					set {timer} to 6
					set {timer-m} to 9
					set {timer-s} to 60
					set {orange} to -10000
			if {jeu_nom} is "&e&lBingo":
				set {barrier} to "yellow"
				if {timer-s} is 35:
					loop all players:
						if loop-player has permission "group.spectators":
							make server execute command "/hide %loop-player%"
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &e&lBingo&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to get every item on your &e&lBingo&r card in less than 20 minutes."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Getting an item before other people will give you more points, so try to be the fastest."
					broadcast "[<##155966>&lTheEvent580&r] You can get every infos on the website."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] You'll spawn with a chainmail armor, an iron sword, an iron axe, an iron shovel & an iron pickaxe, all unbreakable."
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] You can only get 1 bonus, by killing someone (ONLY ONCE), it'll replace your iron sword & pickaxe by a diamond one, also unbreakable."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] You'll also get a 1 minute grace periode to leave and run."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &e&lBingo&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &e&lBingo&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &e&lBingo&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					make server execute command "//world bingo"
					make server execute command "//pos1 -999986,157,-999938"
					make server execute command "//pos2 -999953,150,-999906"
					make server execute command "//walls air"
					make server execute command "//world world"
					make server execute command "execute in minecraft:bingo run gamerule randomTickSpeed 20"
					make server execute command "execute in minecraft:bingo run gamerule doDaylightCycle true"
					broadcast "[<##155966>&lTheEvent580&r] &e&lBingo&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race8" in record category with volume 1 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&eBingo" to loop-player
							set {event_state} to "Game &r&eBingo"
					loop all players:
						if loop-player has permission "group.spectators":
							allow fly for loop-player
							force loop-player to fly
						else:
							set loop-player's gamemode to survival
					set {timer} to 6
					set {timer-m} to 19
					set {timer-s} to 60
					set {yellow} to -10000
					set {damage} to 2
					broadcast "[<##155966>&lTheEvent580&r] Grace periode ends in 1 minute."
			if {jeu_nom} is "&a&lFind The Button":
				if {timer-s} is 35:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &a&lFind The Button&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to press on all 11 buttons in less than 5 minutes."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] WARNING, THERE CAN BE PLOTS WITHOUT ANY BUTTONS !"
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] Pressing a button before other people will give you more points, so try to be the fastest."
					broadcast "[<##155966>&lTheEvent580&r] You can get every infos on the website."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &a&lFind The Button&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &a&lFind The Button&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &a&lFind The Button&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					make server execute command "//world find_the_button"
					make server execute command "//pos1 -4,152,4"
					make server execute command "//pos2 4,147,-4"
					make server execute command "//set air"
					make server execute command "//world world"
					make server execute command "execute in minecraft:find_the_button run gamerule doDaylightCycle true"
					make server execute command "execute in minecraft:find_the_button run time set 0"
					broadcast "[<##155966>&lTheEvent580&r] &a&lFind The Button&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race11" in record category with volume 1 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame Find The Button" to loop-player
							set {event_state} to "Game &r&aFind The Button"
					set {timer} to 6
					set {timer-m} to 12
					set {timer-s} to 31
					set {lime} to -10000
			if {jeu_nom} is "&b&lMultilap":
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &b&lMultilap&r."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] Complete all 3 laps as fast as you can !"
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] Completing a lap before other people will give you more points, so try to be the fastest."
					broadcast "[<##155966>&lTheEvent580&r] You can get every infos on the website."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] &lWARNING, the map will change when the player in 1st place completes a lap."
				if {timer-s} is 5:
					broadcast "[<##155966>&lTheEvent580&r] There are 3 different paths, and will change thoughout the race."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] This &b&lMultilap&r will start in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] This &b&lMultilap&r will start in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] This &b&lMultilap&r will start in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					make server execute command "execute in minecraft:races_lap_3 run fill -3 132 0 3 130 0 air destroy"
					set {race_timer} to true
					loop all players:
						make console execute command "/team leave %loop-player%"
						if {hide.%loop-player's uuid%} is true:
							make console execute command "/hide %loop-player%"
						make console execute command "/team join nocolisions %loop-player%"
						set {race_lap_time.%loop-player's uuid%} to 0
						set {race_total_time.%loop-player's uuid%} to 0
						set {_item} to carrot on a stick
						set {_item.nbt} to nbt compound of {_item}
						add nbt compound of "{display:{Name:'{""text"":""You are on Lap 1"",""italic"""":""false"",""color"":""gold""}'},CustomModelData:27}" to {_item.nbt}
						set slot 40 of loop-player to {_item}
					set {timer-m} to 9
					set {timer-s} to 60
					broadcast "[<##155966>&lTheEvent580&r] &b&lMultilap&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race7" in record category with volume 1 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&bMultilap" to loop-player
							set {event_state} to "Game &r&bMultilap"
					set {timer} to 6
					set {light_blue} to -10000
					set {damage} to 1
					wait 10 seconds
					make console execute command "execute in minecraft:races_lap_3 run fill 6 129 6 -6 134 6 air replace minecraft:red_stained_glass"
			if {jeu_condi} is 6:
				if {timer-s} is 35:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &5&lSurvival Games&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to be the last one standing."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] The 1st blood gives your more points than ay other kills."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] Being alive when someone get killed will give you some points."
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] Being alive for a minute and 30 seconds will also give you points if you survive at least 5 minutes."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] There will be a 1 minute long grace period to loot and run."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &5&lSurvival Games&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &5&lSurvival Games&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &5&lSurvival Games&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
					#if {game} is "SG1":
					#	make server execute command "//world sg1"
					#	make server execute command "//pos1 -1573,64,-641"
					#	make server execute command "//pos2 -1573,64,-641"
					#	make server execute command "//set redstone_block"
					#else if {game} is "SG2":
					#	make server execute command "//world sg2"
					#	make server execute command "//pos1 29,33,0"
					#	make server execute command "//pos2 29,33,0"
					#	make server execute command "//set redstone_block"
					#if {game} is "SG3":
					#	make server execute command "//world sg3"
					#	make server execute command "//pos1 46,26,-13"
					#	make server execute command "//pos2 46,26,-13"
					#	make server execute command "//set redstone_block"
					if {game} is "SG4":
						make server execute command "execute in minecraft:sg4 run setblock 27 37 -3 air"
				if {timer-s} is 0:
					set {finished_players} to 0
					set {sg.height} to 279
					make server execute command "execute in minecraft:sg4 run time set 0"
					broadcast "[<##155966>&lTheEvent580&r] &5&lSurvival Games&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&5Survival Games" to loop-player
							set {event_state} to "Game &r&5Survival Games"
						if loop-player doesn't have permission "group.specators":
							add 1 to {finished_players}
					loop all players:
						if loop-player has permission "group.spectators":
							allow fly for loop-player
							force loop-player to fly
							set {alive.%loop-player's uuid%} to false
						else:
							set loop-player's gamemode to survival
					make console execute command "execute run effect clear @a saturation"
					set {timer} to 6
					set {timer-m} to 19
					set {timer-s} to 59
					set {purple} to -10000
					set {damage} to 2
					broadcast "[<##155966>&lTheEvent580&r] Grace period endinng in 1 minute."
			if {jeu_condi} is 9:
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &1&lBuild Masters&r."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to be the fastest to build the 10 builds before you run out of time !"
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] Once the builds are completed, it will switch automatically."
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] You can get all of the blocks you need in the mall, available with the portal behind you."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] A Concrete block costs 1 second, a Terracotta block costs 2 seconds and a Copper block costs 3 seconds."
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &1&lBuild Masters&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &1&lBuild Masters&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &1&lBuild Masters&r starting in 1."
					set {finished_players} to 0
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					refillAll()
					loop all players:
						if {build.location.%loop-player's uuid%} is 0:
							make server execute command "execute in build_masters run tp %loop-player% 2.5 129 998.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 993"
							make server execute command "execute in minecraft:build_masters run fill 5 128 993 14 128 1002 air"
						else if {build.location.%loop-player's uuid%} is 1:
							make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1019.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1014"
							make server execute command "execute in minecraft:build_masters run fill 5 128 1014 14 128 1023 air"
						else if {build.location.%loop-player's uuid%} is 2:
							make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1040.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1035"
							make server execute command "execute in minecraft:build_masters run fill 5 128 1035 14 128 1044 air"
						else if {build.location.%loop-player's uuid%} is 3:
							make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1061.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1056"
							make server execute command "execute in minecraft:build_masters run fill 5 128 1056 14 128 1065 air"
						else if {build.location.%loop-player's uuid%} is 4:
							make server execute command "execute in build_masters run tp %loop-player% 2.5 129 1082.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1077"
							make server execute command "execute in minecraft:build_masters run fill 5 128 1077 14 128 1086 air"
						else if {build.location.%loop-player's uuid%} is 5:
							make server execute command "execute in build_masters run tp %loop-player% 23.5 129 998.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 993"
							make server execute command "execute in minecraft:build_masters run fill 26 128 993 35 128 1002 air"
						else if {build.location.%loop-player's uuid%} is 6:
							make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1019.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1014"
							make server execute command "execute in minecraft:build_masters run fill 26 128 1014 35 128 1023 air"
						else if {build.location.%loop-player's uuid%} is 7:
							make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1040.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1035"
							make server execute command "execute in minecraft:build_masters run fill 26 128 1035 35 128 1044 air"
						else if {build.location.%loop-player's uuid%} is 8:
							make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1061.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1056"
							make server execute command "execute in minecraft:build_masters run fill 26 128 1056 35 128 1065 air"
						else if {build.location.%loop-player's uuid%} is 9:
							make server execute command "execute in build_masters run tp %loop-player% 23.5 129 1082.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1077"
							make server execute command "execute in minecraft:build_masters run fill 26 128 1077 35 128 1086 air"
						else if {build.location.%loop-player's uuid%} is 10:
							make server execute command "execute in build_masters run tp %loop-player% 44.5 129 998.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 993"
							make server execute command "execute in minecraft:build_masters run fill 47 128 993 56 128 1002 air"
						else if {build.location.%loop-player's uuid%} is 11:
							make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1019.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1014"
							make server execute command "execute in minecraft:build_masters run fill 47 128 1014 56 128 1023 air"
						else if {build.location.%loop-player's uuid%} is 12:
							make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1040.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1035"
							make server execute command "execute in minecraft:build_masters run fill 47 128 1035 56 128 1044 air"
						else if {build.location.%loop-player's uuid%} is 13:
							make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1061.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1056"
							make server execute command "execute in minecraft:build_masters run fill 47 128 1056 56 128 1065 air"
						else if {build.location.%loop-player's uuid%} is 14:
							make server execute command "execute in build_masters run tp %loop-player% 44.5 129 1082.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1077"
							make server execute command "execute in minecraft:build_masters run fill 47 128 1077 56 128 1086 air"
						else if {build.location.%loop-player's uuid%} is 15:
							make server execute command "execute in build_masters run tp %loop-player% 65.5 129 998.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 993"
							make server execute command "execute in minecraft:build_masters run fill 68 128 993 77 128 1002 air"
						else if {build.location.%loop-player's uuid%} is 16:
							make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1019.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1014"
							make server execute command "execute in minecraft:build_masters run fill 68 128 1014 77 128 1023 air"
						else if {build.location.%loop-player's uuid%} is 17:
							make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1040.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1035"
							make server execute command "execute in minecraft:build_masters run fill 68 128 1035 77 128 1044 air"
						else if {build.location.%loop-player's uuid%} is 18:
							make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1061.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1056"
							make server execute command "execute in minecraft:build_masters run fill 68 128 1056 77 128 1065 air"
						else if {build.location.%loop-player's uuid%} is 19:
							make server execute command "execute in build_masters run tp %loop-player% 65.5 129 1082.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1077"
							make server execute command "execute in minecraft:build_masters run fill 68 128 1077 77 128 1086 air"
						else if {build.location.%loop-player's uuid%} is 20:
							make server execute command "execute in build_masters run tp %loop-player% 86.5 129 998.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 993"
							make server execute command "execute in minecraft:build_masters run fill 89 128 993 98 128 1002 air"
						else if {build.location.%loop-player's uuid%} is 21:
							make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1019.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1014"
							make server execute command "execute in minecraft:build_masters run fill 89 128 1014 98 128 1023 air"
						else if {build.location.%loop-player's uuid%} is 22:
							make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1040.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1035"
							make server execute command "execute in minecraft:build_masters run fill 89 128 1035 98 128 1044 air"
						else if {build.location.%loop-player's uuid%} is 23:
							make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1061.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1056"
							make server execute command "execute in minecraft:build_masters run fill 89 128 1056 98 128 1065 air"
						else if {build.location.%loop-player's uuid%} is 24:
							make server execute command "execute in build_masters run tp %loop-player% 86.5 129 1082.00000001"
							make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1077"
							make server execute command "execute in minecraft:build_masters run fill 89 128 1077 98 128 1086 air"
						make console execute command "bossbar set minecraft:mall players @a"
						make console execute command "bossbar set minecraft:mall visible true"
						if loop-player has permission "group.spectators":
							make server execute command "execute in minecraft:build_masters run tp %loop-player% -7.53 153.24 1040.13 -90.66 36.09"
							set loop-player's game mode to adventure
							force loop-player to fly
							allow flight to loop-player
						else:
							give 1 of netherite pickaxe of unbreaking 250 and efficiency 2 named "&1Unbreakable Pickaxe" to loop-player
							set loop-player's game mode to survival
					broadcast "[<##155966>&lTheEvent580&r] &1&lBuild Masters&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race3" in record category with volume 1 to the loop-player
						set {timer_minute.%loop-player's uuid%} to 9
						set {timer_second.%loop-player's uuid%} to 60
						set {timeout_portal.%loop-player's uuid%} to 0
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&1Build Masters" to loop-player
							set {event_state} to "Game &r&1Build Masters"
					set {timer} to 6
					set {timer-m} to 59
					set {timer-s} to 60
					set {blue} to -10000
			if {jeu_nom} is "&5&lLabyrinth":
				if {timer-s} is 35:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &5&lLabyrinth&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to get to the other side of the &5&lLabyrinth&r in less than 5 minutes."
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Completing a section / the &5&lLabyrinth&r before other people will give you more points, so try to be the fastest."
					broadcast "[<##155966>&lTheEvent580&r] You can get every infos on the website."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] To get to the next level, just fint the right path !"
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] To complete &5&lLabyrinth&r, just walk on the black / white concrete blocks."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] &lWarning, it is possible that you need to go down a level to get to a higher one ! &r(You are warned)"
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &5&lLabyrinth&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &5&lLabyrinth&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &5&lLabyrinth&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					make server execute command "execute in minecraft:labyrinthe run fill 4 130 1 3 128 0 air destroy"
					broadcast "[<##155966>&lTheEvent580&r] &5&lLabyrinth&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&5Labyrinth" to loop-player
							set {event_state} to "Game &r&5Labyrith"
					set {timer} to 6
					set {timer-m} to 4
					set {timer-s} to 60
					set {purple} to -10000
			if {jeu_nom} is "&d&lBow PVP":
				if {timer-s} is 35:
					broadcast "[<##155966>&lTheEvent580&r] Welcome to &d&lBow PVP&r."
				if {timer-s} is 30:
					broadcast "[<##155966>&lTheEvent580&r] Your goal is to be the last one alive and kill everyone in less than 10 minutes !"
				if {timer-s} is 25:
					broadcast "[<##155966>&lTheEvent580&r] Everyone will start with 5 hearts and dying will remove you one heart."
				if {timer-s} is 20:
					broadcast "[<##155966>&lTheEvent580&r] But stabbing a player will give you its heart."
				if {timer-s} is 15:
					broadcast "[<##155966>&lTheEvent580&r] You'll start with a infinity bow and a stone sword (Both are unbreakable)."
				if {timer-s} is 10:
					broadcast "[<##155966>&lTheEvent580&r] &lWARNING, YOU CAN DIE FROM THE VOID ! &r(You are warned)"
				if {timer-s} is 3:
					broadcast "[<##155966>&lTheEvent580&r] &d&lBow PVP&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 2:
					broadcast "[<##155966>&lTheEvent580&r] &d&lBow PVP&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 1:
					broadcast "[<##155966>&lTheEvent580&r] &d&lBow PVP&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} is 0:
					loop all players:
						if loop-player has permission "group.spectators":
							teleport loop-player to location(0, 166, 0, world "Bow_PVP")
						else:
							respawnBowPVP(loop-player)
							give 1 of bow of unbreaking 250 and infinity 1 and power 250 named "&dUnbreakable Bow" to loop-player
							give 1 of stone sword of unbreaking 250 and sharpness 250 named "&dUnbreakable Sword" to loop-player
							set slot 8 of loop-player's inventory to arrow
					broadcast "[<##155966>&lTheEvent580&r] &d&lBow PVP&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						play sound "custom:race1" in record category with volume 1 to the loop-player
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eStarting game&r --> &aGame &r&dBow PVP" to loop-player
							set {event_state} to "Game &r&dBow PVP"
					set {timer} to 6
					set {damage} to 4
					set {timer-m} to 9
					set {timer-s} to 60
					set {pink} to -10000
			if {timer-s} is 1:
				loop all players:
					if loop-player has permission "group.spectators":
						set slot 0 of loop-player to compass named "&rTeleport to player"
						set slot 1 of loop-player to feather named "&rChange player's fly speed"
						if {hide.%loop-player's uuid%} = false:
							make console execute command "hide %loop-player%"
				if {jeu_condi} is not 0:
					make server execute command "effect give @a minecraft:night_vision 9999 255 true"
				#if {courses} is "boat":
				#	loop all players:
				#		make console execute command "/see %loop-player%"
				#	loop all players:
				#		if loop-player has permission "group.spectators":
				#			make server execute command "/hide %loop-player%"
				#if {jeu_nom} is "&1&lSurvival Games &e(&r %{map_sg}% / 2&e)&r":
				#	loop all players:
				#		make console execute command "/see %loop-player%"
				#	loop all players:
				#		if loop-player has permission "group.spectators":
				#			make server execute command "/hide %loop-value%"
		else:
			if {timer-s} = 0:
				remove 1 from {timer-m}
				set {timer-s} to 60
		remove 1 from {timer-s}
	if {timer} is 6:
		if {jeu_condi} is not 6 or 8:
			if {finished_players} is smaller than {checking_finished_players}:
				if {jeu_condi} = 9:
					#Build Masters
						#Refills
					if {timer-s} = 30:
						refillAll()
					# Warnings
					loop all players:
						if {timer_second.%loop-player's uuid%} = 0:
							if {timer_minute.%loop-player's uuid%} = 5:
								send title "&e5 minutes left" with subtitle "&eHurry up !" to loop-player
							if {timer_minute.%loop-player's uuid%} = 3:
								send title "&63 minutes left" with subtitle "&6You better finish this build !" to loop-player
							if {timer_minute.%loop-player's uuid%} = 2:
								send title "&c2 minutes left" with subtitle "&cYou're almost out !" to loop-player
							if {timer_minute.%loop-player's uuid%} = 1:
								send title "&41 minute left" with subtitle "&4This is your last chance." to loop-player
				#Sounds
				loop all players:
					if {jeu_condi} = 1: #Dropper
						if {timer-m} = 3:
							if {timer-s} = 37:
								play sound "custom:race6" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 37:
								play sound "custom:race6" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 24:
								play sound "custom:race6" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 11:
								play sound "custom:race6" in record category with volume 1 to the loop-player
					if {jeu_condi} = 2: #Parkour
						if {timer-m} = 8:
							if {timer-s} = 54:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 7:
							if {timer-s} = 48:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 42:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 36:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 30:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 24:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 18:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 12:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 6:
								play sound "custom:race2" in record category with volume 1 to the loop-player
					if {jeu_condi} = 3: #Bingo
						if {timer-m} = 18:
							if {timer-s} = 46:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 17:
							if {timer-s} = 36:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 16:
							if {timer-s} = 22:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 15:
							if {timer-s} = 12:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 13:
							if {timer-s} = 58:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 12:
							if {timer-s} = 48:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 11:
							if {timer-s} = 34:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 10:
							if {timer-s} = 24:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 9:
							if {timer-s} = 10:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 8:
							if {timer-s} = 0:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 46:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 36:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 22:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 12:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 58:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 48:
								play sound "custom:race8" in record category with volume 1 to the loop-player
					if {jeu_condi} = 4: #Find The Button
						if {timer-m} = 11:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 10:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 9:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 8:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 7:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
					if {jeu_condi} = 5: #Multilap
						if {timer-m} = 8:
							if {timer-s} = 56:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 7:
							if {timer-s} = 44:
								play sound "custom:race7" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 30:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 18:
								play sound "custom:race7" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 14:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 2:
								play sound "custom:race7" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 58:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 46:
								play sound "custom:race7" in record category with volume 1 to the loop-player
					if {jeu_condi} = 8: #Bow PVP
						if {timer-m} = 7:
							if {timer-s} = 49:
								play sound "custom:race4" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 40:
								play sound "custom:race1" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 29:
								play sound "custom:race4" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 20:
								play sound "custom:race1" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 19:
								play sound "custom:race4" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 0:
								play sound "custom:race1" in record category with volume 1 to the loop-player
					if {jeu_condi} = 9: #Build Masters
						if {timer-m} = 29:
							if {timer-s} = 40:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 28:
							if {timer-s} = 19:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 27:
							if {timer-s} = 12:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 26:
							if {timer-s} = 1:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 24:
							if {timer-s} = 54:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 23:
							if {timer-s} = 43:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 22:
							if {timer-s} = 36:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 21:
							if {timer-s} = 25:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 20:
							if {timer-s} = 18:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 19:
							if {timer-s} = 07:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 18:
							if {timer-s} = 0:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 16:
							if {timer-s} = 49:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 15:
							if {timer-s} = 42:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 14:
							if {timer-s} = 31:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 13:
							if {timer-s} = 26:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 12:
							if {timer-s} = 15:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 11:
							if {timer-s} = 08:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 09:
							if {timer-s} = 57:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 08:
							if {timer-s} = 50:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 07:
							if {timer-s} = 39:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 06:
							if {timer-s} = 32:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 05:
							if {timer-s} = 21:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 04:
							if {timer-s} = 14:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 03:
							if {timer-s} = 03:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 01:
							if {timer-s} = 54:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 00:
							if {timer-s} = 43:
								play sound "custom:race5" in record category with volume 1 to the loop-player

				#Time and all
				if {timer-s} is 0:
					if {timer-m} is 0:
						force all players to fly
						allow fly for all players
						loop all players:
							play sound "block.respawn_anchor.deplete" in voice category with volume 2 to the loop-player
							allow fly for loop-player
							set {gamemode.%loop-player's uuid%} to 3
							if loop-player has permission "theevent580.staff":
								send "[<##155966>&lTheEvent580&r] Code : 1" to loop-player
						if {jeu_condi} is 1:
							make server execute command "execute in dropper run fill 14 127 10 5 127 1 barrier"
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&cDropper&r --> &aShowing scores" to loop-player
						if {jeu_condi} is 2:
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&6Parkour&r --> &aShowing scores" to loop-player
						if {jeu_condi} is 3:
							make server execute command "//world bingo"
							make server execute command "//pos1 289,64,164"
							make server execute command "//pos2 322,71,132"
							make server execute command "//walls barrier"
							make server execute command "execute in minecraft:bingo run gamerule doDaylightCycle false"
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame Bingo&r --> &aShowing scores" to loop-player
						if {jeu_condi} is 4:
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&aFind The Button&r --> &aShowing scores" to loop-player
						if {jeu_condi} is 5:
							set {race_timer} to false
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&bMultilap&r --> &aShowing scores" to loop-player
							set {jeu_condi} to 0
							set {damage} to 1
						if {jeu_condi} is 7:
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&5Labyrinth&r --> &aShowing scores" to loop-player
						if {jeu_condi} is 9:
							command("execute as @e[type=minecraft:text_display,tag=bm] run data modify entity @s text set value '{""text"":""Plot : Available""}'")
							loop all players:
								if loop-player has permission "theevent580.staff":
									send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&1Build Masters&r --> &aShowing scores" to loop-player
						set {event_state} to "Showing scores"
						if {jeu} is not 6:
							set {timer-m} to 0
							set {timer-s} to 30
							set {timer} to 7
						if {jeu} is 6:
							set {timer-m} to 1
							set {timer-s} to 30
							set {timer} to 10
						set {jeu_condi} to 0
						set {damage} to 1
						set {finished_players} to 0
						make server execute command "clear @a"
					if {timer-m} > 0:
						if {jeu_condi} = 9:
							refillAll()
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
				if {jeu_condi} is 9:
					loop all players:
						if {finished.%loop-player's uuid%} is false:
							if {timer_second.%loop-player's uuid%} = 0:
								remove 1 from {timer_minute.%loop-player's uuid%}
								add 60 to {timer_second.%loop-player's uuid%}
							remove 1 from {timer_second.%loop-player's uuid%}
				remove 1 from {timer-s}
			set {online_players_finished} to 0
			loop all players:
				if {finished.%loop-player's uuid%} is true:
					if loop-player doesn't have permission "group.spectators":
						add 1 to {online_players_finished}
			if {online_players_finished} is {online_players}:
				force all players to fly
				loop all players:
					play sound "block.respawn_anchor.deplete" in voice category with volume 2 to the loop-player
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580&r] Code : 4" to loop-player
				if {jeu_condi} is 9:
					command("execute as @e[type=minecraft:text_display,tag=bm] run data modify entity @s text set value '{""text"":""Plot : Available""}'")
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&1Build Masters&r --> &aShowing scores" to loop-player
				set {event_state} to "Showing scores"
				if {jeu} is not 6:
					set {timer-m} to 0
					set {timer-s} to 30
					set {timer} to 7
				if {jeu} is 6:
					set {timer-m} to 1
					set {timer-s} to 30
					set {timer} to 10
				set {jeu_condi} to 0
				set {damage} to 1
				set {finished_players} to 0
				make server execute command "clear @a"
			else if {finished_players} is {checking_finished_players}:
				force all players to fly
				loop all players:
					play sound "block.respawn_anchor.deplete" in voice category with volume 2 to the loop-player
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580&r] Code : 3" to loop-player
				if {barrier} is "red":
					make server execute command "execute in dropper run fill 14 127 10 5 127 1 barrier"
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&cDropper&r --> &aShowing scores" to loop-player
				if {jeu_condi} is 2:
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&6Parkour&r --> &aShowing scores" to loop-player
				if {barrier} is "yellow":
					make server execute command "//world bingo"
					make server execute command "//pos1 289,64,164"
					make server execute command "//pos2 322,71,132"
					make server execute command "//walls barrier"
					make server execute command "execute in minecraft:bingo run gamerule doDaylightCycle false"
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame Bingo&r --> &aShowing scores" to loop-player
				if {jeu_condi} is 4:
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&aFind The Button&r --> &aShowing scores" to loop-player
				if {jeu_condi} is 5:
					set {race_timer} to false
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&bMultilap&r --> &aShowing scores" to loop-player
					set {jeu_condi} to 0
					set {damage} to 1
				if {jeu_condi} is 7:
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&5Labyrinth&r --> &aShowing scores" to loop-player
				if {jeu_condi} is 9:
					command("execute as @e[type=minecraft:text_display,tag=bm] run data modify entity @s text set value '{""text"":""Plot : Available""}'")
					loop all players:
						if loop-player has permission "theevent580.staff":
							send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&1Build Masters&r --> &aShowing scores" to loop-player
				set {event_state} to "Showing scores"
				if {jeu} is not 6:
					set {timer-m} to 0
					set {timer-s} to 30
					set {timer} to 7
				if {jeu} is 6:
					set {timer-m} to 1
					set {timer-s} to 30
					set {timer} to 10
				set {jeu_condi} to 0
				set {damage} to 1
				set {finished_players} to 0
				make server execute command "clear @a"
		if {jeu_condi} is 6:
			if {finished_players} is bigger than 1:
				if {timer-s} = 1:
					if {timer-m} = 0:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_5}% Survived until the final battle")
								add round({pts_lvl_5}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_5}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for until the final battle" to loop-player
								make console execute command "achivement %loop-player% give FBSG"
				if {timer-s} is 30:
					if {timer-m} is 0:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 19 mins and 30 secs" to loop-player
						if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 3 10"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 6 blocks over 10 seconds. This is the last zone."
					if {timer-m} is 3:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 16 mins and 30 secs" to loop-player
					if {timer-m} is 6:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 13 mins and 30 secs" to loop-player
					if {timer-m} is 7:
						set {sg.wb} to 5
					if {timer-m} is 9:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 10 mins and 30 secs" to loop-player
					if {timer-m} is 12:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 7 mins and 30 secs" to loop-player
					if {timer-m} is 15:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 4 mins and 30 secs" to loop-player
					if {timer-m} is 18:
						loop all players:
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 1 mins and 30 secs" to loop-player
				else if {timer-s} is 0:
					#if {timer-m} is 0:
					#	if {finihsed_players} > 1:
					#		stop trigger
					#	else:
					#		force all players to fly
					#		loop all players:
					#			allow fly for loop-player
					#			set {gamemode.%loop-player's uuid%} to 3
					#			if loop-player has permission "theevent580.staff":
					#				send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&5Survival Games&r --> &aShowing scores" to loop-player
					#				set {event_state} to "Showing scores"
					#		if {jeu} is not 6:
					#			set {timer-m} to 0
					#			set {timer-s} to 30
					#			set {timer} to 7
					#		if {jeu} is 6:
					#			set {timer-m} to 1
					#			set {timer-s} to 30
					#			set {timer} to 10
					#		set {jeu_condi} to 0
					#	set {damage} to 1
					#	make server execute command "clear @a"
					if {timer-m} is 1:
						set {timer-m} to 0
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 3 10"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 3 10"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 9 10"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 10 blocks over 10 seconds. Last shrinking in 30 seconds."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 3 10"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 6 blocks over 10 seconds. This is the last zone."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 3 10"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 3 10"
					if {timer-m} is 2:
						set {timer-m} to 1
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 18 minutes" to loop-player
						if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 19 15"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 32 blocks over 15 seconds. Next shrinking in 1 minute."
					if {timer-m} is 3:
						remove 1 from {timer-m}
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
					if {timer-m} is 4:
						remove 1 from {timer-m}
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
					if {timer-m} is 5:
						remove 1 from {timer-m}
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 15 mins" to loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 9 10"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 9 10"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 41 30"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 52 blocks over 30 seconds. Next shrinking in 3 minutes."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 9 10"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 10 blocks over a minute. Last shrinking in 4 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 9 10"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 9 15"
					if {timer-m} is 6:
						remove 1 from {timer-m}
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
					if {timer-m} is 7:
						set {sg.wb} to 3
						remove 1 from {timer-m}
						set {timer-s} to 60
						if {finished_players} is bigger than {checking_finished_players}:
							loop all players:
								play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
					if {timer-m} is 8:
						remove 1 from {timer-m}
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 12 mins" to loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 19 15"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 19 15"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 93 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 102 blocks over a minute. Next shrinking in 3 minutes."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 19 15"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 30 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 19 15"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 19 30"
					if {timer-m} is 9:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 10:
						remove 1 from {timer-m}
						set {timer-s} to 60
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 49 30"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 49 30"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 195 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 102 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 49 30"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 50 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 49 30"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 59 45"
					if {timer-m} is 11:
						set {sg.wb} to 10
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 9 mins" to loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 12:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 99 60"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 99 60"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 297 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 102 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 99 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 100 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 99 60"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 109 60"
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 13:
						set {sg.wb} to 20
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 14:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 6 mins" to loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 199 60"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 199 60"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 399 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 102 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 199 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 100 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 199 60"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 219 60"
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 15:
						set {sg.wb} to 30
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 16:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 299 60"
						if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 299 60"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 501 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 100 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG4":
							make server execute command "execute in minecraft:sg4 run worldborder set 299 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 100 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 299 60"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 329 60"
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 17:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
							if {alive.%loop-player's uuid%} is true:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								command("gamepoints %loop-player% %{pts_lvl_4}% Survived 1:30")
								add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
								add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
								send "[<##155966>&lTheEvent580&r] You stayed alive for 3 mins" to loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 18:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						if {game} is "SG1":
							make server execute command "execute in minecraft:sg1 run worldborder set 399 60"
						else if {game} is "SG2":
							make server execute command "execute in minecraft:sg2 run worldborder set 399 60"
						else if {game} is "SG3":
							make server execute command "execute in minecraft:sg3 run worldborder set 603 60"
							broadcast "[<##155966>&lTheEvent580&r] Border is shrinking by 100 blocks over a minute. Next shrinking in 2 minutes."
						else if {game} is "SG5":
							make server execute command "execute in minecraft:sg5 run worldborder set 399 60"
						else if {game} is "SG6":
							make server execute command "execute in minecraft:sg6 run worldborder set 439 60"
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 19:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
						if {jeu_condi} is 3:
							set {damage} to 0
						else if {jeu_condi} is 6:
							set {damage} to 3
						broadcast "[<##155966>&lTheEvent580&r] End of the grace period."
				if {timer-s} or {timer-m} > 0:
					remove 1 from {timer-s}
			if {finished_players} < 2:
				force all players to fly
				loop all players:
					play sound "block.respawn_anchor.deplete" in voice category with volume 2 to the loop-player
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580&r] Code : 2" to loop-player
						send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&5Survival Games&r --> &aShowing scores" to loop-player
						set {event_state} to "Showing scores"
				if {jeu} is not 6:
					set {timer-m} to 0
					set {timer-s} to 30
					set {timer} to 7
				if {jeu} is 6:
					set {timer-m} to 1
					set {timer-s} to 30
					set {timer} to 10
				set {jeu_condi} to 0
				set {damage} to 1
				make server execute command "clear @a"
		if {jeu_condi} is 8:
			if {finished_players} is bigger than 1:
				if {timer-s} is 0:
					if {timer-m} is 0:
						force all players to fly
						loop all players:
							allow fly for loop-player
							set {gamemode.%loop-player's uuid%} to 3
							if loop-player has permission "theevent580.staff":
								send "[<##155966>&lTheEvent580&r] Code : 2" to loop-player
								send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&dBow PVP&r --> &aShowing scores" to loop-player
								set {event_state} to "Showing scores"
						if {jeu} is not 6:
							set {timer-m} to 0
							set {timer-s} to 30
							set {timer} to 7
						if {jeu} is 6:
							set {timer-m} to 1
							set {timer-s} to 30
							set {timer} to 10
						set {jeu_condi} to 0
						set {damage} to 1
						set {finished_players} to 0
						make server execute command "clear @a"
					if {timer-m} is 1:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						set {timer-m} to 0
						set {timer-s} to 60
					if {timer-m} is 2:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						set {timer-m} to 1
						set {timer-s} to 60
					if {timer-m} is 3:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 4:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 5:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 6:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 7:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 8:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} is 9:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
				remove 1 from {timer-s}
			else if {finished_players} is 1:
				force all players to fly
				loop all players:
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eGame &r&dBow PVP&r --> &aShowing scores" to loop-player
						set {event_state} to "Showing scores"
				if {jeu} is not 6:
					set {timer-m} to 0
					set {timer-s} to 30
					set {timer} to 7
				if {jeu} is 6:
					set {timer-m} to 1
					set {timer-s} to 30
					set {timer} to 10
				set {jeu_condi} to 0
				set {damage} to 1
				set {finished_players} to 0
				make server execute command "clear @a"
	if {timer} is 7:
		if {jeu_condi} = 9:
			make server execute command "bossbar set minecraft:mall visible false"
		if {timer-s} is 29:
			make console execute command "stopsound @a"
			clear all players's inventory
			loop all players:
				remove invisibility from loop-player
				remove speed from loop-player
				clear {pos.%loop-player's uuid%}
				set {finished.%loop-player's uuid%} to false
				send title "&cGame Over" with subtitle "Check the chat to see your 工" to loop-player for 5 seconds
			clear {pos1}
			clear {pos2}
			clear {pos3}
			clear {show}
			clear {finished::*}
			clear {list_points::*}
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {jeu_nom} = "&6&lParkour":
						set {points_game_covert.%loop-player's uuid%} to round({points_game.%loop-player's uuid%} * {game_multiplier.%loop-player's uuid%})
						set {points_game.%loop-player's uuid%} to {points_game_covert.%loop-player's uuid%}
					add {points_game.%loop-player's uuid%} to {points.%loop-player's uuid%}
					add {points.%loop-player's uuid%} to {list_points::*}
					set {points_string.%loop-player's uuid%} to checkPoints({points.%loop-player's uuid%})
			set {list_points::*} to sorted {list_points::*}
			set {list_points::*} to reversed {list_points::*}
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {list_points::1} is {points.%loop-player's uuid%}:
						set {pos1} to "[<##155966>&lTheEvent580&r] 1st : %loop-player% - %checkPoints({points.%loop-player's uuid%})% 工"
						set {pos.%loop-player's uuid%} to "<##BCD71D>1st"
					if {list_points::2} is {points.%loop-player's uuid%}:
						set {pos2} to "[<##155966>&lTheEvent580&r] 2nd : %loop-player% - %checkPoints({points.%loop-player's uuid%})% 工"
						set {pos.%loop-player's uuid%} to "<##BCD71D>2nd"
					if {list_points::3} is {points.%loop-player's uuid%}:
						set {pos3} to "[<##155966>&lTheEvent580&r] 3rd : %loop-player% - %checkPoints({points.%loop-player's uuid%})% 工"
						set {pos.%loop-player's uuid%} to "<##BCD71D>3rd"
					if {list_points::4} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>4th"
					if {list_points::5} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>5th"
					if {list_points::6} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>6th"
					if {list_points::7} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>7th"
					if {list_points::8} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>8th"
					if {list_points::9} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>9th"
					if {list_points::10} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>10th"
					if {list_points::11} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>11th"
					if {list_points::12} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>12th"
					if {list_points::13} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>13th"
					if {list_points::14} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>14th"
					if {list_points::15} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>15th"
					if {list_points::16} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>16th"
					if {list_points::17} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>17th"
					if {list_points::18} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>18th"
					if {list_points::19} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>19th"
					if {list_points::20} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>20th"
					if {list_points::21} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>21st"
					if {list_points::22} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>22nd"
					if {list_points::23} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>23rd"
					if {list_points::24} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>24th"
					if {list_points::25} is {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<##BCD71D>&l25th"
				else:
					set {pos.%loop-player's uuid%} to "<##BCD71D>Spec"
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					set {show} to {points_game.%loop-player's uuid%}
					loop all players:
						if loop-player-2 has permission "group.spectators":
							send "[<##155966>&lTheEvent580&r] %loop-player-1% had %{show}% 工 this game !" to loop-player-2
							send "[<##155966>&lTheEvent580&r] %loop-player-1% had %{show}% coins this game !" to console

		if {timer-s} is 25:
			broadcast "[<##155966>&lTheEvent580&r] Event Top 3 :"
			make server execute command "updateclassement"
		if {timer-s} is 22:
			loop all players:
				if {list_points::1} is {points.%loop-player's uuid%}:
					play sound "custom:coins" in voice category with volume 2 to the loop-player
				if {list_points::2} is {points.%loop-player's uuid%}:
					play sound "custom:coins" in voice category with volume 2 to the loop-player
				if {list_points::3} is {points.%loop-player's uuid%}:
					play sound "custom:coins" in voice category with volume 2 to the loop-player
			broadcast {pos1}
			broadcast {pos2}
			broadcast {pos3}
			set {scoreboard.pos} to 1
		if {timer-s} is 20:
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					send "[<##155966>&lTheEvent580&r] You had %checkPoints({points_game.%loop-player's uuid%})% 工 this game and have %checkPoints({points.%loop-player's uuid%})% 工 in total !" to loop-player
					play sound "custom:coins" in voice category with volume 2 to the loop-player
					set {alive.%loop-player's uuid%} to true
		if {timer-s} is 15:
			broadcast "[<##155966>&lTheEvent580&r] You placement is visible next to your points count in the middle of the games"
		if {timer-s} is 1:
			if {jeu} is 3:
				set {timer-m} to 5
				set {timer-s} to 60
			else:			
				set {timer-m} to 1
				set {timer-s} to 60
			set {timer} to 8
			set {jeu_condi} to 0
			set {l6} to {jeu_nom}
			set {jeu_nom} to "&rHub"
			loop all players:
				set helmet of loop-player to {flag.%loop-player's uuid%}
				set {gamemode.%loop-player's uuid%} to 2
				set {points_game.%loop-player's uuid%} to 0
				set the game mode of loop-player to adventure
				make loop-player execute command "spawn"
				if loop-player can fly:
					make console execute command "fly %loop-player%"
				clear loop-player's inventory
				if {hide.%loop-player's uuid%} = true:
					make console execute command "hide %loop-player%"
				if loop-player has permission "theevent580.staff":
					send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eShowing scores&r --> &aIntermission" to loop-player
					set {event_state} to "Intermission"
		remove 1 from {timer-s}
	if {timer} is 8:
		if {timer-s} is 0:
			if {timer-m} is 0:
				add 1 to {jeu}
				if {jeu} is 3 or 4:
					set {multiplier} to 1.5
				else if {jeu} is 5 or 6:
					set {multiplier} to 2
				set {timer-s} to 10
				set {timer-m} to 0
				make server execute command "gametp"
				loop all players:
					set loop-player's game mode to adventure
					clear loop-player's inventory
					if loop-player has permission "group.spectators":
						make server execute command "/hide %loop-player%"
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eIntermission&r --> &aOpening votes" to loop-player
						set {event_state} to "Opening votes"
				set {timer} to 9
			if {timer-m} is 1:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				set {timer-m} to 0
				make server execute command "fill 8 253 9 -8 250 -9 air replace minecraft:polished_deepslate"
				make server execute command "fill 8 247 3 -8 247 3 minecraft:redstone_block"
				make server execute command "fill 8 247 -3 -8 247 -3 minecraft:redstone_block"
				make server execute command "fill -3 247 -8 -3 247 8 minecraft:redstone_block"
				make server execute command "fill 3 247 -8 3 247 8 minecraft:redstone_block"
				make server execute command "fill 8 247 3 -8 247 3 minecraft:redstone_block"
				make server execute command "fill 8 247 -3 -8 247 -3 minecraft:redstone_block"
				make server execute command "fill -3 247 -8 -3 247 8 minecraft:redstone_block"
				make server execute command "fill 3 247 -8 3 247 8 minecraft:redstone_block"
			if {timer-m} is 2:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				set {timer-m} to 1
			if {timer-m} is 3:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				remove 1 from {timer-m}
			if {timer-m} is 4:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				remove 1 from {timer-m}
			if {timer-m} is 5:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				remove 1 from {timer-m}
		remove 1 from {timer-s}
	if {timer} is 9:
		if {timer-s} is 5:
			if {jeu} is 3:
				send title "&c&lNew multiplier !" with subtitle "Multiplier went from 1必 to 1.5必" to all players for 3 seconds
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1.5 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 2 to all players
			if {jeu} is 5:
				send title "&c&lNew multiplier !" with subtitle "Multiplier went from 1.5必 to 2必" to all players for 3 seconds
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1.5 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 2 to all players
		if {timer-s} is 0:
			if {timer-m} is 0:
				make server execute command "fill 8 247 -8 -8 247 8 air"
				wait 5 ticks
				make server execute command "fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab"
				make server execute command "fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab"
				make server execute command "fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab"
				make server execute command "fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab"
				make server execute command "fill 8 251 3 -8 251 3 minecraft:air"
				make server execute command "fill 8 251 -3 -8 251 -3 minecraft:air"
				make server execute command "fill -3 251 -8 -3 251 8 minecraft:air"
				make server execute command "fill 3 251 -8 3 251 8 minecraft:air"
				set {timer-s} to 40
				set {timer-m} to 0
				set {timer} to 3
				loop all players:
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eOpening votes&r --> &aVoting" to loop-player
						set {event_state} to "Voting"
		remove 1 from {timer-s}
	if {timer} is 10:
		if {timer-m} is 1:
			if {timer-s} is 15:
				send title "&cGame & Event Over" with subtitle "Check the chat to see your coins" to all players for 5 seconds
				endNPCs()
				loop all players:
					if loop-player doesn't have permission "group.spectators":
						set {show} to {points_game.%loop-value-1's uuid%}
					loop {staff::*}:
						if loop-value-1 is not loop-value-2:
							send "[<##155966>&lTheEvent580&r] %loop-value-1% had %{show}% coins this game !" to loop-value-2
							send "[<##155966>&lTheEvent580&r] %loop-value-1% had %{show}% coins this game !" to console
			loop all players:
				remove invisibility from loop-player
				remove speed from loop-player
		if {timer-m} is 0:
			if {timer-s} is 5:
				if {timer-m} is 0:
					endNPCs()
					make server execute command "tp @a 336.548 -4.1 337.584 153.30 -21.00"
					clear {list_points::*}
					loop all players:
						if loop-player doesn't have permission "group.spectators":
							add {points_game.%loop-player's uuid%} to {points.%loop-player's uuid%}
							add {points.%loop-player's uuid%} to {list_points::*}
							set {points_string.%loop-player's uuid%} to checkPoints({points.%loop-player's uuid%})
					set {list_points::*} to sorted {list_points::*}
					set {list_points::*} to reversed {list_points::*}
		if {timer-s} is 0:
			if {timer-m} is 0:
				loop all players:
					if {list_points::1} is {points.%loop-player's uuid%}:
						make server execute command "npc select 23"
						make server execute command "npc skin %loop-player%"
						make server execute command "hd setLine S1E5W 2 %{color.%loop-player's uuid%}% %loop-player%"
						#make server execute command "execute as @e[type=minecraft:text_display,tag=S1E5-5W] run data modify entity @s text set value '{""text"":""%{color.%loop-player's uuid%}% %loop-player%""}'"
				set {timer} to "Fin"
				loop all players:
					if {list_points::1} is {points.%loop-player's uuid%}:
						make server execute command "npc select 8"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 1 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::2} is {points.%loop-player's uuid%}:
						make server execute command "npc select 9"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 2 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::3} is {points.%loop-player's uuid%}:
						make server execute command "npc select 10"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 3 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::4} is {points.%loop-player's uuid%}:
						make server execute command "npc select 11"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 4 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::5} is {points.%loop-player's uuid%}:
						make server execute command "npc select 12"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 5 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::6} is {points.%loop-player's uuid%}:
						make server execute command "npc select 13"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 6 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::7} is {points.%loop-player's uuid%}:
						make server execute command "npc select 14"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 7 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::8} is {points.%loop-player's uuid%}:
						make server execute command "npc select 15"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 8 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::9} is {points.%loop-player's uuid%}:
						make server execute command "npc select 16"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 9 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
					if {list_points::10} is {points.%loop-player's uuid%}:
						make server execute command "npc select 17"
						make server execute command "npc skin %loop-player%"
						make server execute command "npc rename <##D9D8F1>Top 10 : %{color.%loop-player's uuid%}% %loop-player% &r<##D9D8F1>--> %{points_string.%loop-player's uuid%}% &r工"
			if {timer-m} is 1:
				set {timer-s} to 60
				set {timer-m} to 0
				make all players execute command "spawn"
				loop all players:
					if loop-player has permission "theevent580.staff":
						send "[<##155966>&lTheEvent580 - Admin&r] Event state : &eShowing scores&r --> &aEnd" to loop-player
						set {event_state} to "End"
		remove 1 from {timer-s}
	if {event_timer} is true:
		add 1 to {event_timer_second}
		add 1 to {event_timer_second_total}
		if {event_timer_second} = 60:
			remove 60 from {event_timer_second}
			add 1 to {event_timer_minute}
		if {event_timer_minute} = 60:
			remove 60 from {event_timer_minute}
			add 1 to {event_timer_hour}
		if {event_timer_second_total} = 60:
			remove 60 from {event_timer_second_total}
			add 1 to {event_timer_minute_total}
		if {event_timer_minute_total} = 60:
			remove 60 from {event_timer_minute_total}
			add 1 to {event_timer_hour_total}

every 5 seconds:
	if {timer} is 0 or 1 or 8 or 9 or 10 or "pause" or "Fin":
		randomColor()

every 2 ticks:
	if {timer} = 6:
		if {jeu_condi} = 6:
			loop all players:
				if location of loop-player isn't within world border of world of loop-player:
					if {alive.%loop-player's uuid%} is true:
						damage loop-player by 0.5 heart with fake cause suffocate
				if the y-coordinate of loop-player + 1.7 > {sg.height}:
					damage loop-player by 0.5 heart with fake cause suffocate