every tick:
	reloadTab()
	if {race_timer} = true:
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if {finished.%loop-player's uuid%} = false:
					add 0.05 to {race_lap_time.%loop-player's uuid%}
					add 0.05 to {race_total_time.%loop-player's uuid%}
			reloadTimer()

	if {jeu_condi} = 0:
		if {timer} or {timer_save} != 7 or 6 or 5:
			loop all players:
				if world of loop-player = "world":
					if the y-coordinate of loop-player < 4.5:
						if block at location(x-coordinate of loop-player, -6, z-coordinate of loop-player,  world of loop-player) = structure block:
							make 3 of end_rod at loop-player's location with offset vector(0.1, 0, 0.1) with extra 0.01 
							remove levitation from loop-player
							apply levitation 3 without particles whilst hiding the potion icon to loop-player for 2 tick
					if block 1 meter below loop-player = hay block:
						make loop-player execute command "spawn"
						add 1 to {compl_parcour.%loop-player's uuid%}
						updateParkour()
					if block 0 meter below loop-player = water:
						if loop-player's gamemode = adventure:
							make loop-player execute command "spawn"
					if block 0 or 1 meter below loop-player = dirt path:
						remove speed from loop-player
						apply speed 2 without particles whilst hiding the potion icon to loop-player for 1 second
					if block 1 meter below loop-player = ochre froglight:
						make loop-player execute command "spawn"
					if block 1 meter below loop-player = verdant froglight:
						teleport loop-player to location(193.5,69,-381.5,world "overworld", 0.01,0.01)
					if block 1 meter below loop-player = jigsaw block:
						if helmet of loop-player != air:
							command("pridecolor %loop-player% clear")
							send action bar "Your %name of {flag.%loop-player's uuid%}%&r has been removed" to loop-player
							clear {flag.%loop-player's uuid%}
							clear helmet of loop-player
						if {HubParkour.%loop-player's uuid%} = false:
							command("achivement %loop-player% give HubParkour")
					if block 2 meter under loop-player = powder_snow:
						if {Secret_Base_1.%loop-player's uuid%} = false:
							command("achivement %loop-player% give Secret_Base_1")

	else if {jeu_condi} = 2: #Parkour
		loop all players:
			if y-coordinate of loop-player is less than 100:
				if {parkour.main_level.%loop-player's uuid%} and {parkour.sub_level.%loop-player's uuid%} = 1:
					teleport loop-player to location(131.5, 129.00, 201.5,"parkour", -90, 0)
				else if game mode of loop-player = spectator:
					teleport loop-player to location(131.5, 129.00, 201.5,"parkour", -90, 0)
				else:
					teleport loop-player to {parkour_checkpoint_location.%loop-player's uuid%}
			if the game mode of loop-player = adventure:
				if loop-player doesn't have permission "group.spectators":
					if {finished.%loop-player's uuid%} = false:
						if {parkour.main_level.%loop-player's uuid%} = 4:
							if {parkour.sub_level.%loop-player's uuid%} = 7:
								if the inventory of loop-player contains carrot on a stick:
									clear loop-player's inventory
						if the x-coordinate of loop-player > {parkour.next_level_coord.%loop-player's uuid%}:
							if the y coordinate of loop-player > 128:
								if the z-coordinate of loop-player is between 198 and 204 :
									set {parkour_checkpoint_location.%loop-player's uuid%} to location of loop-player
									add 1 to {parkour.sub_level.%loop-player's uuid%}
									if {parkour.main_level.%loop-player's uuid%} != 4:
										add 16 to {parkour.next_level_coord.%loop-player's uuid%}
									else:
										if {parkour.sub_level.%loop-player's uuid%} != 7:
											add 16 to {parkour.next_level_coord.%loop-player's uuid%}
										else:
											add 32 to {parkour.next_level_coord.%loop-player's uuid%}
									if {parkour.main_level.%loop-player's uuid%} = 1:
										if {parkour.skip_used.%loop-player's uuid%} = false:
											add 0.1 to {game_multiplier.%loop-player's uuid%}
										if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
											send "[&6Parkour&r] &aEasy&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
											if {parkour.sub_level.%loop-player's uuid%} = 7:
												set {parkour.sub_level.%loop-player's uuid%} to 1
												add 1 to {parkour.main_level.%loop-player's uuid%}
												loop all players:
													if loop-player-1 != loop-player-2:
														send "[&6Parkour&r] %loop-player-1% finished all &aEasy&r levels." to loop-player-2
									if {parkour.main_level.%loop-player's uuid%} = 2:
										if {parkour.skip_used.%loop-player's uuid%} = false:
											add 0.2 to {game_multiplier.%loop-player's uuid%}
										if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
											send "[&6Parkour&r] &6Medium&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
											if {parkour.sub_level.%loop-player's uuid%} = 7:
												set {parkour.sub_level.%loop-player's uuid%} to 1
												add 1 to {parkour.main_level.%loop-player's uuid%}
												loop all players:
													if loop-player-1 != loop-player-2:
														send "[&6Parkour&r] %loop-player-1% finished al &6Medium&r levels." to loop-player-2
									if {parkour.main_level.%loop-player's uuid%} = 3:
										if {parkour.skip_used.%loop-player's uuid%} = false:
											add 0.4 to {game_multiplier.%loop-player's uuid%}
										if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
											send "[&6Parkour&r] &cHard&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player
											if {parkour.sub_level.%loop-player's uuid%} = 7:
												set {parkour.sub_level.%loop-player's uuid%} to 1
												add 1 to {parkour.main_level.%loop-player's uuid%}
												loop all players:
													if loop-player-1 != loop-player-2:
														send "[&6Parkour&r] %loop-player-1% finished all &cHard&r levels." to loop-player-2
									if {parkour.main_level.%loop-player's uuid%} = 4:
										if {parkour.sub_level.%loop-player's uuid%} = 8:
											add 1.3 to {game_multiplier.%loop-player's uuid%}
											command("fly %loop-player% true")
											command("see %loop-player-1%")
											set slot 0 of loop-player to compass named "&rTeleport to player"
											set slot 1 of loop-player to feather named "&rChange your fly speed"
											loop all players:
												if loop-player-1 = loop-player-2:
													send "[&6Parkour&r] You fully finished &6Parkour&r ! You get rewarded with %checkPoints({points_game.%loop-player-1's uuid%} * {game_multiplier.%loop-player-1's uuid%})% 工 !" to loop-player-1
												else:
													if {finished.%loop-player-2's uuid%} = true:
														if loop-player-2 doesn't have permission "group.spectators":
															command("gamepoints %loop-player-2% %10*{multiplier}% %loop-player-1% completed &r&6&lParkour&r<#D9D8F1> after you (unmultiplied)")
															send "[&6Parkour&r] %loop-player-1% finished &6Parkour&r after you ! You get rewarded with %checkPoints(10*{multiplier})% 工 (unmultiplied)!" to loop-player-2
														else:
															send "[&6Parkour&r] %loop-player-1% finished all 25 levels of &6Parkour&r !" to loop-player-2
											wait 2 ticks
											set {finished.%loop-player's uuid%} to true
										else:
											if {parkour.sub_level.%loop-player's uuid%} - 1 > 0:
												if {parkour.skip_used.%loop-player's uuid%} = false:
													add 0.75 to {game_multiplier.%loop-player's uuid%}
												send "[&6Parkour&r] &4Extreme&r sub-level completed ! New multiplier : 必%{game_multiplier.%loop-player-1's uuid%}% !" to loop-player

	else if {jeu_condi} = 3: #Bingo
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if {bingo_kill.%loop-player's uuid%} = true:
					set {bingo_kill.%loop-player's uuid%} to 2
					remove 1 of iron sword from loop-player's inventory
					give 1 of diamond sword of unbreaking 250 and sharpness 1 named "&eDiamond sword" to loop-player
					create a gui with virtual chest inventory with 3 rows named "&eUpgrade your pickaxe":
						make gui slot 11 with diamond pickaxe of unbreaking 250 and efficiency 4 and silk touch named "&eSilk touch diamond pickaxe":
							close player's inventory
							remove 1 of iron pickaxe of unbreaking 250 and efficiency 2 and silk touch from player's inventory
							give 1 of diamond pickaxe of unbreaking 250 and efficiency 4 and silk touch named "&eSilk touch diamond pickaxe" to player
						make gui slot 15 with diamond pickaxe of unbreaking 250 and efficiency 4 and fortune 1 named "&eFortune diamond pickaxe":
							close player's inventory
							remove 1 of iron pickaxe of unbreaking 250 and efficiency 2 and fortune 2 from player's inventory
							give 1 of diamond pickaxe of unbreaking 250 and efficiency 4 and fortune 1 named "&eFortune diamond pickaxe" to player
					open the last gui for the loop-player
				loop all items in loop-player's inventory:
						wait 1 tick
						if {bingo_case_1.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_1_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_1_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_1_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_1.%loop-player's uuid%} to {bingo_case_1_completed}
							add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
							remove round(5*{multiplier}) from {pts_lvl_1}
							if {pts_lvl_1} < 0:
								set {pts_lvl_1} to 0
						wait 1 tick
						if {bingo_case_2.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_2_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_2_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_2_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_2.%loop-player's uuid%} to {bingo_case_2_completed}
							add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
							remove round(15*{multiplier}) from {pts_lvl_2}
							if {pts_lvl_2} < 0:
								set {pts_lvl_2} to 0
						wait 1 tick
						if {bingo_case_3.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_3_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_3_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_3_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_3.%loop-player's uuid%} to {bingo_case_3_completed}
							add round({pts_lvl_3}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
							remove round(25*{multiplier}) from {pts_lvl_3}
							if {pts_lvl_3} < 0:
								set {pts_lvl_3} to 0
						wait 1 tick
						if {bingo_case_4.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_4_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_4_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_4_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_4.%loop-player's uuid%} to {bingo_case_4_completed}
							add round({pts_lvl_4}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_4}) to {total_points_event.%loop-player's uuid%}
							remove round(35*{multiplier}) from {pts_lvl_4}
							if {pts_lvl_4} < 0:
								set {pts_lvl_4} to 0
						wait 1 tick
						if {bingo_case_5.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_5_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_5_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_5_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_5.%loop-player's uuid%} to {bingo_case_5_completed}
							add round({pts_lvl_5}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_5}) to {total_points_event.%loop-player's uuid%}
							remove round(45*{multiplier}) from {pts_lvl_5}
							if {pts_lvl_5} < 0:
								set {pts_lvl_5} to 0
						wait 1 tick
						if {bingo_case_6.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_6_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_6_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_6_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_6.%loop-player's uuid%} to {bingo_case_6_completed}
							add round({pts_lvl_6}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_6}) to {total_points_event.%loop-player's uuid%}
							remove round(55*{multiplier}) from {pts_lvl_6}
							if {pts_lvl_6} < 0:
								set {pts_lvl_6} to 0
						wait 1 tick
						if {bingo_case_7.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_7_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_7_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_7_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_7.%loop-player's uuid%} to {bingo_case_7_completed}
							add round({pts_lvl_7}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_7}) to {total_points_event.%loop-player's uuid%}
							remove round(70*{multiplier}) from {pts_lvl_7}
							if {pts_lvl_7} < 0:
								set {pts_lvl_7} to 0
						wait 1 tick
						if {bingo_case_8.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_8_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_8_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_8_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_8.%loop-player's uuid%} to {bingo_case_8_completed}
							add round({pts_lvl_8}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_8}) to {total_points_event.%loop-player's uuid%}
							remove round(85*{multiplier}) from {pts_lvl_8}
							if {pts_lvl_8} < 0:
								set {pts_lvl_8} to 0
						wait 1 tick
						if {bingo_case_9.%loop-player's uuid%} = 0:
							add 1 to {bingo_all_cases}
							add 1 to {bingo_case_9_completed}
							add 1 to {bingo_cases.%loop-player's uuid%}
							if {bingo_case_9_1} = true:
								loop all players:
									if loop-player-1 != loop-player-2:
							else:
								set {bingo_case_9_1} to true
								loop all players:
									if loop-player-1 != loop-player-2:
							play sound "custom:coins" in voice category with volume 2 to the loop-player
							set {bingo_case_9.%loop-player's uuid%} to {bingo_case_9_completed}
							add round({pts_lvl_9}) to {total_points.%loop-player's uuid%}
							add round({pts_lvl_9}) to {total_points_event.%loop-player's uuid%}
							remove round(100*{multiplier}) from {pts_lvl_9}
							if {pts_lvl_9} < 0:
								set {pts_lvl_9} to 0
				if {bingo_cases.%loop-player's uuid%} = 9:
					set {bingo_cases.%loop-player's uuid%} to "All"
					if {bingo_fin} = false:
						set {bingo_fin} to true
						loop all players:
							if loop-player-1 != loop-player-2 :
								send "[&eBingo] &r%{color.%loop-player-1's uuid%}%%loop-player-1%&r is the 1st player to complete &e&lBingo&r." to loop-player-2
					else:
						loop all players:
							if loop-player-1 != loop-player-2 :
								send "[&eBingo] &r%{color.%loop-player-1's uuid%}%%loop-player-1%&r completed &e&lBingo&r." to loop-player-2
					send "[&eBingo] You completed &e&lBingo&r" to loop-player
					set {bingo_fin.%loop-player's uuid%} to true
					command("/see %loop-player%")
					set {finished.%loop-player's uuid%} to true
					command("gamepoints %loop-player% %10*{multiplier}% Completion bonus")
					add 10*{multiplier} to {total_points.%loop-player's uuid%}
					add 10*{multiplier} to {total_points_event.%loop-player's uuid%}
					set loop-player's gamemode to adventure
					clear loop-player's inventory
					set slot 0 of loop-player to compass named "&rTeleport to player"
					set slot 1 of loop-player to feather named "&rChange your fly speed"
					command("/hide %loop-player% true")
					force loop-player to fly
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					add 1 to {finished_players}

	else if {jeu_condi} = 5: #Races
		loop all players:
			if the y coordinate of loop-player < 100:
				if {race_checkpoint.%loop-player's uuid%} = 0:
					teleport loop-player to location(1, 131, 3.5, world("Races_lap_3"),180, 0)
				else:
					teleport loop-player to {race_checkpoint_pos.%loop-player's uuid%}
			if block 2 meter under loop-player = pearlescent froglight:
				remove speed from loop-player
				apply speed 2 without particles to loop-player for 50 ticks
			if block 3 meter under loop-player = coal block:
				if loop-player's inventory doesn't contain trident:
					give 1 of trident of unbreaking 250 and riptide 1 to loop-player
					send title "&7[&a+&7] &aTrident equipped" to loop-player for 1 second
			if the x coordinate of loop-player is between 4 and -4:
				if the y coordinate of loop-player is between 128 and 134:
					if the z coordinate of loop-player is between 1 and 0:
						if {finished.%loop-player's uuid%} = false:
							if {race_checkpoint.%loop-player's uuid%} >= 2:
								play sound "custom:coins" in voice category with volume 2 to the loop-player
								if {race_lap.%loop-player's uuid%} = 3:
									if {race_lap_3_finished} = false:
										set {race_lap_3_finished} to true
										set {race_lap} to "All"
										command("execute in minecraft:races_lap_3 run fill -10 130 -43 -12 136 -43 air replace stone")
										command("execute in minecraft:races_lap_3 run fill -16 130 -43 -18 136 -43 air replace smooth_basalt")
									set {gamemode.%loop-player's uuid%} to 3
									set {finished.%loop-player's uuid%} to true
									clear loop-player's inventory
									command("/hide %loop-player% true")
									force loop-player to fly
									allow fly for loop-player
									broadcast "[&bMultilap&r] %loop-player% just completed the race in &b%minuteSecondTicks({race_total_time.%loop-player's uuid%})%"
									send "[&bMultilap&r] You just completed the race in &b%minuteSecondTicks({race_total_time.%loop-player's uuid%})%" to loop-player
									command("gamepoints %loop-player% %{pts_lvl_3}% Completed &r&b&lMultilap")
									add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
									add round({pts_lvl_3}) to {total_points_event.%loop-player's uuid%}
									add 1 to {finished_players}
									remove round(80*{multiplier}) from {pts_lvl_3}
									set slot 0 of loop-player to compass named "&rTeleport to player"
									set slot 1 of loop-player to feather named "&rChange your fly speed"
								else:
									if {race_lap.%loop-player's uuid%} = 1:
										if {race_lap_1_finished} = false:
											set {race_lap_1_finished} to true
											set {race_lap} to 2
											command("execute in minecraft:races_lap_3 run fill -10 130 -43 -12 136 -43 stone replace air")
											command("execute in minecraft:races_lap_3 run fill -16 130 -43 -18 136 -43 air replace smooth_basalt")
										send "[&bMultilap&r] You just completed the 1st lap of the race in &b%minuteSecondTicks({race_lap_time.%loop-player's uuid%})%" to loop-player
										command("gamepoints %loop-player% %{pts_lvl_1}% Completed Lap 1")
										add round({pts_lvl_1}) to {total_points.%loop-player's uuid%}
										add round({pts_lvl_1}) to {total_points_event.%loop-player's uuid%}
										remove round(40*{multiplier}) from {pts_lvl_1}
										set {_item} to carrot on a stick
										apply custom model data to {_item}:
											strings: "lap_2_text"
										set the name of {_item} to "&r&6You're on Lap 2"
										set slot 40 of loop-player to {_item}
									if {race_lap.%loop-player's uuid%} = 2:
										if {race_lap_2_finished} = false:
											set {race_lap_2_finished} to true
											set {race_lap} to 3
											command("execute in minecraft:races_lap_3 run fill -16 130 -43 -18 136 -43 smooth_basalt replace air")
											command("execute in minecraft:races_lap_3 run fill -4 130 -43 -6 136 -43 air replace blackstone")
											command("execute in minecraft:races_lap_3 run setblock 44 131 -20 minecraft:redstone_block")
										send "[&bMultilap&r] You just completed the 2nd lap of the race in &b%minuteSecondTicks({race_lap_time.%loop-player's uuid%})%" to loop-player
										command("gamepoints %loop-player% %{pts_lvl_2}% Completed Lap 2")
										add round({pts_lvl_2}) to {total_points.%loop-player's uuid%}
										add round({pts_lvl_2}) to {total_points_event.%loop-player's uuid%}
										remove round(60*{multiplier}) from {pts_lvl_2}
										set {_item} to carrot on a stick
										apply custom model data to {_item}:
											strings: "lap_3_text"
										set the name of {_item} to "&r&cYou're on Lap 3"
										set slot 40 of loop-player to {_item}
									add 1 to {race_lap.%loop-player's uuid%}
									send title "&7[&bLap&7] &bEntered Lap %{race_lap.%loop-player's uuid%}%" to loop-player for 1 second
									set {race_lap_time.%loop-player's uuid%} to 0
						set {race_checkpoint.%loop-player's uuid%} to 0
			if the x coordinate of loop-player is between 22 and 24:
				if the y coordinate of loop-player is between 155 and 160:
					if the z coordinate of loop-player is between -51 and -42:
						if {race_checkpoint.%loop-player's uuid%} = 1:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
			if the x coordinate of loop-player is between 28 and 31:
				if the y coordinate of loop-player is between 139 and 145:
					if the z coordinate of loop-player is between -7 and -16:
						if {race_boat.%loop-player's uuid%} = true:
							send title "&7[&c-&7] &cBoat removed" to loop-player for 1 second
							if {in_vehicle.%loop-player's uuid%} = true:
								command("execute in minecraft:races_lap_3 at %loop-player% run kill @e[type=minecraft:chest_boat,limit=1,sort=nearest]")
							remove 5 of oak boat with chest from loop-player
							set {race_boat.%loop-player's uuid%} to false
			if the x coordinate of loop-player is between 26 and 27:
				if the y coordinate of loop-player is between 155 and 160:
					if the z coordinate of loop-player is between -51 and -42:
						if {race_boat.%loop-player's uuid%} = false:
							send title "&7[&a+&7] &aBoat equipped" to loop-player for 1 second
							give 1 of oak boat with chest to loop-player
							set {race_boat.%loop-player's uuid%} to true
			if the x coordinate of loop-player is between -5 and -4:
				if the y coordinate of loop-player is between 130 and 135:
					if the z coordinate of loop-player is between 13 and 18:
						if loop-player's inventory contain elytra:
							send title "&7[&c-&7] &cElytra removed" to loop-player for 1 second
							remove 1 of elytra from loop-player
			if the x coordinate of loop-player is between -15 and -6:
				if the y coordinate of loop-player is between 129 and 134:
					if the z coordinate of loop-player is between -34 and -36:
						if {race_checkpoint.%loop-player's uuid%} = 0:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							add 1 to {race_checkpoint.%loop-player's uuid%}
							if {finished.%loop-player's uuid%} = false:
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
			if the x coordinate of loop-player is between -55 and -60:
				if the y coordinate of loop-player is between 139 and 144:
					if the z coordinate of loop-player is between -27 and -26:
						if loop-player's inventory doesn't contain elytra:
							set chestplate of loop-player to elytra of unbreaking 250
							send title "&7[&a+&7] &aElytra equipped" to loop-player for 1 second
					if the z coordinate of loop-player is between -34 and -32:
						if {race_checkpoint.%loop-player's uuid%} = 1:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
			if the x coordinate of loop-player is between 0 and 20:
				if the y coordinate of loop-player is between 138 and 200:
					if the z coordinate of loop-player is between -32 and -30:
						if {race_checkpoint.%loop-player's uuid%} = 2:
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
				if the y coordinate of loop-player is between 126 and 130:
					if the z coordinate of loop-player is between -89 and -87:
						if {race_checkpoint.%loop-player's uuid%} = 1:
							set {race_checkpoint_pos.%loop-player's uuid%} to position of loop-player
							if {finished.%loop-player's uuid%} = false:
								add 1 to {race_checkpoint.%loop-player's uuid%}
								send title "&7[&bCP&7] &bCheckpoint %{race_checkpoint.%loop-player's uuid%}% passed" to loop-player for 1 second
					if the z coordinate of loop-player is between -90 and -89:
						if loop-player's inventory contain trident:
							send title "&7[&c-&7] &cTrident removed" to loop-player for 0.1 second
							remove 1 of trident from loop-player
					if the z coordinate of loop-player is between -88 and -87:
						if loop-player's inventory doesn't contain elytra:
							set chestplate of loop-player to elytra of unbreaking 250
							send title "&7[&a+&7] &aElytra equipped" to loop-player for 1 second
				if the y coordinate of loop-player > 138:
					if the z coordinate of loop-player is between -39 and -38:
						if loop-player's inventory contain elytra:
							send title "&7[&c-&7] &cElytra removed" to loop-player for 1 second
							remove 1 of elytra from loop-player
			if block 1.3 meter under loop-player = structure block:
				push loop-player up at speed 1
				push loop-player forward at speed 0.6
			if block 1 meter under loop-player = command block:
				remove jump boost from loop-player
				apply jump boost 8.7 without particles to loop-player for 2 ticks

	else if {jeu_condi} = 8: #Bow PVP
		loop all players:
			if {invincibility.%loop-player's uuid%} = true:
				if {invincibility.time_left.%loop-player's uuid%} > 0.05:
					remove 0.05 from {invincibility.time_left.%loop-player's uuid%}
				else:
					set {invincibility.%loop-player's uuid%} to false
					#command("hide %loop-player%"
					set helmet of loop-player to air
					set chestplate of loop-player to air
					set leggings of loop-player to air
					set boots of loop-player to air
			if the y-coordinate of loop-player < 90:
				if {alive.%loop-player's uuid%} = true:
					kill loop-player
				else:
					respawnBowPVP(loop-player)

	else if {jeu_condi} = 9: #Build Masters
		if {timer} = 6:
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {finished.%loop-player's uuid%} = false:
						if {check_block.%loop-player's uuid%} is false:
							if the z-coordinate of loop-player > 3000:
								set {_concrete_items} to 0
								set {_terracotta_items} to 0
								set {_copper_items} to 0
								loop all items in loop-player's inventory:
									if loop-item = red concrete or orange concrete or yellow concrete or lime concrete or green concrete or cyan concrete or light blue concrete or blue concrete or purple concrete or magenta concrete or pink concrete or brown concrete or black concrete or gray concrete or light gray concrete or white concrete :
										add the amount of loop-item in loop-player's inventory to {_concrete_items}
									if loop-item = red terracotta or orange terracotta or yellow terracotta or lime terracotta or green terracotta or cyan terracotta or light blue terracotta or blue terracotta or purple terracotta or magenta terracotta or pink terracotta or brown terracotta or black terracotta or gray terracotta or light gray terracotta or white terracotta or terracotta:
										add the amount of loop-item in loop-player's inventory to {_terracotta_items}
									if loop-item = waxed copper block or waxed exposed copper block or waxed weathered copper block or waxed oxidized copper block or waxed cut copper block or waxed exposed cut copper block or waxed weathered cut copper block or waxed oxidized cut copper block :
										add the amount of loop-item in loop-player's inventory to {_copper_items}
								set {_total_pay} to {_concrete_items} + {_terracotta_items} * 2 + {_copper_items} * 3
								send action bar "&9Total price : %minuteSecond({_total_pay})%" to loop-player
						if {timer_minute.%loop-player's uuid%} >= 0:
							if {build.%loop-player's uuid%} = 1:
								checkBuild1({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 2:
								checkBuild2({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 3:
								checkBuild3({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 4:
								checkBuild4({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 5:
								checkBuild5({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 6:
								checkBuild6({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 7:
								checkBuild7({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 8:
								checkBuild8({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 9:
								checkBuild9({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = 10:
								checkBuild10({build.location.%loop-player's uuid%})
							if {build.%loop-player's uuid%} = "End":
								allow fly for loop-player
								force loop-player to fly
								set loop-player's gamemode to adventure
								add loop-player to {finished::*}
								set {finished.%loop-player's uuid%} to true
								set {build.%loop-player's uuid%} to "end"
							set {_x_%loop-player's uuid%} to the x-coordinate of loop-player
							set {_z_%loop-player's uuid%} to the z-coordinate of loop-player
							if {timeout_portal.%loop-player's uuid%} > 0:
								remove 0.05 from {timeout_portal.%loop-player's uuid%}
							if block at location({_x_%loop-player's uuid%}, 128, {_z_%loop-player's uuid%}, "build_masters") = pumpkin:
								if {timeout_portal.%loop-player's uuid%} <= 0:
									if the z-coordinate of loop-player > 3000:
										set {timeout_portal.%loop-player's uuid%} to 5
										set {_concrete_items} to 0
										set {_terracotta_items} to 0
										set {_copper_items} to 0
										loop all items in loop-player's inventory:
											if loop-item = red concrete or orange concrete or yellow concrete or lime concrete or green concrete or cyan concrete or light blue concrete or blue concrete or purple concrete or magenta concrete or pink concrete or brown concrete or black concrete or gray concrete or light gray concrete or white concrete :
												add the amount of loop-item in loop-player's inventory to {_concrete_items}
											if loop-item = red terracotta or orange terracotta or yellow terracotta or lime terracotta or green terracotta or cyan terracotta or light blue terracotta or blue terracotta or purple terracotta or magenta terracotta or pink terracotta or brown terracotta or black terracotta or gray terracotta or light gray terracotta or white terracotta or terracotta:
												add the amount of loop-item in loop-player's inventory to {_terracotta_items}
											if loop-item = waxed copper block or waxed exposed copper block or waxed weathered copper block or waxed oxidized copper block or waxed cut copper block or waxed exposed cut copper block or waxed weathered cut copper block or waxed oxidized cut copper block :
												add the amount of loop-item in loop-player's inventory to {_copper_items}
										set {_total_pay} to {_concrete_items} + {_terracotta_items} * 2 + {_copper_items} * 3
										removeTime({_total_pay}, loop-player)
										if {build.location.%loop-player's uuid%} = 0:
											command("execute in build_masters run tp %loop-player% 2.5 129 998.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 1:
											command("execute in build_masters run tp %loop-player% 2.5 129 1019.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 2:
											command("execute in build_masters run tp %loop-player% 2.5 129 1040.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 3:
											command("execute in build_masters run tp %loop-player% 2.5 129 1061.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 4:
											command("execute in build_masters run tp %loop-player% 2.5 129 1082.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 5:
											command("execute in build_masters run tp %loop-player% 23.5 129 998.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 6:
											command("execute in build_masters run tp %loop-player% 23.5 129 1019.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 7:
											command("execute in build_masters run tp %loop-player% 23.5 129 1040.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 8:
											command("execute in build_masters run tp %loop-player% 23.5 129 1061.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 9:
											command("execute in build_masters run tp %loop-player% 23.5 129 1082.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 10:
											command("execute in build_masters run tp %loop-player% 44.5 129 998.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 11:
											command("execute in build_masters run tp %loop-player% 44.5 129 1019.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 12:
											command("execute in build_masters run tp %loop-player% 44.5 129 1040.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 13:
											command("execute in build_masters run tp %loop-player% 44.5 129 1061.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 14:
											command("execute in build_masters run tp %loop-player% 44.5 129 1082.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 15:
											command("execute in build_masters run tp %loop-player% 65.5 129 998.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 16:
											command("execute in build_masters run tp %loop-player% 65.5 129 1019.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 17:
											command("execute in build_masters run tp %loop-player% 65.5 129 1040.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 18:
											command("execute in build_masters run tp %loop-player% 65.5 129 1061.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 19:
											command("execute in build_masters run tp %loop-player% 65.5 129 1082.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 20:
											command("execute in build_masters run tp %loop-player% 86.5 129 998.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 21:
											command("execute in build_masters run tp %loop-player% 86.5 129 1019.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 22:
											command("execute in build_masters run tp %loop-player% 86.5 129 1040.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 23:
											command("execute in build_masters run tp %loop-player% 86.5 129 1061.00000001 -90 0")
										else if {build.location.%loop-player's uuid%} = 24:
											command("execute in build_masters run tp %loop-player% 86.5 129 1082.00000001 -90 0")
									else:
										command("execute in build_masters run tp %loop-player% 6.5 131 5000.5 -90 0")
								else:
									send action bar "You need to wait %round({timeout_portal.%loop-player's uuid%})% seconds before going into the portal again" to loop-player
							if the z-coordinate of loop-player > 3000:
								remove speed from loop-player
								apply speed 4 without particles whilst hiding the potion icon to loop-player for 2 ticks
						else:
							clear loop-player's inventory
							set slot 0 of loop-player to compass named "&rTeleport to player"
							set slot 1 of loop-player to feather named "&rChange your fly speed"
							set {finished.%loop-player's uuid%} to true
							add loop-player to {finished::*}
							command("/hide %loop-player% true")
							command("/see %loop-player%")
							wait 5 ticks
							command("fly %loop-player% true")
							set loop-player's gamemode to adventure
					else:
						if block at location({_x_%loop-player's uuid%}, 128, {_z_%loop-player's uuid%}, "build_masters") = pumpkin:
							if the z-coordinate of loop-player > 3000:
								command("execute in minecraft:build_masters run tp %loop-player% -7.0 153.5 1040.0 -90 35")
						else if block 1 meter under loop-player = pumpkin :
							command("execute in build_masters run tp %loop-player% 6.5 131 5000.5 -90 0")

every second:
	if {timer} = 1:
		if {timer-m} = 2:
			if {timer-s} = 30:
				newPlayers()
			if {timer-s} = 0:
				set {timer-m} to 1
				set {timer-s} to 60
		if {timer-m} = 1:
			if {timer-s} = 45:
				currentPlayers()
			if {timer-s} = 30:
				play sound "custom:intro" in voice category with volume 1 to all players
			if {timer-s} = 0:
				currentSpecs()
				set {timer-m} to 0
				set {timer-s} to 60
		if {timer-m} = 0:
			if {timer-s} = 11:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&4>     10     <" to loop-player for 3 seconds with fadein 0.5 second and fadeout 0 second
			if {timer-s} = 10:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&4>     9     <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 9:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&c>    8    <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 8:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&c>    7    <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 7:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&6>   6   <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 6:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&6>   5   <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 5:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&e>  4  <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 4:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&e>  3  <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 3:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&a> 2 <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
			if {timer-s} = 2:
				loop all players:
					send title "<#f0f01c>Event starting in" with subtitle "&a> 1 <" to loop-player for 3 seconds with fadein 0 second and fadeout 0 second
					command("fill 8 247 -8 -8 247 8 redstone_block")
			if {timer-s} = 1:
				loop all players:
					send title "<#f0f01c>Event starting" with subtitle "&2NOW" to loop-player for 0.5 second with fadein 0 second and fadeout 0.5 second
					if loop-player has permission "theevent580.staff":
						if {debug.%loop-player's uuid%} = true:
							send "[&4Admin&r] Event state : &eStart Countdown&r --> &aShowing games" to loop-player
				set {event_state} to "Showing games"
			if {timer-s} = 0:
				set {timer} to 2
				set {timer-m} to 0
				set {timer-s} to 30
				bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
				command("starttp")
				loop all players:
					if loop-player doesn't have permission "group.spectators":
						set loop-player's game mode to adventure
					clear loop-player's inventory
					command("/hide %loop-player% true")
				broadcast "[<#155966>&lDecision Crysyal&r] This Episode's minigames are :"
				send title "This Episode's minigames are :" with subtitle " " to all players for 5 seconds with fadein 0.5 second and fadeout 0 second
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 2:
		if {timer-s} = 28:
			broadcast "[<#155966>&lDecision Crysyal&r] <#f0f064> &c&lTrials"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &c&lTrials" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 25:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] <#f0f064> &6&lParkour"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &6&lParkour" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 22:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] <#f0f064> &e&lBingo"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &e&lBingo" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 19:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] <#f0f064> &a&lTag"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &a&lTag" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 16:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] <#f0f064> &b&lMultilap"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &b&lMultilap" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 13:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] <#f0f064> &9&lBuild Masters"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &9&lBuild Masters" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 10:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] <#f0f064> &5&lArms Race"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &5&lArms Race" to all players for 5 seconds with fadein 0 second and fadeout 0 second
		if {timer-s} = 7:
			broadcast "%nl%[<#155966>&lDecision Crysyal&r] and <#f0f064> &d&lBow PVP"
			send title "This Episode's minigames are :" with subtitle "<#f0f064> &d&lBow PVP" to all players for 5 seconds with fadein 0 second and fadeout 1 second
		if {timer-s} = 4:
			command("starttp")
		if {timer-s} = 0:
			add 1 to {jeu}
			set {timer} to 3
			set {timer-m} to 0
			set {timer-s} to 40
			bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
			command("fill 8 247 -8 -8 247 8 air")
			wait 5 ticks
			command("fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab")
			command("fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab")
			command("fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab")
			command("fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab")
			command("fill 8 251 3 -8 251 3 minecraft:air")
			command("fill 8 251 -3 -8 251 -3 minecraft:air")
			command("fill -3 251 -8 -3 251 8 minecraft:air")
			command("fill 3 251 -8 3 251 8 minecraft:air")
			loop all players:
				if {hide.%loop-player's uuid%} = true:
					if loop-player doesn't have permission "group.spectators":
						command("hide %loop-player% false")
				if loop-player has permission "group.spectators":
					force loop-player to fly
					allow fly for loop-player
					command("/hide %loop-player% true")
				if loop-player has permission "theevent580.staff":
					if {debug.%loop-player's uuid%} = true:
						send "[&4Admin&r] Event state : &eShowing games&r --> &aVoting" to loop-player
			set {event_state} to "Voting"
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 3:
		if {timer-s} = 35:
			loop all players:
				if loop-player doesn't have permission "group.specators":
					giveRandomItems(loop-player)
		if {timer-s} = 13:
			loop all players:
				if loop-player has permission "theevent580.staff":
					if {debug.%loop-player's uuid%} = true:
						send "[&4Admin&r] Event state : &eVoting&r --> &aVotes closed" to loop-player
				remove 1 of carrot on a stick named "&rBlock a game" from loop-player
				remove 1 of carrot on a stick named "&rYou choose the game" from loop-player
				remove 1 of carrot on a stick named "&rSwap players and spectators" from loop-player
				remove 1 of minecart named "&rGrab a player" from loop-player
				remove 1 of netherite sword named "&rKill a player" from loop-player
				remove 1 of crossbow named "&rKill a player" from loop-player
				remove 1 of fox spawn egg named "&rSpawn a Fox" from loop-player
				clear {ride.%loop-player's uuid%}
			set {event_state} to "Votes closed"
		if {timer-s} = 0:
			set {timer} to 4
			set {timer-m} to 0
			set {timer-s} to 10
			bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
			loop all players:
				if loop-player has permission "theevent580.staff":
					if {debug.%loop-player's uuid%} = true:
						send "[&4Admin&r] Event state : &eVotes closed&r --> &aTeleporting to game" to loop-player
			set {event_state} to "Teleporting to game"
			wait 3 seconds
			command("fill 8 247 -8 -8 247 8 air")
			wait 5 ticks
			command("fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab")
			command("fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab")
			command("fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab")
			command("fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab")
			command("fill 8 251 3 -8 251 3 minecraft:air")
			command("fill 8 251 -3 -8 251 -3 minecraft:air")
			command("fill -3 251 -8 -3 251 8 minecraft:air")
			command("fill 3 251 -8 3 251 8 minecraft:air")
		if {timer-s} = 13:
			command("fill 8 247 -8 -8 247 8 redstone_block")
			loop all players:
				clear {ride.%loop-player's uuid%}
			if {red} isn't -10000:
				set {red} to 0
			if {orange} isn't -10000:
				set {orange} to 0
			if {yellow} isn't -10000:
				set {yellow} to 0
			if {lime} isn't -10000:
				set {lime} to 0
			if {light_blue} isn't -10000:
				set {light_blue} to 0
			if {blue} isn't -10000:
				set {blue} to 0
			if {purple} isn't -10000:
				set {purple} to 0
			if {pink} isn't -10000:
				set {pink} to 0
			set {white} to 0
			set {light_gray} to 0
		if {timer-s} = 11:
			loop all entities in world "world":
				if loop-entity = fox:
					if block 2 meters below loop-entity = red_concrete:
						add 1 to {red}
					else if block 2 meters below loop-entity = orange_concrete:
						add 1 to {orange}
					else if block 2 meters below loop-entity = yellow_concrete:
						add 1 to {yellow}
					else if block 2 meters below loop-entity = lime_concrete:
						add 1 to {lime}
					else if block 2 meters below loop-entity = light_blue_concrete:
						add 1 to {light_blue}
					else if block 2 meters below loop-entity = blue_concrete:
						add 1 to {blue}
					else if block 2 meters below loop-entity = purple_concrete:
						add 1 to {purple}
					else if block 2 meters below loop-entity = pink_concrete:
						add 1 to {pink}
					else if block 2 meters below loop-entity = light_gray_concrete:
						add 1 to {light_gray}
					else:
						add 1 to {white}
			loop all players:
				if {vote_swap} = false:
					if loop-player doesn't have permission "group.spectators":
						if {alive.%loop-player's uuid%} = true:
							#Vote x1
							if the chestplate of loop-player != golden chestplate or diamond chestplate: 
								if block 2 meters below loop-player = red_concrete:
									add 1 to {red}
								else if block 2 meters below loop-player = orange_concrete:
									add 1 to {orange}
								else if block 2 meters below loop-player = yellow_concrete:
									add 1 to {yellow}
								else if block 2 meters below loop-player = lime_concrete:
									add 1 to {lime}
								else if block 2 meters below loop-player = light_blue_concrete:
									add 1 to {light_blue}
								else if block 2 meters below loop-player = blue_concrete:
									add 1 to {blue}
								else if block 2 meters below loop-player = purple_concrete:
									add 1 to {purple}
								else if block 2 meters below loop-player = pink_concrete:
									add 1 to {pink}
								else if block 2 meters below loop-player = light_gray_concrete:
									add 1 to {light_gray}
								else:
									add 1 to {white}
							#Vote x2
							if the chestplate of loop-player = golden chestplate: 
								if block 2 meters below loop-player = red_concrete:
									add 2 to {red}
								else if block 2 meters below loop-player = orange_concrete:
									add 2 to {orange}
								else if block 2 meters below loop-player = yellow_concrete:
									add 2 to {yellow}
								else if block 2 meters below loop-player = lime_concrete:
									add 2 to {lime}
								else if block 2 meters below loop-player = light_blue_concrete:
									add 2 to {light_blue}
								else if block 2 meters below loop-player = blue_concrete:
									add 2 to {blue}
								else if block 2 meters below loop-player = purple_concrete:
									add 2 to {purple}
								else if block 2 meters below loop-player = pink_concrete:
									add 2 to {pink}
								else if block 2 meters below loop-player = light_gray_concrete:
									add 2 to {light_gray}
								else:
									add 2 to {white}
							#Vote x3
							if the chestplate of loop-player = diamond chestplate: 
								if block 2 meters below loop-player = red_concrete:
									add 3 to {red}
								else if block 2 meters below loop-player = orange_concrete:
									add 3 to {orange}
								else if block 2 meters below loop-player = yellow_concrete:
									add 3 to {yellow}
								else if block 2 meters below loop-player = lime_concrete:
									add 3 to {lime}
								else if block 2 meters below loop-player = light_blue_concrete:
									add 3 to {light_blue}
								else if block 2 meters below loop-player = blue_concrete:
									add 3 to {blue}
								else if block 2 meters below loop-player = purple_concrete:
									add 3 to {purple}
								else if block 2 meters below loop-player = pink_concrete:
									add 3 to {pink}
								else if block 2 meters below loop-player = light_gray_concrete:
									add 3 to {light_gray}
								else:
									add 3 to {white}
				else:
					if loop-player has permission "group.spectators":
						if block 2 meters below loop-player = red_concrete:
							add 1 to {red}
						else if block 2 meters below loop-player = orange_concrete:
							add 1 to {orange}
						else if block 2 meters below loop-player = yellow_concrete:
							add 1 to {yellow}
						else if block 2 meters below loop-player = lime_concrete:
							add 1 to {lime}
						else if block 2 meters below loop-player = light_blue_concrete:
							add 1 to {light_blue}
						else if block 2 meters below loop-player = blue_concrete:
							add 1 to {blue}
						else if block 2 meters below loop-player = purple_concrete:
							add 1 to {purple}
						else if block 2 meters below loop-player = pink_concrete:
							add 1 to {pink}
						else if block 2 meters below loop-player = light_gray_concrete:
							add 1 to {light_gray}
						else:
							add 1 to {white}
		if {timer-s} = 10:
			clear all players's inventory
			checkBiggest()
		if {timer-s} = 3:
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {alive.%loop-player's uuid%} = false:
						if {hide.%loop-player's uuid%} = true:
							command("/hide %loop-player% false")
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 4:
		if {timer-s} = 5:
			loop all players:
				apply levitation of tier 2 without particles whilst hiding the potion icon to loop-player for 5.3 seconds
				if {hide.%loop-player's uuid%} = true:
					command("hide %loop-player% false")
		if {timer-s} = 1:
			send title "轉" to all players for 5 seconds with fadein 0.5 second and fade out 0.5 second
		if {timer-s} = 0:
			after()
			set {timer} to 5
			set {timer-s} to 30
			set {timer-m} to 1
			bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
			set {event_state} to "Starting game"
			loop all players:
				clear loop-player's inventory
				command("effect clear %loop-player% levitation")
				if loop-player has permission "theevent580.staff":
					if {debug.%loop-player's uuid%} = true:
						send "[&4Admin&r] Event state : &eTeleporting to game&r --> &aStarting game" to loop-player
				else:
					set {alive.%loop-player's uuid%} to true
			loop all entities in world "world":
				if loop-entity = fox:
					kill loop-entity
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 5:
		if {jeu_condi} != 0:
			if {timer-s} = 30:
				loop all players:
					if loop-player has permission "group.spectators":
						force loop-player to fly
						allow fly for loop-player
			if {timer-s} = 0:
				if {timer-m} = 1:
					send title "<#f0f064>%{jeu_logo}%&r %{jeu_nom}%" with subtitle "Game %{jeu}%/6" to all players for 5 seconds with fadein 0.5 second and fade out 0.5 second
		set {scoreboard.pos} to 0
		if {timer-m} = 0:
			if {jeu_nom} = "&c&lTrials":
				if {timer-s} = 35:
					broadcast "[&cTrials&r] Welcome to &c&lTrials&r."
				if {timer-s} = 30:
					broadcast "[&cTrials&r] Your goal is to complete as many trials as possible in 10 minutes."
				if {timer-s} = 25:
					broadcast "[&cTrials&r] The faster you go, the more points you get, so try to be the fastest."
				if {timer-s} = 15:
					broadcast "[&cTrials&r] Every 2 minutes, the time between the trials will get smaller, and so will the platform!"
				if {timer-s} = 10:
					broadcast "[&cTrials&r] The trial completion time will go from 10s to 6s."
				if {timer-s} = 3:
					broadcast "[&cTrials&r] &c&lTrials&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&cTrials&r] &c&lTrials&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&cTrials&r] &c&lTrials&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					broadcast "[&cTrials&r] &c&lTrials&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&cTrials" to loop-player
					set {event_state} to "Game &r&cTrials"
					set {jeu_condi} to 10
					set {timer-m} to 9
					set {timer-s} to 60
					set {timer} to 6
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					set {red} to -10000
			if {jeu_nom} = "&6&lParkour":
				if {timer-s} = 35:
					loop all players:
						if loop-player has permission "group.spectators":
							command("/see %loop-player%")
					broadcast "[&6Parkour&r] Welcome to &6&lParkour&r."
				if {timer-s} = 30:
					broadcast "[&6Parkour&r] Your goal is to complete all 25 levels in less than 10 minutes."
				if {timer-s} = 25:
					broadcast "[&6Parkour&r] Finishing a section will up your multiplier, so try to get the most you can !."
				if {timer-s} = 20:
					broadcast "[&6Parkour&r] You will get invisibility AND NO COLLISIONS."
				if {timer-s} = 3:
					broadcast "[&6Parkour&r] &6&lParkour&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&6Parkour&r] &6&lParkour&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&6Parkour&r] &6&lParkour&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					command("execute in parkour run fill 134 132 194 128 129 208 air replace minecraft:barrier")
					broadcast "[&6Parkour&r] &6&lParkour&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						command("/team join nocolisions %loop-player%")
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&6Parkour" to loop-player
					set {event_state} to "Game &r&6Parkour"
					set {timer} to 6
					set {timer-m} to 9
					set {timer-s} to 60
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					set {orange} to -10000
			if {jeu_nom} = "&e&lBingo":
				set {barrier} to "yellow"
				if {timer-s} = 35:
					loop all players:
						if loop-player has permission "group.spectators":
							command("/hide %loop-player% true")
					broadcast "[&eBingo&r] Welcome to &e&lBingo&r."
				if {timer-s} = 30:
					broadcast "[&eBingo&r] Your goal is to get every item on your &e&lBingo&r card in less than 20 minutes."
				if {timer-s} = 25:
					broadcast "[&eBingo&r] Getting an item before other people will give you more points, so try to be the fastest."
				if {timer-s} = 20:
					broadcast "[&eBingo&r] You'll spawn with a chainmail armor, an iron sword, an iron axe, an iron shovel & an iron pickaxe, all unbreakable."
				if {timer-s} = 15:
					broadcast "[&eBingo&r] You can only get 1 bonus, by killing someone (ONLY ONCE), it'll replace your iron sword & pickaxe by a diamond one, also unbreakable."
				if {timer-s} = 10:
					broadcast "[&eBingo&r] You'll also get a 1 minute grace periode to leave and run."
				if {timer-s} = 3:
					broadcast "[&eBingo&r] &e&lBingo&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&eBingo&r] &e&lBingo&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&eBingo&r] &e&lBingo&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					command("//world bingo")
					command("//pos1 999880,139,-999848")
					command("//pos2 999915,149,-999814")
					command("//walls air")
					command("//world world")
					command("execute in minecraft:bingo run gamerule randomTickSpeed 20")
					command("execute in minecraft:bingo run gamerule doDaylightCycle true")
					broadcast "[&eBingo&r] &e&lBingo&r started !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&eBingo" to loop-player
					set {event_state} to "Game &r&eBingo"
					loop all players:
						if loop-player has permission "group.spectators":
							allow fly for loop-player
							force loop-player to fly
						else:
							set loop-player's gamemode to survival
					set {timer} to 6
					set {timer-m} to 19
					set {timer-s} to 60
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					set {yellow} to -10000
					set {damage} to 2
					broadcast "[&eBingo&r] Grace periode ends in 1 minute."
			if {jeu_nom} = "&a&lTag":
				if {timer-s} = 35:
					broadcast "[&aTag&r] Welcome to &a&lTag&r."
				if {timer-s} = 30:
					broadcast "[&aTag&r] Your goal is to stay hidden as long as possible."
				if {timer-s} = 25:
					broadcast "[&aTag&r] One player will be randomly chosen to be the seeker, they must tag someone else before their time runs out, or they will lose a life!"
				if {timer-s} = 20:
					broadcast "[&aTag&r] You only have 3 lives, so don't get tagged"
					broadcast "[&aTag&r] (If you are the seeker at the start, you will only start with 2 lives)"
				if {timer-s} = 3:
					broadcast "[&aTag&r] &a&lTag&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&aTag&r] &a&lTag&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&aTag&r] &a&lTag&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					setRandomHunter()
					broadcast "[&aTag&r] &a&lTag&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame Find The Button" to loop-player
					set {event_state} to "Game &r&aTag"
					set {timer} to 6
					wait 1 second
					setBossbarName(getBossbarById("count"), "<#f0f068>%{players_alive}% players alive")
					showBossbar(getBossbarById("count"))
					set {lime} to -10000
			if {jeu_nom} = "&b&lMultilap":
				if {timer-s} = 25:
					broadcast "[&bMultilap&r] Welcome to &b&lMultilap&r."
				if {timer-s} = 20:
					broadcast "[&bMultilap&r] Complete all 3 laps as fast as you can !"
				if {timer-s} = 15:
					broadcast "[&bMultilap&r] Completing a lap before other people will give you more points, so try to be the fastest."
				if {timer-s} = 10:
					broadcast "[&bMultilap&r] &lWARNING, the map will change when the player in 1st place completes a lap."
				if {timer-s} = 5:
					broadcast "[&bMultilap&r] There are 3 different paths, and will change thoughout the race."
				if {timer-s} = 3:
					broadcast "[&bMultilap&r] This &b&lMultilap&r will start in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&bMultilap&r] This &b&lMultilap&r will start in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&bMultilap&r] This &b&lMultilap&r will start in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					command("execute in minecraft:races_lap_3 run fill -3 132 0 3 130 0 air destroy")
					set {race_timer} to true
					set {timer-m} to 9
					set {timer-s} to 60
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					loop all players:
						command("/team leave %loop-player%")
						if {hide.%loop-player's uuid%} = true:
							command("/hide %loop-player%")
						command("/team join nocolisions %loop-player%")
						set {race_lap_time.%loop-player's uuid%} to 0
						set {race_total_time.%loop-player's uuid%} to 0
						set {_item} to carrot on a stick
						set {_item.nbt} to nbt compound of {_item}
						add nbt of "{""minecraft:custom_model_data"":27,""minecraft:custom_name"":'{""text"":""You are on Lap 1"",""italic"""":false,""color"":""gold""}'}" to {_item.nbt}
						set slot 40 of loop-player to {_item}
					broadcast "[&bMultilap&r] &b&lMultilap&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&bMultilap" to loop-player
					set {event_state} to "Game &r&bMultilap"
					set {timer} to 6
					set {light_blue} to -10000
					set {damage} to 1
					wait 10 seconds
					command("execute in minecraft:races_lap_3 run fill 6 129 6 -6 134 6 air replace minecraft:red_stained_glass")
			if {jeu_condi} = 12:
				if {timer-s} = 35:
					broadcast "[&5Arms Race&r] Welcome to &5&lArms Race&r."
				if {timer-s} = 30:
					broadcast "[&5Arms Race&r] Your goal is to be the 1st one to kill a player with the golden knife as your ONLY weapon."
				if {timer-s} = 25:
					broadcast "[&5Arms Race&r] Every 2 kills, you upgrade to a new weapon!"
				if {timer-s} = 20:
					broadcast "[&5Arms Race&r] You will also have a Golden Knife at all time, killing someone with it will send them back 1 weapon."
				if {timer-s} = 15:
					broadcast "[&5Arms Race&r] If nobody gets the final kill after 15 minutes, the game will end."
				if {timer-s} = 10:
					broadcast "[&5Arms Race&r] Be careful, dying will remove (5+kills of your attacker)%% of your in-game points, so make sure to not die!"
				if {timer-s} = 5:
					broadcast "[&5Arms Race&r] The formula for kill points is [victim's points]*(0.05+your kills/100). Good luck understanding it!"
				if {timer-s} = 3:
					broadcast "[&5Arms Race&r] &5&lArms Race&r will be starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&5Arms Race&r] &5&lArms Race&r will be starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&5Arms Race&r] &5&lArms Race&r will be starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					broadcast "[&5Arms Race&r] &5&lArms Race&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&5Arms Race" to loop-player
					set {event_state} to "Game &r&5Arms Race"
					set {timer} to 6
					set {timer-m} to 14
					set {timer-s} to 59
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					set {purple} to -10000
					set {damage} to 3
			if {jeu_condi} = 9:
				if {timer-s} = 30:
					broadcast "[&9Build Masters&r] Welcome to &9&lBuild Masters&r."
				if {timer-s} = 25:
					broadcast "[&9Build Masters&r] Your goal is to be the fastest to build the 10 builds before you run out of time !"
				if {timer-s} = 20:
					broadcast "[&9Build Masters&r] Once the builds are completed, it will switch automatically."
				if {timer-s} = 15:
					broadcast "[&9Build Masters&r] You can get all of the blocks you need in the mall, available with the portal behind you."
				if {timer-s} = 10:
					broadcast "[&9Build Masters&r] A Concrete block costs 1 second, a Terracotta block costs 2 seconds and a Copper block costs 3 seconds."
				if {timer-s} = 3:
					broadcast "[&9Build Masters&r] &9&lBuild Masters&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&9Build Masters&r] &9&lBuild Masters&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&9Build Masters&r] &9&lBuild Masters&r starting in 1."
					set {finished_players} to 0
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					refillAll()
					loop all players:
						if {build.location.%loop-player's uuid%} = 0:
							command("execute in build_masters run tp %loop-player% 2.5 129 998.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 993")
							command("execute in minecraft:build_masters run fill 5 128 993 14 128 1002 air")
						else if {build.location.%loop-player's uuid%} = 1:
							command("execute in build_masters run tp %loop-player% 2.5 129 1019.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1014")
							command("execute in minecraft:build_masters run fill 5 128 1014 14 128 1023 air")
						else if {build.location.%loop-player's uuid%} = 2:
							command("execute in build_masters run tp %loop-player% 2.5 129 1040.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1035")
							command("execute in minecraft:build_masters run fill 5 128 1035 14 128 1044 air")
						else if {build.location.%loop-player's uuid%} = 3:
							command("execute in build_masters run tp %loop-player% 2.5 129 1061.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1056")
							command("execute in minecraft:build_masters run fill 5 128 1056 14 128 1065 air")
						else if {build.location.%loop-player's uuid%} = 4:
							command("execute in build_masters run tp %loop-player% 2.5 129 1082.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1077")
							command("execute in minecraft:build_masters run fill 5 128 1077 14 128 1086 air")
						else if {build.location.%loop-player's uuid%} = 5:
							command("execute in build_masters run tp %loop-player% 23.5 129 998.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 993")
							command("execute in minecraft:build_masters run fill 26 128 993 35 128 1002 air")
						else if {build.location.%loop-player's uuid%} = 6:
							command("execute in build_masters run tp %loop-player% 23.5 129 1019.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1014")
							command("execute in minecraft:build_masters run fill 26 128 1014 35 128 1023 air")
						else if {build.location.%loop-player's uuid%} = 7:
							command("execute in build_masters run tp %loop-player% 23.5 129 1040.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1035")
							command("execute in minecraft:build_masters run fill 26 128 1035 35 128 1044 air")
						else if {build.location.%loop-player's uuid%} = 8:
							command("execute in build_masters run tp %loop-player% 23.5 129 1061.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1056")
							command("execute in minecraft:build_masters run fill 26 128 1056 35 128 1065 air")
						else if {build.location.%loop-player's uuid%} = 9:
							command("execute in build_masters run tp %loop-player% 23.5 129 1082.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1077")
							command("execute in minecraft:build_masters run fill 26 128 1077 35 128 1086 air")
						else if {build.location.%loop-player's uuid%} = 10:
							command("execute in build_masters run tp %loop-player% 44.5 129 998.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 993")
							command("execute in minecraft:build_masters run fill 47 128 993 56 128 1002 air")
						else if {build.location.%loop-player's uuid%} = 11:
							command("execute in build_masters run tp %loop-player% 44.5 129 1019.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1014")
							command("execute in minecraft:build_masters run fill 47 128 1014 56 128 1023 air")
						else if {build.location.%loop-player's uuid%} = 12:
							command("execute in build_masters run tp %loop-player% 44.5 129 1040.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1035")
							command("execute in minecraft:build_masters run fill 47 128 1035 56 128 1044 air")
						else if {build.location.%loop-player's uuid%} = 13:
							command("execute in build_masters run tp %loop-player% 44.5 129 1061.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1056")
							command("execute in minecraft:build_masters run fill 47 128 1056 56 128 1065 air")
						else if {build.location.%loop-player's uuid%} = 14:
							command("execute in build_masters run tp %loop-player% 44.5 129 1082.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1077")
							command("execute in minecraft:build_masters run fill 47 128 1077 56 128 1086 air")
						else if {build.location.%loop-player's uuid%} = 15:
							command("execute in build_masters run tp %loop-player% 65.5 129 998.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 993")
							command("execute in minecraft:build_masters run fill 68 128 993 77 128 1002 air")
						else if {build.location.%loop-player's uuid%} = 16:
							command("execute in build_masters run tp %loop-player% 65.5 129 1019.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1014")
							command("execute in minecraft:build_masters run fill 68 128 1014 77 128 1023 air")
						else if {build.location.%loop-player's uuid%} = 17:
							command("execute in build_masters run tp %loop-player% 65.5 129 1040.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1035")
							command("execute in minecraft:build_masters run fill 68 128 1035 77 128 1044 air")
						else if {build.location.%loop-player's uuid%} = 18:
							command("execute in build_masters run tp %loop-player% 65.5 129 1061.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1056")
							command("execute in minecraft:build_masters run fill 68 128 1056 77 128 1065 air")
						else if {build.location.%loop-player's uuid%} = 19:
							command("execute in build_masters run tp %loop-player% 65.5 129 1082.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1077")
							command("execute in minecraft:build_masters run fill 68 128 1077 77 128 1086 air")
						else if {build.location.%loop-player's uuid%} = 20:
							command("execute in build_masters run tp %loop-player% 86.5 129 998.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 993")
							command("execute in minecraft:build_masters run fill 89 128 993 98 128 1002 air")
						else if {build.location.%loop-player's uuid%} = 21:
							command("execute in build_masters run tp %loop-player% 86.5 129 1019.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1014")
							command("execute in minecraft:build_masters run fill 89 128 1014 98 128 1023 air")
						else if {build.location.%loop-player's uuid%} = 22:
							command("execute in build_masters run tp %loop-player% 86.5 129 1040.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1035")
							command("execute in minecraft:build_masters run fill 89 128 1035 98 128 1044 air")
						else if {build.location.%loop-player's uuid%} = 23:
							command("execute in build_masters run tp %loop-player% 86.5 129 1061.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1056")
							command("execute in minecraft:build_masters run fill 89 128 1056 98 128 1065 air")
						else if {build.location.%loop-player's uuid%} = 24:
							command("execute in build_masters run tp %loop-player% 86.5 129 1082.00000001")
							command("execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1077")
							command("execute in minecraft:build_masters run fill 89 128 1077 98 128 1086 air")
						showBossbar(getBossbarById("mall"))
						if loop-player has permission "group.spectators":
							command("execute in minecraft:build_masters run tp %loop-player% -7.53 153.24 1040.13 -90.66 36.09")
							set loop-player's game mode to adventure
							force loop-player to fly
							allow flight to loop-player
						else:
							give 1 of netherite pickaxe of unbreaking 250 and efficiency 2 named "&9Unbreakable Pickaxe" to loop-player
							set loop-player's game mode to survival
					broadcast "[&9Build Masters&r] &9&lBuild Masters&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						#play sound "custom:race3" in record category with volume 1 to the loop-player
						set {timer_minute.%loop-player's uuid%} to 9
						set {timer_second.%loop-player's uuid%} to 60
						set {timeout_portal.%loop-player's uuid%} to 0
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&9Build Masters" to loop-player
					set {event_state} to "Game &r&9Build Masters"
					set {timer} to 6
					set {timer-m} to 59
					set {timer-s} to 60
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					set {blue} to -10000
			if {jeu_nom} = "&d&lBow PVP":
				if {timer-s} = 35:
					broadcast "[&dBow PVP&r] Welcome to &d&lBow PVP&r."
				if {timer-s} = 30:
					broadcast "[&dBow PVP&r] Your goal is to be the last one alive and kill everyone in less than 10 minutes !"
				if {timer-s} = 25:
					broadcast "[&dBow PVP&r] Everyone will start with 5 hearts and dying will remove you one heart."
				if {timer-s} = 20:
					broadcast "[&dBow PVP&r] But stabbing a player will give you its heart."
				if {timer-s} = 15:
					broadcast "[&dBow PVP&r] You'll start with a infinity bow and a stone sword (Both are unbreakable)."
				if {timer-s} = 10:
					broadcast "[&dBow PVP&r] &lWARNING, YOU CAN DIE FROM THE VOID ! &r(You are warned)"
				if {timer-s} = 3:
					broadcast "[&dBow PVP&r] &d&lBow PVP&r starting in 3."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 2:
					broadcast "[&dBow PVP&r] &d&lBow PVP&r starting in 2."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 1:
					broadcast "[&dBow PVP&r] &d&lBow PVP&r starting in 1."
					loop all players:
						play sound "block.note_block.bit" in voice category with volume 2 to the loop-player
				if {timer-s} = 0:
					loop all players:
						if loop-player has permission "group.spectators":
							teleport loop-player to location(0, 166, 0, world "Bow_PVP")
						else:
							respawnBowPVP(loop-player)
							give 1 of bow of unbreaking 250 and infinity 1 and power 250 named "&dUnbreakable Bow" to loop-player
							give 1 of stone sword of unbreaking 250 named "&dUnbreakable Sword" to loop-player
							set slot 8 of loop-player's inventory to arrow
					broadcast "[&dBow PVP&r] &d&lBow PVP&r is starting !"
					loop all players:
						play sound "entity.ender_dragon.growl" in voice category with volume 0.25 to the loop-player
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eStarting game&r --> &aGame &r&dBow PVP" to loop-player
					set {event_state} to "Game &r&dBow PVP"
					set {timer} to 6
					set {damage} to 4
					set {timer-m} to 9
					set {timer-s} to 60
					bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
					set {pink} to -10000
			if {timer-s} = 1:
				loop all players:
					if loop-player has permission "group.spectators":
						set slot 0 of loop-player to compass named "&rTeleport to player"
						set slot 1 of loop-player to feather named "&rChange your fly speed"
						command("hide %loop-player% true")
				if {jeu_condi} != 0:
					command("effect give @a minecraft:night_vision 9999 255 true")
		else:
			if {timer-s} = 0:
				remove 1 from {timer-m}
				set {timer-s} to 60
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 6:
		if {jeu_condi} != 6 or 8 or 10 or 11:
			if {finished_players} < {checking_finished_players}:
				if {jeu_condi} = 9:
					#Build Masters
						#Refills
					if {timer-s} = 30:
						refillAll()
					# Warnings
					loop all players:
						if {timer_second.%loop-player's uuid%} = 0:
							if {timer_minute.%loop-player's uuid%} = 5:
								send title "&e5 minutes left" with subtitle "&eHurry up !" to loop-player
							if {timer_minute.%loop-player's uuid%} = 3:
								send title "&63 minutes left" with subtitle "&6You better finish this build !" to loop-player
							if {timer_minute.%loop-player's uuid%} = 2:
								send title "&c2 minutes left" with subtitle "&cYou're almost out !" to loop-player
							if {timer_minute.%loop-player's uuid%} = 1:
								send title "&41 minute left" with subtitle "&4This = your last chance." to loop-player
				#Sounds -- MUSIC = OFF, IT WILL BE REOPENED ONCE I GET PROPER MUSIC
				###
				loop all players:
					if {jeu_condi} = 1: #Dropper
						if {timer-m} = 3:
							if {timer-s} = 37:
								play sound "custom:race6" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 37:
								play sound "custom:race6" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 24:
								play sound "custom:race6" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 11:
								play sound "custom:race6" in record category with volume 1 to the loop-player
					if {jeu_condi} = 2: #Parkour
						if {timer-m} = 8:
							if {timer-s} = 54:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 7:
							if {timer-s} = 48:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 42:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 36:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 30:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 24:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 18:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 12:
								play sound "custom:race2" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 6:
								play sound "custom:race2" in record category with volume 1 to the loop-player
					if {jeu_condi} = 3: #Bingo
						if {timer-m} = 18:
							if {timer-s} = 46:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 17:
							if {timer-s} = 36:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 16:
							if {timer-s} = 22:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 15:
							if {timer-s} = 12:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 13:
							if {timer-s} = 58:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 12:
							if {timer-s} = 48:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 11:
							if {timer-s} = 34:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 10:
							if {timer-s} = 24:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 9:
							if {timer-s} = 10:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 8:
							if {timer-s} = 0:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 46:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 36:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 22:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 12:
								play sound "custom:race8" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 58:
								play sound "custom:race10" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 48:
								play sound "custom:race8" in record category with volume 1 to the loop-player
					if {jeu_condi} = 4: #Find The Button
						if {timer-m} = 11:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 10:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 9:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 8:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 7:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 30:
								play sound "custom:race11" in record category with volume 1 to the loop-player
					if {jeu_condi} = 5: #Multilap
						if {timer-m} = 8:
							if {timer-s} = 56:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 7:
							if {timer-s} = 44:
								play sound "custom:race7" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 30:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 18:
								play sound "custom:race7" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 14:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 3:
							if {timer-s} = 2:
								play sound "custom:race7" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 58:
								play sound "custom:race9" in record category with volume 1 to the loop-player
						if {timer-m} = 0:
							if {timer-s} = 46:
								play sound "custom:race7" in record category with volume 1 to the loop-player
					if {jeu_condi} = 8: #Bow PVP
						if {timer-m} = 7:
							if {timer-s} = 49:
								play sound "custom:race4" in record category with volume 1 to the loop-player
						if {timer-m} = 6:
							if {timer-s} = 40:
								play sound "custom:race1" in record category with volume 1 to the loop-player
						if {timer-m} = 5:
							if {timer-s} = 29:
								play sound "custom:race4" in record category with volume 1 to the loop-player
						if {timer-m} = 4:
							if {timer-s} = 20:
								play sound "custom:race1" in record category with volume 1 to the loop-player
						if {timer-m} = 2:
							if {timer-s} = 19:
								play sound "custom:race4" in record category with volume 1 to the loop-player
						if {timer-m} = 1:
							if {timer-s} = 0:
								play sound "custom:race1" in record category with volume 1 to the loop-player
					if {jeu_condi} = 9: #Build Masters
						if {timer-m} = 29:
							if {timer-s} = 40:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 28:
							if {timer-s} = 19:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 27:
							if {timer-s} = 12:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 26:
							if {timer-s} = 1:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 24:
							if {timer-s} = 54:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 23:
							if {timer-s} = 43:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 22:
							if {timer-s} = 36:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 21:
							if {timer-s} = 25:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 20:
							if {timer-s} = 18:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 19:
							if {timer-s} = 07:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 18:
							if {timer-s} = 0:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 16:
							if {timer-s} = 49:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 15:
							if {timer-s} = 42:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 14:
							if {timer-s} = 31:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 13:
							if {timer-s} = 26:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 12:
							if {timer-s} = 15:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 11:
							if {timer-s} = 08:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 09:
							if {timer-s} = 57:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 08:
							if {timer-s} = 50:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 07:
							if {timer-s} = 39:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 06:
							if {timer-s} = 32:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 05:
							if {timer-s} = 21:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 04:
							if {timer-s} = 14:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 03:
							if {timer-s} = 03:
								play sound "custom:race5" in record category with volume 1 to the loop-player
						if {timer-m} = 01:
							if {timer-s} = 54:
								play sound "custom:race3" in record category with volume 1 to the loop-player
						if {timer-m} = 00:
							if {timer-s} = 43:
								play sound "custom:race5" in record category with volume 1 to the loop-player
				###
				
				#Time and all
				if {timer-s} = 0:
					if {timer-m} = 0:
						set {timer-s} to 31
						bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
						if {jeu} = 6:
							set {timer-m} to 1
							set {timer} to 10
						else:
							set {timer-m} to 0
							set {timer} to 7
						force all players to fly
						allow fly for all players
						loop all players:
							allow fly for loop-player
							set {gamemode.%loop-player's uuid%} to 3
							if loop-player has permission "theevent580.staff":
								send "[<#155966>&lTheEvent580&r] Code : 1" to loop-player
						if {jeu_condi} = 2:
							loop all players:
								if loop-player has permission "theevent580.staff":
									if {debug.%loop-player's uuid%} = true:
										send "[&4Admin&r] Event state : &eGame &r&6Parkour&r --> &aShowing scores" to loop-player
						if {jeu_condi} = 3:
							command("//world bingo")
							command("//pos1 289,64,164")
							command("//pos2 322,71,132")
							command("//walls barrier")
							command("execute in minecraft:bingo run gamerule doDaylightCycle false")
							loop all players:
								if loop-player has permission "theevent580.staff":
									if {debug.%loop-player's uuid%} = true:
										send "[&4Admin&r] Event state : &eGame Bingo&r --> &aShowing scores" to loop-player
						if {jeu_condi} = 5:
							set {race_timer} to false
							loop all players:
								if loop-player has permission "theevent580.staff":
									if {debug.%loop-player's uuid%} = true:
										send "[&4Admin&r] Event state : &eGame &r&bMultilap&r --> &aShowing scores" to loop-player
							set {jeu_condi} to 0
							set {damage} to 1
						if {jeu_condi} = 9:
							command("execute as @e[type=minecraft:text_display,tag=bm] run data modify entity @s text set value '{""text"":""Plot : Available""}'")
							loop all players:
								if loop-player has permission "theevent580.staff":
									if {debug.%loop-player's uuid%} = true:
										send "[&4Admin&r] Event state : &eGame &r&9Build Masters&r --> &aShowing scores" to loop-player
						if {jeu_condi} = 12:
							loop all players:
								if loop-player has permission "theevent580.staff":
									if {debug.%loop-player's uuid%} = true:
										send "[&4Admin&r] Event state : &eGame &r&5Arms Race&r --> &aShowing scores" to loop-player
						set {event_state} to "Showing scores"
						set {timer-s} to 31
						bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
						if {jeu} = 6:
							set {timer-m} to 1
							set {timer} to 10
						else:
							set {timer-m} to 0
							set {timer} to 7
						set {jeu_condi} to 0
						set {damage} to 1
						set {finished_players} to 0
						command("clear @a")
					if {timer-m} > 0:
						if {jeu_condi} = 9:
							refillAll()
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
				if {jeu_condi} = 9:
					loop all players:
						if {finished.%loop-player's uuid%} = false:
							if {timer_second.%loop-player's uuid%} = 0:
								remove 1 from {timer_minute.%loop-player's uuid%}
								add 60 to {timer_second.%loop-player's uuid%}
							remove 1 from {timer_second.%loop-player's uuid%}
				remove 1 from {timer-s}
				bossbarRemove1Sec("count")
			set {online_players_finished} to 0
			loop all players:
				if {finished.%loop-player's uuid%} = true:
					if loop-player doesn't have permission "group.spectators":
						add 1 to {online_players_finished}
			if {online_players_finished} = {online_players}:
				force all players to fly
				loop all players:
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						send "[<#155966>&lTheEvent580&r] Code : 4" to loop-player
				if {jeu_condi} = 9:
					command("execute as @e[type=minecraft:text_display,tag=bm] run data modify entity @s text set value '{""text"":""Plot : Available""}'")
					loop all players:
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eGame &r&9Build Masters&r --> &aShowing scores" to loop-player
				set {event_state} to "Showing scores"
				set {timer-s} to 31
				bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
				if {jeu} = 6:
					set {timer-m} to 1
					set {timer} to 10
				else:
					set {timer-m} to 0
					set {timer} to 7
				set {jeu_condi} to 0
				set {damage} to 1
				set {finished_players} to 0
				command("clear @a")
			else if {finished_players} = {checking_finished_players}:
				force all players to fly
				loop all players:
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						send "[<#155966>&lTheEvent580&r] Code : 3" to loop-player
				if {jeu_condi} = 2:
					loop all players:
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eGame &r&6Parkour&r --> &aShowing scores" to loop-player
				if {barrier} = "yellow":
					command("//world bingo")
					command("//pos1 289,64,164")
					command("//pos2 322,71,132")
					command("//walls barrier")
					command("execute in minecraft:bingo run gamerule doDaylightCycle false")
					loop all players:
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eGame Bingo&r --> &aShowing scores" to loop-player
				if {jeu_condi} = 5:
					set {race_timer} to false
					loop all players:
						if loop-player has permission "theevent580.staff":
							if {debug.%loop-player's uuid%} = true:
								send "[&4Admin&r] Event state : &eGame &r&bMultilap&r --> &aShowing scores" to loop-player
					set {jeu_condi} to 0
					set {damage} to 1
				set {event_state} to "Showing scores"
				set {timer-s} to 31
				bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
				if {jeu} = 6:
					set {timer-m} to 1
					set {timer} to 10
				else:
					set {timer-m} to 0
					set {timer} to 7
				set {jeu_condi} to 0
				set {damage} to 1
				set {finished_players} to 0
				command("clear @a")
		if {jeu_condi} = 8:
			if {finished_players} > 1:
				if {timer-s} = 0:
					if {timer-m} = 0:
						force all players to fly
						loop all players:
							allow fly for loop-player
							set {gamemode.%loop-player's uuid%} to 3
							if loop-player has permission "theevent580.staff":
								if {debug.%loop-player's uuid%} = true:
									send "[<#155966>&lTheEvent580&r] Code : 2" to loop-player
									send "[&4Admin&r] Event state : &eGame &r&dBow PVP&r --> &aShowing scores" to loop-player
						set {event_state} to "Showing scores"
						set {timer-m} to 1
						set {timer-s} to 30
						bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
						if {jeu} = 6:
							set {timer} to 10
						else:
							set {timer} to 7
						set {jeu_condi} to 0
						set {damage} to 1
						set {finished_players} to 0
						command("clear @a")
					if {timer-m} = 1:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						set {timer-m} to 0
						set {timer-s} to 60
					if {timer-m} = 2:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						set {timer-m} to 1
						set {timer-s} to 60
					if {timer-m} = 3:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} = 4:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} = 5:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} = 6:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} = 7:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} = 8:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
					if {timer-m} = 9:
						loop all players:
							play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
						remove 1 from {timer-m}
						set {timer-s} to 60
				remove 1 from {timer-s}
				bossbarRemove1Sec("count")
			else:
				force all players to fly
				loop all players:
					allow fly for loop-player
					set {gamemode.%loop-player's uuid%} to 3
					if loop-player has permission "theevent580.staff":
						if {debug.%loop-player's uuid%} = true:
							send "[&4Admin&r] Event state : &eGame &r&dBow PVP&r --> &aShowing scores" to loop-player
				set {event_state} to "Showing scores"
				set {timer-m} to 1
				set {timer-s} to 30
				bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
				if {jeu} = 6:
					set {timer} to 10
				else:
					set {timer} to 7
				set {jeu_condi} to 0
				set {damage} to 1
				set {finished_players} to 0
				command("clear @a")
	if {timer} = 7:
		if {timer-s} = 29:
			set the maximum health of all players to 10
			set {race_timer} to false
			command("stopsound @a")
			clear all players's inventory
			loop all players:
				remove invisibility from loop-player
				remove speed from loop-player
				clear {pos.%loop-player's uuid%}
				set {finished.%loop-player's uuid%} to false
				play sound "block.respawn_anchor.deplete" in voice category with volume 2 to the loop-player
				send title "&cGame Over" with subtitle "Check the chat to see your <#F0F064>工" to loop-player for 5 seconds
			clear {pos1}
			clear {pos2}
			clear {pos3}
			clear {show}
			clear {finished::*}
			clear {list_points::*}
			loop all players:
				set glowing of loop-player to false
				if loop-player doesn't have permission "group.spectators":
					if {jeu_nom} = "&6&lParkour":
						set {points_game_covert.%loop-player's uuid%} to round({points_game.%loop-player's uuid%} * {game_multiplier.%loop-player's uuid%})
						set {points_game.%loop-player's uuid%} to {points_game_covert.%loop-player's uuid%}
					add {points_game.%loop-player's uuid%} to {points.%loop-player's uuid%}
					add {points_game.%loop-player's uuid%} to {total_points.%loop-player's uuid%}
					add {points_game.%loop-player's uuid%} to {total_points_event.%loop-player's uuid%}
					add {points.%loop-player's uuid%} to {list_points::*}
					set {points_string.%loop-player's uuid%} to checkPoints({points.%loop-player's uuid%})
			set {list_points::*} to sorted {list_points::*}
			set {list_points::*} to reversed {list_points::*}
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					if {list_points::1} = {points.%loop-player's uuid%}:
						set {pos1} to "[<#155966>&lGame Scores&r] 1st : %loop-player% - %checkPoints({points.%loop-player's uuid%})% <#F0F064>工"
						set {pos.%loop-player's uuid%} to "<#BCD71D>1st"
					if {list_points::2} = {points.%loop-player's uuid%}:
						set {pos2} to "[<#155966>&lGame Scores&r] 2nd : %loop-player% - %checkPoints({points.%loop-player's uuid%})% <#F0F064>工"
						set {pos.%loop-player's uuid%} to "<#BCD71D>2nd"
					if {list_points::3} = {points.%loop-player's uuid%}:
						set {pos3} to "[<#155966>&lGame Scores&r] 3rd : %loop-player% - %checkPoints({points.%loop-player's uuid%})% <#F0F064>工"
						set {pos.%loop-player's uuid%} to "<#BCD71D>3rd"
					if {list_points::4} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>4th"
					if {list_points::5} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>5th"
					if {list_points::6} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>6th"
					if {list_points::7} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>7th"
					if {list_points::8} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>8th"
					if {list_points::9} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>9th"
					if {list_points::10} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>10th"
					if {list_points::11} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>11th"
					if {list_points::12} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>12th"
					if {list_points::13} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>13th"
					if {list_points::14} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>14th"
					if {list_points::15} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>15th"
					if {list_points::16} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>16th"
					if {list_points::17} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>17th"
					if {list_points::18} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>18th"
					if {list_points::19} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>19th"
					if {list_points::20} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>20th"
					if {list_points::21} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>21st"
					if {list_points::22} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>22nd"
					if {list_points::23} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>23rd"
					if {list_points::24} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>24th"
					if {list_points::25} = {points.%loop-player's uuid%}:
						set {pos.%loop-player's uuid%} to "<#BCD71D>&l25th"
				else:
					set {pos.%loop-player's uuid%} to "<#BCD71D>Spec"
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					set {show} to {points_game.%loop-player's uuid%}
					loop all players:
						if loop-player-2 has permission "group.spectators":
							send "[<#155966>&lGame Scores&r] %{color.%loop-player-1's uuid%}%%loop-player-1% &rhad <#D9D8F1>%checkPoints({show})% <#F0F064>工&r this game !" to loop-player-2
							send "[<#155966>&lGame Scores&r] %loop-player-1% had %checkPoints({show})% coins this game !" to console

		if {timer-s} = 25:
			command("execute in minecraft:races_lap_3 run setblock 44 131 -20 minecraft:blackstone")
			hideBossbar(getBossbarById("mall"))
			broadcast "[<#155966>&lGame Scores&r] Event Top 3 :"
			command("updateclassement")
		if {timer-s} = 22:
			loop all players:
				if {list_points::1} = {points.%loop-player's uuid%}:
					play sound "custom:coins" in voice category with volume 2 to the loop-player
				if {list_points::2} = {points.%loop-player's uuid%}:
					play sound "custom:coins" in voice category with volume 2 to the loop-player
				if {list_points::3} = {points.%loop-player's uuid%}:
					play sound "custom:coins" in voice category with volume 2 to the loop-player
			broadcast {pos1}
			broadcast {pos2}
			broadcast {pos3}
			set {scoreboard.pos} to 1
		if {timer-s} = 20:
			loop all players:
				if loop-player doesn't have permission "group.spectators":
					send "[<#155966>&lGame Scores&r] You had <#D9D8F1>%checkPoints({points_game.%loop-player's uuid%})% <#F0F064>工&r this game and have <#D9D8F1>%checkPoints({points.%loop-player's uuid%})% <#F0F064>工&r in total !" to loop-player
					play sound "custom:coins" in voice category with volume 2 to the loop-player
					set {alive.%loop-player's uuid%} to true
		if {timer-s} = 15:
			broadcast "[<#155966>&lGame Scores&r] Your placement is visible next to your points count in the middle of the games"
		if {timer-s} = 10:
			broadcast "[<#155966>&lGame Scores&r] You are placed :"
			loop all players:
				send "<#E2F093>%{pos.%loop-player's uuid%}%&r<#BCD71D>&l - <#D9D8F1>&n%checkPoints({points.%loop-player's uuid%})%<#F0F064> 工" to loop-player
		if {timer-s} = 2:
			send title "轉" to all players for 5 seconds with fadein 0.5 second and fade out 0.5 second
		if {timer-s} = 1:
			if {jeu} = 2:
				set time in world "world" to day
			if {jeu} = 4:
				set time in world "world" to dawn
			if {jeu} = 6:
				set time in world "world" to night
			if {jeu} = 3:
				set {timer-m} to 5
				set {timer-s} to 60
			else:			
				set {timer-m} to 1
				set {timer-s} to 60
			set {timer} to 8
			bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
			set {jeu_condi} to 0
			set {l6} to {jeu_nom}
			set {jeu_nom} to "Hub"
			loop all players:
				set helmet of loop-player to {flag.%loop-player's uuid%}
				set {gamemode.%loop-player's uuid%} to 2
				set {points_game.%loop-player's uuid%} to 0
				set the game mode of loop-player to adventure
				make loop-player execute command "spawn"
				command("fly %loop-player% false")
				clear loop-player's inventory
				command("hide %loop-player% false")
				if loop-player has permission "theevent580.staff":
					if {debug.%loop-player's uuid%} = true:
						send "[&4Admin&r] Event state : &eShowing scores&r --> &aIntermission" to loop-player
			set {event_state} to "Intermission"
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 8:
		if {timer-s} = 0:
			if {timer-m} = 0:
				add 1 to {jeu}
				if {jeu} = 4 or 5:
					set {multiplier} to 1.5
				else if {jeu} = 6:
					set {multiplier} to 2
				set {timer-s} to 10
				set {timer-m} to 0
				bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
				command("gametp")
				loop all players:
					set loop-player's game mode to adventure
					clear loop-player's inventory
					if loop-player has permission "group.spectators":
						set loop-player's game mode to spectator
						command("/hide %loop-player%")
					if loop-player has permission "theevent580.staff":
						if {debug.%loop-player's uuid%} = true:
							send "[&4Admin&r] Event state : &eIntermission&r --> &aOpening votes" to loop-player
				set {event_state} to "Opening votes"
				set {timer} to 9
			if {timer-m} = 1:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				set {timer-m} to 0
				command("fill 8 253 9 -8 250 -9 air replace minecraft:polished_deepslate")
				command("fill 8 247 3 -8 247 3 minecraft:redstone_block")
				command("fill 8 247 -3 -8 247 -3 minecraft:redstone_block")
				command("fill -3 247 -8 -3 247 8 minecraft:redstone_block")
				command("fill 3 247 -8 3 247 8 minecraft:redstone_block")
				command("fill 8 247 3 -8 247 3 minecraft:redstone_block")
				command("fill 8 247 -3 -8 247 -3 minecraft:redstone_block")
				command("fill -3 247 -8 -3 247 8 minecraft:redstone_block")
				command("fill 3 247 -8 3 247 8 minecraft:redstone_block")
			if {timer-m} = 2:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				set {timer-m} to 1
			if {timer-m} = 3:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				remove 1 from {timer-m}
			if {timer-m} = 4:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				remove 1 from {timer-m}
			if {timer-m} = 5:
				loop all players:
					play sound "block.note_block.banjo" in voice category with volume 2 and pitch 1 to the loop-player
				set {timer-s} to 60
				remove 1 from {timer-m}
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 9:
		if {timer-s} = 5:
			if {jeu} = 4:
				send title "&c&lNew multiplier !" with subtitle "Multiplier went from 1必 to 1.5必" to all players for 3 seconds
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 0.5 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1.5 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 2 to all players
			if {jeu} = 6:
				send title "&c&lNew multiplier !" with subtitle "Multiplier went from 1.5必 to 2必" to all players for 3 seconds
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 0.5 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 1.5 to all players
				wait 1 ticks
				play sound "block.note_block.iron_xylophone" in voice category with volume 2 and pitch 2 to all players
		if {timer-s} = 0:
			if {timer-m} = 0:
				command("fill 8 247 -8 -8 247 8 air")
				wait 5 ticks
				command("fill 8 250 3 -8 250 3 minecraft:polished_deepslate_slab")
				command("fill 8 250 -3 -8 250 -3 minecraft:polished_deepslate_slab")
				command("fill -3 250 -8 -3 250 8 minecraft:polished_deepslate_slab")
				command("fill 3 250 -8 3 250 8 minecraft:polished_deepslate_slab")
				command("fill 8 251 3 -8 251 3 minecraft:air")
				command("fill 8 251 -3 -8 251 -3 minecraft:air")
				command("fill -3 251 -8 -3 251 8 minecraft:air")
				command("fill 3 251 -8 3 251 8 minecraft:air")
				set {timer-s} to 40
				set {timer-m} to 0
				bossbarRefill("count", {timer-m}*60 + {timer-s}, true)
				set {timer} to 3
				loop all players:
					if loop-player has permission "theevent580.staff":
						if {debug.%loop-player's uuid%} = true:
							send "[&4Admin&r] Event state : &eOpening votes&r --> &aVoting" to loop-player
				set {event_state} to "Voting"
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {timer} = 10:
		if {timer-m} = 1:
			if {timer-s} = 29:
				clear {list_points::*}
				command("execute in minecraft:races_lap_3 run setblock 44 131 -20 minecraft:blackstone")
				hideBossbar(getBossbarById("mall"))
				play sound "block.respawn_anchor.deplete" in voice category with volume 2 to all players
				send title "&cGame & Event Over" with subtitle "Check the chat to see your coins" to all players for 5 seconds
				endNPCs()
				loop all players:
					set glowing of loop-player to false
					if loop-player doesn't have permission "group.spectators":
						if {jeu_nom} = "&6&lParkour":
							set {points_game_covert.%loop-player's uuid%} to round({points_game.%loop-player's uuid%} * {game_multiplier.%loop-player's uuid%})
							set {points_game.%loop-player's uuid%} to {points_game_covert.%loop-player's uuid%}
						add {points_game.%loop-player's uuid%} to {points.%loop-player's uuid%}
						add {points_game.%loop-player's uuid%} to {total_points.%loop-player's uuid%}
						add {points_game.%loop-player's uuid%} to {total_points_event.%loop-player's uuid%}
						add {points.%loop-player's uuid%} to {list_points::*}
						set {points_string.%loop-player's uuid%} to checkPoints({points.%loop-player's uuid%})
					loop {staff::*}:
						if loop-value-1 != loop-value-2:
							send "[<#155966>&lTheEvent580&r] %{color.%loop-value-1's uuid%}%%loop-value-1% had <#D9D8F1>%{show}% <#F0F064>工&r this game !" to loop-value-2
							send "[<#155966>&lTheEvent580&r] %loop-value-1% had <#D9D8F1>%{show}% <#F0F064>工&r this game !" to console
				set {list_points::*} to sorted {list_points::*}
				set {list_points::*} to reversed {list_points::*}
				loop all players:
					if loop-player doesn't have permission "group.spectators":
						if {list_points::1} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k1st"
						if {list_points::2} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k2nd"
						if {list_points::3} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k3rd"
						if {list_points::4} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k4th"
						if {list_points::5} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k5th"
						if {list_points::6} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k6th"
						if {list_points::7} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k7th"
						if {list_points::8} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k8th"
						if {list_points::9} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k9th"
						if {list_points::10} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k10th"
						if {list_points::11} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k11th"
						if {list_points::12} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k12th"
						if {list_points::13} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k13th"
						if {list_points::14} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k14th"
						if {list_points::15} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k15th"
						if {list_points::16} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k16th"
						if {list_points::17} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k17th"
						if {list_points::18} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k18th"
						if {list_points::19} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k19th"
						if {list_points::20} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k20th"
						if {list_points::21} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k21st"
						if {list_points::22} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k22nd"
						if {list_points::23} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k23rd"
						if {list_points::24} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k24th"
						if {list_points::25} = {points.%loop-player's uuid%}:
							set {pos.%loop-player's uuid%} to "<#BCD71D>&k25th"
				loop all players:
					remove invisibility from loop-player
					remove speed from loop-player
			if {timer-s} = 10:
				broadcast "[<#155966>&lTheEvent580&r] You are placed :"
				loop all players:
					send "<#E2F093>&k%{pos.%loop-player's uuid%}%&r<#BCD71D>&l - <#D9D8F1>&k%checkPoints({points.%loop-player's uuid%})%<#F0F064> 工" to loop-player
			if {timer-s} < 1:
				set {timer-s} to 59
				remove 1 from {timer-m}
				make all players execute "spawn"
		if {timer-m} = 0:
			if {timer-s} = 5:
				endNPCs()
				command("tp @a 335.5 -5.00 337.50 -104 -18")
			if {timer-s} = 0:
				if {timer-m} = 0:
					loop all players:
						if {list_points::1} = {points.%loop-player's uuid%}:
							#command("execute as @e[type=minecraft:text_display,tag=S1EDW] run data modify entity @s text set value '{""text"":""%{color.%loop-player's uuid%}% %loop-player%""}'")
							command("npc select 27")
							command("npc skin %loop-player%")
							command("dh l set S1E7W 1 2 %{color.%loop-player's uuid%}% %loop-player%")
					set {timer} to "Fin"
					set {event_timer} to false
					updateClassement()
			if {timer-m} = 1:
				set {timer-s} to 60
				set {timer-m} to 0
				make all players execute command "spawn"
				loop all players:
					if loop-player has permission "theevent580.staff":
						if {debug.%loop-player's uuid%} = true:
							send "[&4Admin&r] Event state : &eShowing scores&r --> &aEnd" to loop-player
				set {event_state} to "End"
		remove 1 from {timer-s}
		bossbarRemove1Sec("count")
	if {event_timer} = true:
		add 1 to {event_timer_second}
		add 1 to {event_timer_second_total}
		if {event_timer_second} = 60:
			remove 60 from {event_timer_second}
			add 1 to {event_timer_minute}
		if {event_timer_minute} = 60:
			remove 60 from {event_timer_minute}
			add 1 to {event_timer_hour}
		if {event_timer_second_total} = 60:
			remove 60 from {event_timer_second_total}
			add 1 to {event_timer_minute_total}
		if {event_timer_minute_total} = 60:
			remove 60 from {event_timer_minute_total}
			add 1 to {event_timer_hour_total}