on command "pl":
	if player does not have permission "*":
		cancel event
		send "[&c&lTheEvent580 - Private Messages&r] You don't have acess to the plugins list %player%..." to player

on command "plugins":
	if player does not have permission "*":
		cancel event
		send "[&c&lTheEvent580 - Private Messages&r] You don't have acess to the plugins list %player%..." to player

on command "tell":
	cancel event
	send "[&c&lTheEvent580 - Private Messages&r] This command is disabled, please use /msg instead"

on Skript start:
	set {online_players} to 0
	clear {staff::*}
	resetTab()

on inventory click:
	if clicked slot is 39:
		if {jeu_condi} is 0:
			cancel event
			close player's inventory
			send "[&c&lTheEvent580&r] You cannot remove this cosmetic manually, please go on the &cX &rblock (mushroom island) to remove it."
			wait 1 ticks
			clear slot 0 of player's inventory
			clear slot 1 of player's inventory
			clear slot 2 of player's inventory
			clear slot 3 of player's inventory
			clear slot 4 of player's inventory
			clear slot 5 of player's inventory
			clear slot 6 of player's inventory
			clear slot 7 of player's inventory
			clear slot 8 of player's inventory
	if {jeu_condi} is 1 or 2 or 5:
		cancel event
	if clicked slot is 8:
		if {jeu_condi} is 3 or 4:
			cancel event
	if clicked slot is 7:
		if {jeu_condi} is 3:
			cancel event
	if {menu.%player%} is "main":
		cancel event
		if clicked slot is 0:
			make player say ":skull:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 1:
			close player's inventory
			clear {menu.%player%}
			make player execute command "emotes heart"
		if clicked slot is 26:
			close player's inventory
			clear {menu.%player%}
	else if {menu.%player%} is "heart":
		cancel event
		if clicked slot is 0:
			make player say ":darkredlove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 1:
			make player say ":redlove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 2:
			make player say ":orangelove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 3:
			make player say ":yellowlove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 4:
			make player say ":limelove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 5:
			make player say ":greenlove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 6:
			make player say ":cyanlove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 7:
			make player say ":lightbluelove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 8:
			make player say ":bluelove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 9:
			make player say ":darkbluelove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 10:
			make player say ":purplelove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 11:
			make player say ":pinklove:"
			close player's inventory
			clear {menu.%player%}
		if clicked slot is 25:
			close player's inventory
			make player execute command "emotes"
		if clicked slot is 26:
			close player's inventory
			clear {menu.%player%}


on chat:
	if {mute.server} is true:
		if player doesn't have permission "group.spectators":
			cancel event
			send action bar "[&c&lTheEvent580 - Chat&r] &6⚠&rThe chat is currently muted !" to player
	if {mute.%player%} is true:
		cancel event
		send action bar "[&c&lTheEvent580 - Chat&r] &6⚠&rYou are currently muted by one of the staff members !" to player
	else:
		replace all "kys" with "***" in the message
		replace all "shit" and "fuck" with "****" in the message
		replace all "nigge" and "nigga" with "*****" in the message
		replace all "nigger" and "niggas" with "******" in the message
		replace all "niggers" with "*******" in the message
		replace all ":skull:" with "☠" in the message
		replace all ":darkredlove:" with "&4❤" in the message
		replace all ":redlove:" with "&c❤" in the message
		replace all ":orangelove:" with "&6❤" in the message
		replace all ":yellowlove:" with "&e❤" in the message
		replace all ":limelove:" with "&a❤" in the message
		replace all ":greenlove:" with "&2❤" in the message
		replace all ":cyanlove:" with "&3❤" in the message
		replace all ":lightbluelove:" with "&b❤" in the message
		replace all ":bluelove:" with "&9❤" in the message
		replace all ":darkbluelove:" with "&1❤" in the message
		replace all ":purplelove:" with "&5❤" in the message
		replace all ":pinklove:" with "&d❤" in the message


on server list ping:
	set the motd to "Fixing the bugs for &c&lTheEvent580 • Season 1 - Episode 4"

on join:
	wait 3 ticks
	apply saturation of tier 255 without any particles to the player for 999 days
	if player has permission "group.spectators":
		set the join message to "&r[&a+&r] &8%player%"
		set {color.%player's uuid%} to "露&8 "
		set {alive.%player%} to false
	else:
		set {alive.%player%} to true
		if player has permission "group.bleu_clair":
			set the join message to "&r[&a+&r] &b%player%"
			set {color.%player's uuid%} to "動&b "
		if player has permission "group.rouge":
			set the join message to "&r[&a+&r] &c%player%"
			set {color.%player's uuid%} to "ラ&c "
		if player has permission "group.rose":
			set the join message to "&r[&a+&r] &d%player%"
			set {color.%player's uuid%} to "目&d "
		if player has permission "group.vert":
			set the join message to "&r[&a+&r] &a%player%"
			set {color.%player's uuid%} to "画&a "
		if player has permission "group.bleu":
			set the join message to "&r[&a+&r] &1%player%"
			set {color.%player's uuid%} to "像&1 "
		if player has permission "group.orange":
			set the join message to "&r[&a+&r] &6%player%"
			set {color.%player's uuid%} to "ャ&6 "
		if player has permission "group.jaune":
			set the join message to "&r[&a+&r] &e%player%"
			set {color.%player's uuid%} to "ギ&e "
		if player has permission "group.violet":
			set the join message to "&r[&a+&r] &5%player%"
			set {color.%player's uuid%} to "の&5 "
	if {flag.%player%} is not set:
		set {flag.%player%} to false
	if {Secret_Base_1.%player%} is not set:
		set {Secret_Base_1.%player%} to false
		set {Secret_Base_1.%player%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %player% does not have the Achivement : You found the secret base in the hub !"
	if {Herobrine.%player%} is not set:
		set {Herobrine.%player%} to false
		set {Herobrine.%player%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %player% does not have the Achivement : You discovered Herobrine !"
	if {HubParkour.%player%} is not set:
		set {HubParkour.%player%} to false
		set {HubParkour.%player%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %player% does not have the Achivement : You finished the Hub parkour !"
	if {1SecBM.%player%} is not set:
		set {1SecBM.%player%} to false
		set {1SecBM.%player%.infos} to "[&c&lTheEvent580 - Achivement&r] Player %player% does not have the Achivement : Finishing the Build Master 5 seconds before the end !"
	if {check_block.%player%} is not set:
		set {check_block.%player%} to false
	if {gamemode.%player%} is 3:
		wait 1 second
		force player to fly
		allow fly for player
		add 1 to {finished_players}
	if {jeu_condi} is 1 or 2 or 4 or 5:
		if {hide.%player%} is true:
			make console execute command "/hide %player%"
		make console execute command "/hide %player%"
	else if {jeu_condi} is 0 or 3 or 6 or 7 or 8:
		if {hide.%player%} is false:
			make console execute command "/hide %player%"
		make console execute command "/hide %player%"
	if player has permission "*":
		add player to {staff::*}
		send "[&c&lTheEvent580 - Admin&r] Online Staff :"
		loop {staff::*}:
			send "[&c&lTheEvent580 - Admin&r] %loop-value%"
	make console execute command "/team join nocolisions %player%"
	if {total_points.%player's uuid%} is not set:	
		set {total_points.%player's uuid%} to 0
		set {total_points_event.%player's uuid%} to 0
	set {total_points_event.%player's uuid%} to {total_points_event.%player%}
	if {points.%player's uuid%} is not set:
		set {points.%player's uuid%} to 0
	if {timer} is 0:
		set {points.%player's uuid%} to 0
		set {total_points_event.%player's uuid%} to 0
	if player doesn't have permission "group.spectators":
		add 1 to {online_players}
	apply saturation without particles to player for 100 days
	wait 2 ticks
	if player doesn't have permission "group.spectators":
		if {jeu_condi} is not 3 or 6 or 9:
			set player's gamemode to adventure
		else:
			set player's gamemode to survival
	else:
		set player's gamemode to creative
	if {jeu_condi} = 0:
		make player execute command "/spawn"

	if {jeu_condi} = 1:
		if event-world is not "dropper":
			make server execute command "execute in minecraft:dropper run tp %player% 30.0 129 6.0 90 0"

	if {jeu_condi} = 2:
		if event-world is not "parkour":
			make server execute command "execute in minecraft:parkour run tp %player% 131.5 129.00 201.5 -90 0"

	if {jeu_condi} = 3:
		if event-world is not "bingo":
			make server execute command "execute in minecraft:bingo run tp %player% 999889.0 153 999932.5 0 0"

	if {jeu_condi} = 4:
		if event-world is not "find_the_button":
			make server execute command "execute in minecraft:find_the_button run tp %player% 0 148 0 0 0"

	if {jeu_condi} = 5:
		if event-world is not "races_lap_3":
			make server execute command "execute in minecraft:races_lap_3 run tp %player% 0.5 131 3.5 180 0"

	if {jeu_condi} = 9:
		if event-world is not "build_masters":
			if {timer} = 5 or 7:
				make server execute command "execute in minecraft:build_masters run tp %player% 0.5 131 3.5 180 0"
			if {timer} = 6:
				if {build.location.%player%} is 0:
					make server execute command "execute in build_masters run tp %player% 2.5 129 998.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 993"
						make server execute command "execute in minecraft:build_masters run fill 5 128 993 14 128 1002 air"
				else if {build.location.%player%} is 1:
					make server execute command "execute in build_masters run tp %player% 2.5 129 1019.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1014"
						make server execute command "execute in minecraft:build_masters run fill 5 128 1014 14 128 1023 air"
				else if {build.location.%player%} is 2:
					make server execute command "execute in build_masters run tp %player% 2.5 129 1040.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1035"
						make server execute command "execute in minecraft:build_masters run fill 5 128 1035 14 128 1044 air"
				else if {build.location.%player%} is 3:
					make server execute command "execute in build_masters run tp %player% 2.5 129 1061.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1056"
						make server execute command "execute in minecraft:build_masters run fill 5 128 1056 14 128 1065 air"
				else if {build.location.%player%} is 4:
					make server execute command "execute in build_masters run tp %player% 2.5 129 1082.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 19 131 1077"
						make server execute command "execute in minecraft:build_masters run fill 5 128 1077 14 128 1086 air"
				else if {build.location.%player%} is 5:
					make server execute command "execute in build_masters run tp %player% 23.5 129 998.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 993"
						make server execute command "execute in minecraft:build_masters run fill 26 128 993 35 128 1002 air"
				else if {build.location.%player%} is 6:
					make server execute command "execute in build_masters run tp %player% 23.5 129 1019.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1014"
						make server execute command "execute in minecraft:build_masters run fill 26 128 1014 35 128 1023 air"
				else if {build.location.%player%} is 7:
					make server execute command "execute in build_masters run tp %player% 23.5 129 1040.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1035"
						make server execute command "execute in minecraft:build_masters run fill 26 128 1035 35 128 1044 air"
				else if {build.location.%player%} is 8:
					make server execute command "execute in build_masters run tp %player% 23.5 129 1061.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1056"
						make server execute command "execute in minecraft:build_masters run fill 26 128 1056 35 128 1065 air"
				else if {build.location.%player%} is 9:
					make server execute command "execute in build_masters run tp %player% 23.5 129 1082.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 40 131 1077"
						make server execute command "execute in minecraft:build_masters run fill 26 128 1077 35 128 1086 air"
				else if {build.location.%player%} is 10:
					make server execute command "execute in build_masters run tp %player% 44.5 129 998.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 993"
						make server execute command "execute in minecraft:build_masters run fill 47 128 993 56 128 1002 air"
				else if {build.location.%player%} is 11:
					make server execute command "execute in build_masters run tp %player% 44.5 129 1019.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1014"
						make server execute command "execute in minecraft:build_masters run fill 47 128 1014 56 128 1023 air"
				else if {build.location.%player%} is 12:
					make server execute command "execute in build_masters run tp %player% 44.5 129 1040.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1035"
						make server execute command "execute in minecraft:build_masters run fill 47 128 1035 56 128 1044 air"
				else if {build.location.%player%} is 13:
					make server execute command "execute in build_masters run tp %player% 44.5 129 1061.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1056"
						make server execute command "execute in minecraft:build_masters run fill 47 128 1056 56 128 1065 air"
				else if {build.location.%player%} is 14:
					make server execute command "execute in build_masters run tp %player% 44.5 129 1082.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 61 131 1077"
						make server execute command "execute in minecraft:build_masters run fill 47 128 1077 56 128 1086 air"
				else if {build.location.%player%} is 15:
					make server execute command "execute in build_masters run tp %player% 65.5 129 998.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 993"
						make server execute command "execute in minecraft:build_masters run fill 68 128 993 77 128 1002 air"
				else if {build.location.%player%} is 16:
					make server execute command "execute in build_masters run tp %player% 65.5 129 1019.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1014"
						make server execute command "execute in minecraft:build_masters run fill 68 128 1014 77 128 1023 air"
				else if {build.location.%player%} is 17:
					make server execute command "execute in build_masters run tp %player% 65.5 129 1040.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1035"
						make server execute command "execute in minecraft:build_masters run fill 68 128 1035 77 128 1044 air"
				else if {build.location.%player%} is 18:
					make server execute command "execute in build_masters run tp %player% 65.5 129 1061.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1056"
						make server execute command "execute in minecraft:build_masters run fill 68 128 1056 77 128 1065 air"
				else if {build.location.%player%} is 19:
					make server execute command "execute in build_masters run tp %player% 65.5 129 1082.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 82 131 1077"
						make server execute command "execute in minecraft:build_masters run fill 68 128 1077 77 128 1086 air"
				else if {build.location.%player%} is 20:
					make server execute command "execute in build_masters run tp %player% 86.5 129 998.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 993"
						make server execute command "execute in minecraft:build_masters run fill 89 128 993 98 128 1002 air"
				else if {build.location.%player%} is 21:
					make server execute command "execute in build_masters run tp %player% 86.5 129 1019.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1014"
						make server execute command "execute in minecraft:build_masters run fill 89 128 1014 98 128 1023 air"
				else if {build.location.%player%} is 22:
					make server execute command "execute in build_masters run tp %player% 86.5 129 1040.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1035"
						make server execute command "execute in minecraft:build_masters run fill 89 128 1035 98 128 1044 air"
				else if {build.location.%player%} is 23:
					make server execute command "execute in build_masters run tp %player% 86.5 129 1061.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1056"
						make server execute command "execute in minecraft:build_masters run fill 89 128 1056 98 128 1065 air"
				else if {build.location.%player%} is 24:
					make server execute command "execute in build_masters run tp %player% 86.5 129 1082.00000001"
					if {build.%player%} is 1:
						make server execute command "execute in minecraft:build_masters run clone -23 138 10001 -23 129 10010 103 131 1077"
						make server execute command "execute in minecraft:build_masters run fill 89 128 1077 98 128 1086 air"

	if {jeu_condi} = 7:
		if event-world is not "SG1" or "SG2" or "SG3" or "SG4" or "SG5" or "SG6":
			if {game} = "SG1":
				if player have permission "group.spectators":
					make server execute command "execute in minecraft:sg1 run tp %player% -1565.177 68 -635.511 28.3 24.3"
				else if player have permission "group.rouge":
					make server execute command "execute in minecraft:sg1 run tp %player% -1577.5 59 -635.5 0 0"
				else if player have permission "group.orange":
					make server execute command "execute in minecraft:sg1 run tp %player% -1558.5 59 -628.5 45 0"
				else if player have permission "group.jaune":
					make server execute command "execute in minecraft:sg1 run tp %player% -1551.5 59 -611.5 90 0"
				else if player have permission "group.vert":
					make server execute command "execute in minecraft:sg1 run tp %player% -1558.5 59 -592.5 135 0"
				else if player have permission "group.bleu_clair":
					make server execute command "execute in minecraft:sg1 run tp %player% -1577.5 59 -585.5 180 0"
				else if player have permission "group.bleu":
					make server execute command "execute in minecraft:sg1 run tp %player% -1594.5 59 -592.5 -135 0"
				else if player have permission "group.violet":
					make server execute command "execute in minecraft:sg1 run tp %player% -1601.5 59 -611.5 -90 0"
				else if player have permission "group.rose":
					make server execute command "execute in minecraft:sg1 run tp %player% -1594.5 59 -628.5 -45 0"
			if {game} = "SG2":
				if player have permission "group.spectators":
					make server execute command "execute in minecraft:sg2 run tp %player% 0 45 0 0 90"
				else if player have permission "group.rouge":
					make server execute command "execute in minecraft:sg2 run tp %player% 20.5 21 0.5 90 0"
				else if player have permission "group.orange":
					make server execute command "execute in minecraft:sg2 run tp %player% 14.5 21 14.5 135 0"
				else if player have permission "group.jaune":
					make server execute command "execute in minecraft:sg2 run tp %player% 0.5 21 20.5 180 0"
				else if player have permission "group.vert":
					make server execute command "execute in minecraft:sg2 run tp %player% -13.5 21 14.5 -135 0"
				else if player have permission "group.bleu_clair":
					make server execute command "execute in minecraft:sg2 run tp %player% -19.5 21 0.5 -90 0"
				else if player have permission "group.bleu":
					make server execute command "execute in minecraft:sg2 run tp %player% -13.5 21 -13.5 -45 0"
				else if player have permission "group.violet":
					make server execute command "execute in minecraft:sg2 run tp %player% 0.5 21 -19.5 0 0"
				else if player have permission "group.rose":
					make server execute command "execute in minecraft:sg2 run tp %player% 14.5 21 -13.5 45 0"
			if {game} = "SG3":
				if player have permission "group.spectators":
					make server execute command "execute in minecraft:sg3 run tp %player% 37 28 -18 65.1 30.7"
				else if player have permission "group.rouge":
					make server execute command "execute in minecraft:sg3 run tp %player% 0 16 40 180 0"
				else if player have permission "group.orange":
					make server execute command "execute in minecraft:sg3 run tp %player% -27 16 28 -135 0"
				else if player have permission "group.jaune":
					make server execute command "execute in minecraft:sg3 run tp %player% -40 16 0 -90 0"
				else if player have permission "group.vert":
					make server execute command "execute in minecraft:sg3 run tp %player% -27 16 27 -45 0"
				else if player have permission "group.bleu_clair":
					make server execute command "execute in minecraft:sg3 run tp %player% 0 16 -40 0 0"
				else if player have permission "group.bleu":
					make server execute command "execute in minecraft:sg3 run tp %player% 28 16 -27 45 0"
				else if player have permission "group.violet":
					make server execute command "execute in minecraft:sg3 run tp %player% 40 16 0 90 0"
				else if player have permission "group.rose":
					make server execute command "execute in minecraft:sg3 run tp %player% 28 16 28 135 0"
			if {game} = "SG4":
				if player have permission "group.spectators":
					make server execute command "execute in minecraft:sg4 run tp %player% 0 60 -2.5 0 90"
				else if player have permission "group.rouge":
					make server execute command "execute in minecraft:sg4 run tp %player% 17 30 -2 90 0"
				else if player have permission "group.orange":
					make server execute command "execute in minecraft:sg4 run tp %player% 12 30 9 135 0"
				else if player have permission "group.jaune":
					make server execute command "execute in minecraft:sg4 run tp %player% 0 30 14 180 0"
				else if player have permission "group.vert":
					make server execute command "execute in minecraft:sg4 run tp %player% -11 30 9 -135 0"
				else if player have permission "group.bleu_clair":
					make server execute command "execute in minecraft:sg4 run tp %player% -16 30 -2 -90 0"
				else if player have permission "group.bleu":
					make server execute command "execute in minecraft:sg4 run tp %player% -11 30 -14 -45 0"
				else if player have permission "group.violet":
					make server execute command "execute in minecraft:sg4 run tp %player% 0 30 -19 0 0"
				else if player have permission "group.rose":
					make server execute command "execute in minecraft:sg4 run tp %player% 12 30 -14 45 0"
			if {game} = "SG5":
				if player have permission "group.spectators":
					make server execute command "execute in minecraft:sg5 run tp %player% 15 86 24 0 90"
				else if player have permission "group.rouge":
					make server execute command "execute in minecraft:sg5 run tp %player% 15 65 49 180 0"
				else if player have permission "group.orange":
					make server execute command "execute in minecraft:sg5 run tp %player% -2 65 42 -135 0"
				else if player have permission "group.jaune":
					make server execute command "execute in minecraft:sg5 run tp %player% -9 65 24 -90 0"
				else if player have permission "group.vert":
					make server execute command "execute in minecraft:sg5 run tp %player% -2 65 6 -45 0"
				else if player have permission "group.bleu_clair":
					make server execute command "execute in minecraft:sg5 run tp %player% 15 65 -1 0 0"
				else if player have permission "group.bleu":
					make server execute command "execute in minecraft:sg5 run tp %player% 33 65 6 45 0"
				else if player have permission "group.violet":
					make server execute command "execute in minecraft:sg5 run tp %player% 40 65 24 90 0"
				else if player have permission "group.rose":
					make server execute command "execute in minecraft:sg5 run tp %player% 33 65 42 135 0"
			if {game} = "SG6":
				if player have permission "group.spectators":
					make server execute command "execute in minecraft:sg6 run tp %player% -164.5 91 -34.5 -180 90"
				else if player have permission "group.rouge":
					make server execute command "execute in minecraft:sg6 run tp %player% -136 66 -34 90 0"
				else if player have permission "group.orange":
					make server execute command "execute in minecraft:sg6 run tp %player% -144 66 -14 135 0"
				else if player have permission "group.jaune":
					make server execute command "execute in minecraft:sg6 run tp %player% -164 66 -6 180 0"
				else if player have permission "group.vert":
					make server execute command "execute in minecraft:sg6 run tp %player% -184 66 -14 -135 0"
				else if player have permission "group.bleu_clair":
					make server execute command "execute in minecraft:sg6 run tp %player% -192 66 -34 -90 0"
				else if player have permission "group.bleu":
					make server execute command "execute in minecraft:sg6 run tp %player% -184 66 -54 -45 0"
				else if player have permission "group.violet":
					make server execute command "execute in minecraft:sg6 run tp %player% -164 66 -62 0 0"
				else if player have permission "group.rose":
					make server execute command "execute in minecraft:sg6 run tp %player% -144 66 -54 45 0"

	if {jeu_condi} = 8:
		if event-world is not "bow_pvp":
			respawnBowPVP(player)
	wait 2 second
	if event-world is "world":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/00f58e93166e5deb00f98d74f94e37f67ef84350.zip 00f58e93166e5deb00f98d74f94e37f67ef84350" #Spawn
	if event-world is "dropper":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Dropper
	if event-world is "parkour":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/1c42f10ba02c0ea9a19180dbe4bc4d2e66f17a26.zip 1c42f10ba02c0ea9a19180dbe4bc4d2e66f17a26" #Parkour
	if event-world is "bingo":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/5b7cf07cb063037d9c8a7fe3fcfc98f89ab35a38.zip 5b7cf07cb063037d9c8a7fe3fcfc98f89ab35a38" #Bingo
	if event-world is "find_the_button":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Find The Button
	if event-world is "races_lap_3":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/2d6d579a86304775612992fdcac5d645783889e6.zip 2d6d579a86304775612992fdcac5d645783889e6" #Multilap
	if event-world is "build_masters":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/d7af2588cb9bcb13535c952d915e5919ad0bd166.zip d7af2588cb9bcb13535c952d915e5919ad0bd166" #Build Masters
	if event-world is "SG1" or "SG2" or "SG3" or "SG4" or "SG5" or "SG6":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Survival Games
	if event-world is "Bow_PVP":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Bow PVP

on vehicle destroy:
	if {jeu_condi} is 0:
		cancel event

on vehicle exit:
	set {in_vehicle.%player%} to false
	if {jeu_condi} is 5:
		make server execute command "execute at %player% run kill @e[type=minecraft:boat,sort=nearest,limit=1]"
		if y-coordinate of player is greater than 119:
			if player's gamemode is adventure:
				wait 3 ticks
				if {race_boat.%player%} is true:
					give 1 of oak boat to player

on vehicle enter:
	set {in_vehicle.%player%} to true

on quit:
	if {gamemode.%player%} is 3:
		remove 1 from {finished_players}
	if player has permission "group.spectators":
		remove player from {staff::*}
	set {color.%player's uuid%} to "タ &7"
	remove player from {players::*}
	#For Tests --> put nothing
	#remove 1 from {online_players}
	#For Event --> 
	if player doesn't have permission "group.spectators":
		remove 1 from {online_players}
	if player has permission "group.spectators":
		set leave message to "&r[&c-&r] &8%player%"
	else if player has permission "group.bleu_clair":
		set leave message to "&r[&c-&r] &b%player%"
	else if player has permission "group.rouge":
		set leave message to "&r[&c-&r] &c%player%"
	else if player has permission "group.rose":
		set leave message to "&r[&c-&r] &d%player%"
	else if player has permission "group.vert":
		set leave message to "&r[&c-&r] &a%player%"
	else if player has permission "groupe.bleu":
		set leave message to "&r[&c-&r] &1%player%"
	else if player has permission "groupe.orange":
		set leave message to "&r[&c-&r] &6%player%"
	else if player has permission "groupe.jaune":
		set leave message to "&r[&c-&r] &e%player%"
	else if player has permission "groupe.violet":
		set leave message to "&r[&c-&r] &5%player%"

on damage:
	if damage cause is fall:
		cancel event
	if attacker has permission "group.spectators":
		if {jeu_condi} is 0 or -1:
			cancel event
	if victim has permission "group.spectators":
		cancel event
	if {timer} is 3 or 8:
		if attacker doesn't have permission "group.spectators":
			if damage cause is not projectile:
				if attacker is not holding netherite sword:
					cancel event
				else: # Sword
					cancel event
					make console execute command "hide %victim%"
					broadcast "[&c&lTheEvent580 - ☠&r] %{color.%victim's uuid%}%%victim%&r was killed by %{color.%attacker's uuid%}%%attacker%"
					set {alive.%victim%} to false
					clear victim's inventory
					clear attacker's inventory
					allow flight for victim
			else: # Crossbow
				cancel event
				make console execute command "execute at %victim% run kill @e[type=minecraft:arrow,sort=nearest,limit=1]"
				make console execute command "hide %victim%"
				broadcast "[&c&lTheEvent580 - ☠&r] %{color.%victim's uuid%}%%victim%&r was shot by %{color.%attacker's uuid%}%%attacker%"
				set {alive.%victim%} to false
				clear victim's inventory
				clear attacker's inventory
				allow flight for victim
	else if {timer} = 4 or 5:
		cancel event
	else if {jeu_condi} is 0:
		if attacker doesn't have permission "group.spectators":
			cancel event
	else:
		if {damage} is 1 or 2:
			if victim is a player:
				cancel event
		else:
			if {jeu_condi} = 8:
				if attacker = victim:
					cancel event
					send "[&c&lTheEvent580&r] You cannot kill yourself" to victim
				if {invincibility.%victim's uuid%} = true:
					cancel event
					send "You should take damage right now but you're invincible for %{invincibility.time_left.%victim's uuid%}% more seconds" to victim
				if {finished.%victim%} or {finished.%attacker%} = true:
					cancel event
				if {alive.%victim%} or {alive.%attacker%} = false:
					cancel event
			if {jeu_condi} is 3:
				if victim is item frame:
					cancel event
				if {bingo_cases.%attacker's uuid%} is "All":
					cancel event
			if {jeu_condi} = 6:
				if {alive.%victim's uuid%} or {alive.%attacker's uuid%} = false:
					cancel event

on death:
	if victim is a player:
		if {jeu_condi} is not 3 or 8:
			wait 5 ticks
			force victim to respawn
			make console execute command "hide %victim%"
			make console execute command "fly %victim%"
			if {jeu_condi} is 6:
				if {game} is "SG1":
					teleport victim to location(-1565.177, 68, -635.511, "sg1", 28.3, 24.3)
				if {game} is "SG2":
					teleport victim to location(0, 45, 0, "sg2", 0, 90)
				if {game} is "SG3":
					teleport victim to location(0, 25, 0, "sg3", 0.1, 90)
				remove 1 from {finished_players}
				set {alive.%victim's uuid%} to false
		if attacker is a player:
			if {jeu_condi} is 3:
				if {bingo_kill.%attacker's uuid%} is false:
					set {bingo_kill.%attacker's uuid%} to true
					send "[&c&lTheEvent580&r] You killed a player for the 1st time and recieved your bonus" to attacker
				else if {bingo_kill.%attacker's uuid%} is 2:
					send "[&c&lTheEvent580&r] You already killed a player and got nothing" to attacker
			else if {jeu_condi} is 6:
				if {1st_blood} is false:
					add {pts_lvl_2} to {points_game.%attacker's uuid%}
					add {pts_lvl_2} to {total_points.%attacker's uuid%}
					add {pts_lvl_2} to {total_points_event.%attacker's uuid%}
					broadcast "[&c&lTheEvent580&r] %victim% got killed by %attacker% [&5+%{pts_lvl_2}%&r╣]"
					send "[&c&lTheEvent580&r] You killed %victim% [&5+%{pts_lvl_2}%&r╣]" to attacker
					send "[&c&lTheEvent580&r] You got killed by %attacker%" to victim
				else if {1st_blood} is true:
					add {pts_lvl_1} to {points_game.%attacker's uuid%}
					add {pts_lvl_1} to {total_points.%attacker's uuid%}
					add {pts_lvl_1} to {total_points_event.%attacker's uuid%}
					broadcast "[&c&lTheEvent580&r] %victim% got killed by %attacker% (1st blood) [&5+%{pts_lvl_1}%&r╣]"
					send "[&c&lTheEvent580&r] You killed %victim% (1st blood) [&5+%{pts_lvl_1}%&r╣]" to attacker
					send "[&c&lTheEvent580&r] You got killed by %attacker% (1st blood)" to victim
					set {1st_blood} to false
		if {jeu_condi} is 6:
			loop all players:
				if loop-player is not attacker or victim:
					if {alive.%loop-player's uuid%} is true:
						add {pts_lvl_3} to {points_game.%loop-player's uuid%}
						add {pts_lvl_3} to {total_points.%loop-player's uuid%}
						add {pts_lvl_3} to {total_points_event.%loop-player's uuid%}
						send "[&c&lTheEvent580&r] You survived to a kill [&5+%{pts_lvl_3}%&r╣]" to loop-player
		if {jeu_condi} = 8:
			heal attacker
			if the maximum health of victim < 1 :
				set {finished.%victim's uuid%} to true
				set {alive.%victim's uuid%} to false
				if damage cause = projectile:
					loop all players:
						if loop-player = victim:
							send "[&c&lTheEvent580 - Elimination&r] You were shot by %attacker% (-1 &c❤&r)" to loop-player
						else if loop-player = attacker:
							add {pts_lvl_3} to {points_game.%attacker's uuid%}
							add {pts_lvl_3} to {total_points.%attacker's uuid%}
							add {pts_lvl_3} to {total_points_event.%attacker's uuid%}
							send "[&c&lTheEvent580 - Elimination&r] You shot %victim% [&d+%{pts_lvl_3}%&r╣]" to loop-player
						else:
							if {alive.%loop-player's uuid%} is true:
								add {pts_lvl_6} to {points_game.%loop-player's uuid%}
								add {pts_lvl_6} to {total_points.%loop-player's uuid%}
								add {pts_lvl_6} to {total_points_event.%loop-player's uuid%}
								send "[&c&lTheEvent580 - Elimination&r] Player %victim% was shot by %attacker% [&d+%{pts_lvl_6}%&r╣]" to loop-player
				else if damage cause = attack:
					loop all players:
						if loop-player = victim:
							send "[&c&lTheEvent580 - Elimination&r] You were killed by %attacker% (-1 &c❤&r)" to loop-player
						else if loop-player = attacker:
							add {pts_lvl_2} to {points_game.%attacker's uuid%}
							add {pts_lvl_2} to {total_points.%attacker's uuid%}
							add {pts_lvl_2} to {total_points_event.%attacker's uuid%}
							send "[&c&lTheEvent580 - Elimination&r] You killed %victim% (+1 &c❤&r)[&d+%{pts_lvl_2}%&r╣]" to loop-player
						else:
							if {alive.%loop-player's uuid%} is true:
								add {pts_lvl_6} to {points_game.%loop-player's uuid%}
								add {pts_lvl_6} to {total_points.%loop-player's uuid%}
								add {pts_lvl_6} to {total_points_event.%loop-player's uuid%}
								send "[&c&lTheEvent580 - Elimination&r] Player %victim% was killed by %attacker% [&d+%{pts_lvl_6}%&r╣]" to loop-player
					add 1 to the maximum health of attacker
					wait 2 ticks
					heal attacker
				else if y-coordinate of victim < 95:
					loop all players:
						if loop-player = victim:
							send "[&c&lTheEvent580 - Elimination&r] You fell into the void (-1 &c❤&r)" to loop-player
						else:
							if {alive.%loop-player's uuid%} is true:
								add {pts_lvl_6} to {points_game.%loop-player's uuid%}
								add {pts_lvl_6} to {total_points.%loop-player's uuid%}
								add {pts_lvl_6} to {total_points_event.%loop-player's uuid%}
								send "[&c&lTheEvent580 - Elimination&r] Player %victim% fell into the void [&d+%{pts_lvl_6}%&r╣]" to loop-player
				wait 3 ticks
				make console execute command "hide %victim%"
				set the maximum health of the victim to 10
				push victim 2 blocks up
				force victim to fly
				allow fly for victim
				clear victim's inventory
			else:
				set {invincibility.time_left.%victim's uuid%} to 5
				set {invincibility.%victim's uuid%} to true
				if damage cause = projectile:
					loop all players:
						if loop-player = victim:
							send "[&c&lTheEvent580 - 💀&r] You were shot by %attacker% (-1 &c❤&r)" to loop-player
						else if loop-player = attacker:
							add {pts_lvl_1} to {points_game.%attacker's uuid%}
							add {pts_lvl_1} to {total_points.%attacker's uuid%}
							add {pts_lvl_1} to {total_points_event.%attacker's uuid%}
							send "[&c&lTheEvent580 - 💀&r] You shot %victim% (+1 &c❤&r)[&d+%{pts_lvl_1}%&r╣]" to loop-player
						else:
							if {alive.%loop-player's uuid%} is true:
								add {pts_lvl_5} to {points_game.%loop-player's uuid%}
								add {pts_lvl_5} to {total_points.%loop-player's uuid%}
								add {pts_lvl_5} to {total_points_event.%loop-player's uuid%}
								send "[&c&lTheEvent580 - 💀&r] Player %victim% was shot by %attacker% [&d+%{pts_lvl_5}%&r╣]" to loop-player
				else if damage cause = attack:
					loop all players:
						if loop-player = victim:
							send "[&c&lTheEvent580 - 💀&r] You were killed by %attacker% (-1 &c❤&r)" to loop-player
						else if loop-player = attacker:
							add {pts_lvl_2} to {points_game.%attacker's uuid%}
							add {pts_lvl_2} to {total_points.%attacker's uuid%}
							add {pts_lvl_2} to {total_points_event.%attacker's uuid%}
							send "[&c&lTheEvent580 - 💀&r] You killed %victim% [&d+%{pts_lvl_2}%&r╣]" to loop-player
						else:
							if {alive.%loop-player's uuid%} is true:
								add {pts_lvl_5} to {points_game.%loop-player's uuid%}
								add {pts_lvl_5} to {total_points.%loop-player's uuid%}
								add {pts_lvl_5} to {total_points_event.%loop-player's uuid%}
								send "[&c&lTheEvent580 - 💀&r] Player %victim% was killed by %attacker% [&d+%{pts_lvl_5}%&r╣]" to loop-player
					add 1 to the maximum health of attacker
					wait 2 ticks
					heal attacker
				else if damage cause = void:
					loop all players:
						if loop-player = victim:
							send "[&c&lTheEvent580 - 💀&r] You fell into the void (-1 &c❤&r)" to loop-player
						else:
							if {alive.%loop-player's uuid%} is true:
								add {pts_lvl_5} to {points_game.%loop-player's uuid%}
								add {pts_lvl_5} to {total_points.%loop-player's uuid%}
								add {pts_lvl_5} to {total_points_event.%loop-player's uuid%}
								send "[&c&lTheEvent580 - 💀&r] Player %victim% fell into the void [&d+%{pts_lvl_5}%&r╣]" to loop-player
				wait 3 ticks
				remove 1 from the maximum health of victim
			wait 1 second
			force victim to respawn

on respawn:
	if {jeu_condi} is 3:
		wait 1 tick
		teleport player to location(999889.0, 153, 999932.5, world "Bingo")
		make server execute command "effect give @a minecraft:night_vision 9999 255 true"
	else if {jeu_condi} is 6:
		wait 1 tick
		if {game} is "SG1":
			teleport player to location(-1565.177, 68, -635.511, "sg1", 28.3, 24.3)
		else if {game} is "SG2":
			teleport player to location(0, 45, 0, "sg2", 0, 90)
		else if {game} is "SG3":
			teleport player to location(37, 28, -18, "sg3", 65.1, 30.7)
	else if {jeu_condi} is 8:
		wait 1 tick
		respawnBowPVP(player)
		heal player
		apply saturation without particles to player for 100 days

on break:
	if player's gamemode is not creative:
		if {jeu_condi} is not 3 or 9:
			if {jeu_condi} is 6:
				if event-block isn't cobweb or leaves or vines or mushroom or hay bale or wheat:
					cancel event
			else:
				cancel event
		else if {jeu_condi} is 9:
			if block is smooth quartz or quartz pillar or iron block or gold block or emerald block or diamond block or dark oak trapdoor or chiseled quartz or quartz bricks:
				cancel event
			if the y-coordinate of block is bigger than 129:
				cancel event
	if {timer} is "pause":
		if player doesn't have permission "group.spectators":
			cancel event

on right click with paper:
	if name of tool of player is "&eYour Bingo card":
		make player execute command "card"
	if name of tool of player is "&aTotal of button pressed card":
		make player execute command "totalbuttons"

on right click with feather:
	if name of tool of player is "Change player's fly speed":
		make player execute command "speed"

on right click with bone meal:
	if targeted block is oak sapling:
		remove 1 of bone meal from player
		# Face 1
		make 5 of happy_villager at location(318.2,66.3,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.3,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.3,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.2,66.6,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.6,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.6,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.2,66.9,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.9,335.3,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.9,335.3,"world") with force for all players
		#Face 2
		make 5 of happy_villager at location(318.2,66.3,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.3,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.3,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.2,66.6,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.6,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.6,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.2,66.9,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.9,335.6,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.9,335.6,"world") with force for all players
		#Face 3
		make 5 of happy_villager at location(318.2,66.3,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.3,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.3,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.2,66.6,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.6,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.6,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.2,66.9,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.5,66.9,335.9,"world") with force for all players
		make 5 of happy_villager at location(318.8,66.9,335.9,"world") with force for all players

on right click with carrot on a stick:
	if name of tool of player is "&eTeleport to home":
		teleport player to location(999889.0, 153, 999932.5, world "Bingo")
	if name of tool of player is "&6Skip level":
		if {parkour.main_level.%player's uuid%} = 4:
			if {parkour.sub_level.%player's uuid%} = 7:
				send "[&c&lTheEvent580 - Parkour&r] Sorry, but as this is the last level, you cannot skip this level... Good luck !"
			else:
				if {parkour.skip.%player's uuid%} = false:
					set {parkour.skip.%player's uuid%} to true
					set {parkour.skip_used.%player's uuid%} to true
					set {_parkour_tp} to {parkour.next_level_coord.%player's uuid%} + 0.5
					wait 2 tick
					teleport player to location({_parkour_tp}, 129, z-coordinate of player, world "parkour", -90, 0.0001)
					remove 10 from {points_game.%player's uuid%}
					wait 3 ticks
					set {parkour.skip_used.%player's uuid%} to false
					wait 15 ticks
					if {parkour.sub_level.%player's uuid%} = 6:
						clear player's inventory
					wait 9 seconds
					set {parkour.skip.%player's uuid%} to false
				else:
					send "[&c&lTheEvent580 - Parkour&r] You have to wait 10 seconds before using the skip again"
		else if {parkour.main_level.%player's uuid%} = 1:
			if {parkour.sub_level.%player's uuid%} = 1:
				send "[&c&lTheEvent580 - Parkour&r] Sorry, but as this is the first level, you cannot skip this level... Good luck !"
			else:
				if {parkour.skip.%player's uuid%} = false:
					set {parkour.skip.%player's uuid%} to true
					set {parkour.skip_used.%player's uuid%} to true
					set {_parkour_tp} to {parkour.next_level_coord.%player's uuid%} + 0.5
					wait 2 tick
					teleport player to location({_parkour_tp}, 129, z-coordinate of player, world "parkour", -90, 0.0001)
					remove 10 from {points_game.%player's uuid%}
					wait 3 ticks
					set {parkour.skip_used.%player's uuid%} to false
					wait 15 ticks
					wait 9 seconds
					set {parkour.skip.%player's uuid%} to false
				else:
					send "[&c&lTheEvent580 - Parkour&r] You have to wait 10 seconds before using the skip again"
		else:
			if {parkour.skip.%player's uuid%} = false:
				set {parkour.skip.%player's uuid%} to true
				set {parkour.skip_used.%player's uuid%} to true
				set {_parkour_tp} to {parkour.next_level_coord.%player's uuid%} + 0.5
				wait 2 tick
				teleport player to location({_parkour_tp}, 129, z-coordinate of player, world "parkour", -90, 0.0001)
				remove 10 from {points_game.%player's uuid%}
				wait 3 ticks
				set {parkour.skip_used.%player's uuid%} to false
				wait 15 ticks
				wait 9 seconds
				set {parkour.skip.%player's uuid%} to false
			else:
				send "[&c&lTheEvent580 - Parkour&r] You have to wait 10 seconds before using the skip again"
	if name of tool of player is "Block a game":
		send "Test"
		if block 2 meter under player is red concrete:
			blockGame("Dropper",player)
		if block 2 meter under player is orange concrete:
			blockGame("Parkour",player)
		if block 2 meter under player is yellow concrete:
			blockGame("Bingo",player)
		if block 2 meter under player is lime concrete:
			blockGame("Find The Button",player)
		if block 2 meter under player is light blue concrete:
			blockGame("Multilap",player)
		if block 2 meter under player is blue concrete:
			blockGame("Build Masters",player)
		if block 2 meter under player is purple concrete:
			blockGame("Survival Games",player)
		if block 2 meter under player is pink concrete:
			blockGame("Bow PVP",player)
	if name of tool of player is "You choose the game":
		loop all players:
			if loop-player doesn't have permission "group.spectators":
				if loop-player != player:
					make console execute command "hide %loop-player%"
					set {alive.%loop-player's uuid%} to false
					clear loop-player's inventory
					allow flight for loop-player
		broadcast "[&c&lTheEvent580&r] %player% is chosing the next game"
	if name of tool of player is "Swap players and spectators":
		loop all players:
			set {alive.%loop-player's uuid%} to false
			if loop-player has permission "group.spectators":
				set {alive.%loop-player's uuid%} to true
		loop all players:
			if {alive.%loop-player's uuid%} = false:
				make console execute command "hide %loop-player%"
				allow flight for loop-player
				clear loop-player's inventory
			else:
				make console execute command "hide %loop-player%"
				disable fly for loop-player
		broadcast "[&c&lTheEvent580&r] %{color.%player's uuid%}%%player%&r used the Players <> Spectators swap !"

on right click with minecart:
	if {timer} = 3:
		if targeted entity is a player:
			make console execute command "grab %targeted entity% %player%"
			remove 1 of minecart from player

on right click with compass:
	if name of tool of player is "Teleport to player":
		make player execute command "tpspec"

on right click :
	if player has permission "group.spectators":
		if {timer} is not "pause" or 0 or "Fin":
			cancel event
	if {timer} is not "pause":
		if {jeu_condi} is 0:
			if {timer} or {timer_save} is not 7 or 10 or "Fin":
				if event-block is lever:
					if {Herobrine.%player's uuid%} is false:
						make server execute command "achivement %player% give Herobrine"
		if {jeu_condi} is 0: #Spawn
			if event-block is oak_button:
				set helmet of player to carrot on a stick named "&rAsexual Flag"
				set {flag.%player%} to "&rAsexual Flag"
				send "[&c&lTheEvent580&r] You now have the Asexual flag on your head"
			if event-block is spruce_button:
				set helmet of player to carrot on a stick named "&rPride Flag"
				set {flag.%player%} to "&rPride Flag"
				send "[&c&lTheEvent580&r] You now have the Pride flag on your head"
			if event-block is birch_button:
				set helmet of player to carrot on a stick named "&rTransgender Flag"
				set {flag.%player%} to "&rTransgender Flag"
				send "[&c&lTheEvent580&r] You now have the Transgender flag on your head"
			if event-block is jungle_button:
				set helmet of player to carrot on a stick named "&rPansexual Flag"
				set {flag.%player%} to "&rPansexual Flag"
				send "[&c&lTheEvent580&r] You now have the Pansexual flag on your head"
			if event-block is acacia_button:
				set helmet of player to carrot on a stick named "&rLesbian Flag"
				set {flag.%player%} to "&rLesbian Flag"
				send "[&c&lTheEvent580&r] You now have the Lesbian flag on your head"
			if event-block is dark_oak_button:
				set helmet of player to carrot on a stick named "&rTrans-Inclusive Gay Men Flag"
				set {flag.%player%} to "&rTrans-Inclusive Gay Men Flag"
				send "[&c&lTheEvent580&r] You now have the Trans-Inclusive Gay Men flag on your head"
			if event-block is mangrove_button:
				set helmet of player to carrot on a stick named "&rNon Binary Flag"
				set {flag.%player%} to "&rNon Binary Flag"
				send "[&c&lTheEvent580&r] You now have the Non Binary flag on your head"
			if event-block is stone_button:
				set helmet of player to carrot on a stick named "&rBisexual Flag"
				set {flag.%player%} to "&rBisexual Flag"
				send "[&c&lTheEvent580&r] You now have the Bisexual flag on your head"
			if event-block is polished_blackstone_button:
				set helmet of player to carrot on a stick named "&rUnlabled Flag"
				set {flag.%player%} to "&rUnlabled Flag"
				send "[&c&lTheEvent580&r] You now have the Unlabled flag on your head"
			if event-block is red concrete:
				give 1 of apple to player
		if {jeu_condi} is 4: #Find The Button
			if {finished.%player%} is false:
				if event-block is oak_button:
					if {ftb_1.%player%} is false:
						if {ftb_1} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the oak button !"
							send "[&c&lTheEvent580&r] You found the oak button [&a+%{pts_lvl_1}% &r╣]" to player
						if {ftb_1} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the oak button !"
							send "[&c&lTheEvent580&r] You found the oak button [&a+%{pts_lvl_1}% &r╣]" to player
							set {ftb_1} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_oak_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_1.%player%} to true
						add {pts_lvl_1} to {points_game.%player's uuid%}
						add {pts_lvl_1} to {total_points.%player's uuid%}
						add {pts_lvl_1} to {total_points_event.%player's uuid%}
						remove 10*{multiplier} from {pts_lvl_1}
				if event-block is spruce_button:
					if {ftb_2.%player%} is false:
						if {ftb_2} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the spruce button !"
							send "[&c&lTheEvent580&r] You found the spruce button [&a+%{pts_lvl_2}% &r╣]" to player
						if {ftb_2} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the spruce button !"
							send "[&c&lTheEvent580&r] You found the spruce button [&a+%{pts_lvl_2}% &r╣]" to player
							set {ftb_2} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_spruce_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_2.%player%} to true
						add {pts_lvl_2} to {points_game.%player's uuid%}
						add {pts_lvl_2} to {total_points.%player's uuid%}
						add {pts_lvl_2} to {total_points_event.%player's uuid%}
						remove 15*{multiplier} from {pts_lvl_2}
				if event-block is acacia_button:
					if {ftb_3.%player%} is false:
						if {ftb_3} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the acacia button !"
							send "[&c&lTheEvent580&r] You found the acacia button [&a+%{pts_lvl_3}% &r╣]" to player
						if {ftb_3} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the acacia button !"
							send "[&c&lTheEvent580&r] You found the acacia button [&a+%{pts_lvl_3}% &r╣]" to player
							set {ftb_3} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_acacia_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_3.%player%} to true
						add {pts_lvl_3} to {points_game.%player's uuid%}
						add {pts_lvl_3} to {total_points.%player's uuid%}
						add {pts_lvl_3} to {total_points_event.%player's uuid%}
						remove 20*{multiplier} from {pts_lvl_3}
				if event-block is mangrove_button:
					if {ftb_4.%player%} is false:
						if {ftb_4} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the mangrove button !"
							send "[&c&lTheEvent580&r] You found the mangrove button [&a+%{pts_lvl_4}% &r╣]" to player
						if {ftb_4} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the mangrove button !"
							send "[&c&lTheEvent580&r] You just found the mangrove button [&a+%{pts_lvl_4}% &r╣]" to player
							set {ftb_4} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_mangrove_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_4.%player%} to true
						add {pts_lvl_4} to {points_game.%player's uuid%}
						add {pts_lvl_4} to {total_points.%player's uuid%}
						add {pts_lvl_4} to {total_points_event.%player's uuid%}
						remove 25*{multiplier} from {pts_lvl_4}
				if event-block is crimson_button:
					if {ftb_5.%player%} is false:
						if {ftb_5} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the crimson button !"
							send "[&c&lTheEvent580&r] You found the crimson button [&a+%{pts_lvl_5}% &r╣]" to player
						if {ftb_5} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the crimson button !"
							send "[&c&lTheEvent580&r] You found the crimson button [&a+%{pts_lvl_5}% &r╣]" to player
							set {ftb_5} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_crimson_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_5.%player%} to true
						add {pts_lvl_5} to {points_game.%player's uuid%}
						add {pts_lvl_5} to {total_points.%player's uuid%}
						add {pts_lvl_5} to {total_points_event.%player's uuid%}
						remove 30*{multiplier} from {pts_lvl_5}
				if event-block is polished_blackstone_button:
					if {ftb_6.%player%} is false:
						if {ftb_6} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the polished blackstone button !"
							send "[&c&lTheEvent580&r] You found the polished blackstone button [&a+%{pts_lvl_6}% &r╣]" to player
						if {ftb_6} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the polished blackstone button !"
							send "[&c&lTheEvent580&r] You found the polished blackstone button [&a+%{pts_lvl_6}% &r╣]" to player
							set {ftb_6} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_polished_blackstone_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_6.%player%} to true
						add {pts_lvl_6} to {points_game.%player's uuid%}
						add {pts_lvl_6} to {total_points.%player's uuid%}
						add {pts_lvl_6} to {total_points_event.%player's uuid%}
						remove 35*{multiplier} from {pts_lvl_6}
				if event-block is dark_oak_button:
					if {ftb_7.%player%} is false:
						if {ftb_7} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the dark oak button !"
							send "[&c&lTheEvent580&r] You found the dark oak button [&a+%{pts_lvl_7}% &r╣]" to player
						if {ftb_7} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the dark oak button !"
							send "[&c&lTheEvent580&r] You just found the dark oak button [&a+%{pts_lvl_7}% &r╣]" to player
							set {ftb_7} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_dark_oak_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_7.%player%} to true
						add {pts_lvl_7} to {points_game.%player's uuid%}
						add {pts_lvl_7} to {total_points.%player's uuid%}
						add {pts_lvl_7} to {total_points_event.%player's uuid%}
						remove 40*{multiplier} from {pts_lvl_7}
				if event-block is stone_button:
					if {ftb_8.%player%} is false:
						if {ftb_8} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the stone button !"
							send "[&c&lTheEvent580&r] You just found the stone button [&a+%{pts_lvl_8}% &r╣]" to player
						if {ftb_8} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the stone button !"
							send "[&c&lTheEvent580&r] You just found the stone button [&a+%{pts_lvl_8}% &r╣]" to player
							set {ftb_8} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_stone_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_8.%player%} to true
						add {pts_lvl_8} to {points_game.%player's uuid%}
						add {pts_lvl_8} to {total_points.%player's uuid%}
						add {pts_lvl_8} to {total_points_event.%player's uuid%}
						remove 45*{multiplier} from {pts_lvl_8}
				if event-block is warped_button:
					if {ftb_9.%player%} is false:
						if {ftb_9} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the warped button !"
							send "[&c&lTheEvent580&r] You found the warped button [&a+%{pts_lvl_9}% &r╣]" to player
						if {ftb_9} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the warped button !"
							send "[&c&lTheEvent580&r] You found the warped button [&a+%{pts_lvl_9}% &r╣]" to player
							set {ftb_9} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_warped_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_9.%player%} to true
						add {pts_lvl_9} to {points_game.%player's uuid%}
						add {pts_lvl_9} to {total_points.%player's uuid%}
						add {pts_lvl_9} to {total_points_event.%player's uuid%}
						remove 50*{multiplier} from {pts_lvl_9}
				if event-block is jungle_button:
					if {ftb_10.%player%} is false:
						if {ftb_10} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the jungle button !"
							send "[&c&lTheEvent580&r] You found the jungle button [&a+%{pts_lvl_10}% &r╣]" to player
							wait 1 second
						if {ftb_10} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the jungle button !"
							send "[&c&lTheEvent580&r] You found the jungle button [&a+%{pts_lvl_10}% &r╣]" to player
							set {ftb_10} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_jungle_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_10.%player%} to true
						add {pts_lvl_10} to {points_game.%player's uuid%}
						add {pts_lvl_10} to {total_points.%player's uuid%}
						add {pts_lvl_10} to {total_points_event.%player's uuid%}
						remove 55*{multiplier} from {pts_lvl_10}
				if event-block is birch_button:
					if {ftb_11.%player%} is false:
						if {ftb_11} is true:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r found the birch button !"
							send "[&c&lTheEvent580&r] You found the birch button [&a+%{pts_lvl_11}% &r╣]" to player
							wait 1 second
						if {ftb_11} is false:
							broadcast "[&c&lTheEvent580&r] &a&l%player%&r is the 1st player to find the birch button !"
							send "[&c&lTheEvent580&r] You just found the birch button [&a+%{pts_lvl_11}% &r╣]" to player
							set {ftb_11} to true
						play sound "custom:coins" in voice category with volume 2 to the player 
						add 1 to {total_buttons_pressed}
						add 1 to {ftb_birch_completed}
						add 1 to {ftb_fin.%player%}
						set {ftb_11.%player%} to true
						add {pts_lvl_11} to {points_game.%player's uuid%}
						add {pts_lvl_11} to {total_points.%player's uuid%}
						add {pts_lvl_11} to {total_points_event.%player's uuid%}
						remove 60*{multiplier} from {pts_lvl_11}

on place:
	if {timer} is "pause":
		if player doesn't have permission "group.spectators":
			cancel event
	else:
		if {jeu_condi} is 9:
			if block 1 meter under event-location is not quartz bricks:
				if gamemode of player is not creative:
					cancel event
					send "[&c&lTheEvent580&r] Please place the block in the replication zone only"

on swap hand item:
	if name of tool of player is "&eYour Bingo card":
		cancel event
	if name of tool of player is "&eTeleport to home":
		cancel event

on drop:
	if event-item is a paper named "&eYour Bingo card":
		cancel event
	if event-item is a carrot on a stick named "&eTeleport to home":
		cancel event
	if {jeu_condi} is 5 or 8 or 9:
		cancel event
	if player has permission "group.spectators":
		cancel event

on pickup:
	if player has permission "group.spectators":
		if {jeu_condi} is not 0:
			cancel event
	else:
		if {jeu_condi} is 8:
			cancel event
			make server execute command "execute at %player% run kill @e[type=minecraft:arrow,limit=1]"
		if {jeu_condi} is 9:
			set {_has_finished.%player%} to false
			loop {finished::*}:
				if loop-value is player:
					set {_has_finished.%player%} to true
			if {_has_finished.%player%} is true:
				cancel event
		if {jeu_condi} = 6 or 0:
			if {alive.%player%} = false:
				cancel event


on craft:
	if {jeu_condi} is not 3 or 6:
		cancel event

on player world change:
	loop all players:
		if loop-player has permission "thefox580.staff":
			if event-player doesn't have permission "group.spectators":
				send "[&c&lTheEvent580&r] Player &c&l%event-player%&r got teleported from &6&l%past event-world%&r to &a&l%event-world%&r, loading texture pack..." to loop-player
	send title "PLEASE STANDBY" with subtitle "for the texture pack to download" to player for 5 seconds
	wait 2 second
	if event-world is "world":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/00f58e93166e5deb00f98d74f94e37f67ef84350.zip 00f58e93166e5deb00f98d74f94e37f67ef84350" #Spawn
	if event-world is "dropper":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Dropper
	if event-world is "parkour":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/1c42f10ba02c0ea9a19180dbe4bc4d2e66f17a26.zip 1c42f10ba02c0ea9a19180dbe4bc4d2e66f17a26" #Parkour
	if event-world is "bingo":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/5b7cf07cb063037d9c8a7fe3fcfc98f89ab35a38.zip 5b7cf07cb063037d9c8a7fe3fcfc98f89ab35a38" #Bingo
	if event-world is "find_the_button":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Find The Button
	if event-world is "races_lap_3":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/2d6d579a86304775612992fdcac5d645783889e6.zip 2d6d579a86304775612992fdcac5d645783889e6" #Multilap
	if event-world is "build_masters":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/d7af2588cb9bcb13535c952d915e5919ad0bd166.zip d7af2588cb9bcb13535c952d915e5919ad0bd166" #Build Masters
	if event-world is "SG1" or "SG2" or "SG3" or "SG4" or "SG5" or "SG6":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Survival Games
	if event-world is "Bow_PVP":
		make console execute command "setrp %player% https://download.mc-packs.net/pack/aad686964cba9ba0684473978c9f1caafdc298ea.zip aad686964cba9ba0684473978c9f1caafdc298ea" #Bow PVP

on shoot:
	if {timer} is 3:
		wait 3 seconds
		kill event-projectile

on jump:
	if event-world = "world":
		if block 1 meter under player is deepslate coal ore:
			if the y-coordinate of player = -5:
				teleport player to location(328.5, 69.5, 316.5, world "world", 150, 0.0001)
				remove night vision from the player
	if event-world = "Build_Masters":
		if block 0 meter under event-player = green carpet or cyan carpet:
			remove jump boost from event-player
			apply jump boost 6 without particles to event-player for 2 ticks
			push event-player up at speed 2
		if block 0 meter under event-player = yellow carpet:
			remove jump boost from event-player
			apply jump boost 3 without particles to event-player for 2 ticks
			push event-player east at speed 3
		if block 0 meter under event-player = red carpet:
			remove jump boost from event-player
			apply jump boost 3 without particles to event-player for 2 ticks
			push event-player west at speed 3
		if block 0 meter under event-player = orange carpet:
			remove jump boost from event-player
			apply jump boost 3 without particles to event-player for 2 ticks
			push event-player north at speed 3
		if block 0 meter under event-player = lime carpet:
			remove jump boost from event-player
			apply jump boost 3 without particles to event-player for 2 ticks
			push event-player south at speed 3
		
on sneak toggle:
	if block 1 meter under player is deepslate coal ore:
		if the y-coordinate of player = 69:
			teleport player to location(315.5, -4.5, 323.5, world "world", -90, 0.0001)
			make console execute command "effect give %player% minecraft:night_vision infinite 255 true"
